### PR TITLE
layers: Added support for VUID 01560

### PR DESCRIPTION
**Pull request by sfricke-samsung**
Wrote a test to verify support as well

### CODE REVIEW

**Comment by sfricke-samsung** [comment]
hmm, I see the test I wrote fails with some of the CI builds, will find some time to look into that when possible

**Comment by sjfricke** [comment]
@mark-lunarg So I can't figure out what is wrong here

So it seems to be failing in vklayertests_command.cpp

```
    m_errorMonitor->SetDesiredFailureMsg(VK_DEBUG_REPORT_ERROR_BIT_EXT, "VUID-vkCmdCopyBufferToImage-commandBuffer-recording");
    vk::CmdCopyBufferToImage(m_commandBuffer->handle(), buffer_64k.handle(), image_64k.handle(), VK_IMAGE_LAYOUT_GENERAL, 1,
                             &region);
    m_errorMonitor->VerifyFound();
```

It should be hitting the first error

```
// CoreChecks::PreCallValidateCmdCopyBufferToImage
skip |= ValidateCmd(cb_node, CMD_COPYBUFFERTOIMAGE, "vkCmdCopyBufferToImage()");
```

first, but I think adding maintaince_1_khr someone is tripping `VUID-vkCmdCopyBufferToImage-dstImage-01997` after, but not sure why that would cause it to fail the test

worst of all I can't reproduce
```
VK_LAYER_PATH=$ROOT/VulkanTools/build/layersvt/:$ROOT/Vulkan-ValidationLayers/build/layers/ LD_LIBRARY_PATH=$ROOT/Vulkan-Loader/build/loader/:$LD_LIBRARY_PATH VK_ICD_FILENAMES=$ROOT/Vulkan-Tools/build/icd/VkICD_mock_icd.json VK_INSTANCE_LAYERS="VK_LAYER_LUNARG_device_simulation" VK_DEVSIM_FILENAME=$ROOT/Vulkan-ValidationLayers/tests/device_profiles/mobile_chip.json tests/vk_layer_validation_tests --devsim --gtest_filter=*ImageBufferCopyTests
```
and get it to work
```
Note: Google Test filter = *ImageBufferCopyTests
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from VkLayerTest
[ RUN      ] VkLayerTest.ImageBufferCopyTests
             TEST SKIPPED: Depth / Stencil formats unsupported - skipping D/S tests.
             TEST SKIPPED: VK_FORMAT_G8_B8R8_2PLANE_420_UNORM destination transfer not supported; skipped.
[       OK ] VkLayerTest.ImageBufferCopyTests (23 ms)
[----------] 1 test from VkLayerTest (23 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (23 ms total)
[  PASSED  ] 1 test.
```

**Comment by sfricke-samsung** [comment]
@mark-lunarg So I can't figure out what is wrong here

So it seems to be failing in vklayertests_command.cpp

```
    m_errorMonitor->SetDesiredFailureMsg(VK_DEBUG_REPORT_ERROR_BIT_EXT, "VUID-vkCmdCopyBufferToImage-commandBuffer-recording");
    vk::CmdCopyBufferToImage(m_commandBuffer->handle(), buffer_64k.handle(), image_64k.handle(), VK_IMAGE_LAYOUT_GENERAL, 1,
                             &region);
    m_errorMonitor->VerifyFound();
```

It should be hitting the first error

```
// CoreChecks::PreCallValidateCmdCopyBufferToImage
skip |= ValidateCmd(cb_node, CMD_COPYBUFFERTOIMAGE, "vkCmdCopyBufferToImage()");
```

first, but I think adding maintaince_1_khr someone is tripping `VUID-vkCmdCopyBufferToImage-dstImage-01997` after, but not sure why that would cause it to fail the test

worst of all I can't reproduce
```
VK_LAYER_PATH=$ROOT/VulkanTools/build/layersvt/:$ROOT/Vulkan-ValidationLayers/build/layers/ LD_LIBRARY_PATH=$ROOT/Vulkan-Loader/build/loader/:$LD_LIBRARY_PATH VK_ICD_FILENAMES=$ROOT/Vulkan-Tools/build/icd/VkICD_mock_icd.json VK_INSTANCE_LAYERS="VK_LAYER_LUNARG_device_simulation" VK_DEVSIM_FILENAME=$ROOT/Vulkan-ValidationLayers/tests/device_profiles/mobile_chip.json tests/vk_layer_validation_tests --devsim --gtest_filter=*ImageBufferCopyTests
```
and get it to work
```
Note: Google Test filter = *ImageBufferCopyTests
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from VkLayerTest
[ RUN      ] VkLayerTest.ImageBufferCopyTests
             TEST SKIPPED: Depth / Stencil formats unsupported - skipping D/S tests.
             TEST SKIPPED: VK_FORMAT_G8_B8R8_2PLANE_420_UNORM destination transfer not supported; skipped.
[       OK ] VkLayerTest.ImageBufferCopyTests (23 ms)
[----------] 1 test from VkLayerTest (23 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (23 ms total)
[  PASSED  ] 1 test.
```

**Comment by mark-lunarg** [comment]
Looking into the issues now.

**Comment by mark-lunarg** [comment]
@sfricke-samsung, finally figured this out.  Had the same issue with not being able to repro locally, turns out it's probably due to including the `VK_INSTANCE_LAYERS `in your command for running the tests.  The `--devsim` parameter explicitly loads this layer in the right spot -- explicitly loading it here puts it AFTER the khronos layer, screwing up the format property values.

After getting that right, I'm thinking these new errors are because you are enabling the `MAINTENANCE1 `extension.  This enables the validation for 01997 and others.  You might want to add defensive code for those checks, or split the test to avoid the collisions.

The repo preference is to have validation layer changes on one (or more) commits, followed by one or more commits containing the tests changes.  Please fold in or squash the other changes as appropriate.  Thanks for your patience!

**Comment by sfricke-samsung** [comment]
Ok thanks for helping me debug this.

Also I have added a few other PR, will also update the commits to be for validation and tests there as well. I am in the process of trying to add more Validation for Android centric items so still new to the repo, but happy to make needed changes to any of my PR to fit consistency!

**Comment by mark-lunarg** [comment]
@sfricke-samsung, thanks -- I apologize for not replying sooner to help you in avoiding some rework.  We really appreciate all of the help, this is great!

**Comment by mark-lunarg** [comment]
Running through CI.

**Pull request merged**
