### PR TITLE
layers: don't include DRM modifiers in queries

### PR DESCRIPTION
**Pull request by djdeath**
Unless enabled on the VkDevice.

Would that help for #3673 ?

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
LGTM, thanks for the quick fix @djdeath!

@Kangz any chance you can confirm this change resolves the issue you're seeing?

**Comment by Kangz** [comment]
I confirm that it fixes the ASSERT I was seeing, but looking at the code, it seems there are more places that would need to be fixed (for example fmtProps3 might not be available, etc). It seems the helper to build the extension changes would need to be updated to more easily add, but only if the extension is present (without breaking the chain).

**Comment by ncesario-lunarg** [comment]
Thanks for the input @Kangz, and yes, that looks like the case to me as well. @djdeath if you prefer I can merge this now and create an create an issue to clean up the rest of these cases?

**Comment by djdeath** [comment]
> I confirm that it fixes the ASSERT I was seeing, but looking at the code, it seems there are more places that would need to be fixed (for example fmtProps3 might not be available, etc). It seems the helper to build the extension changes would need to be updated to more easily add, but only if the extension is present (without breaking the chain).

I could be wrong, but all the occurences of `VkFormatProperties3KHR` seem to be within a `if (has_format_feature2)` block which should guarantee the associated extension is supported.

**Comment by djdeath** [comment]
> Thanks for the input @Kangz, and yes, that looks like the case to me as well. @djdeath if you prefer I can merge this now and create an create an issue to clean up the rest of these cases?

Feel free to merge now and we can open an issue with a list of invalid calls. Thanks!

**Pull request merged**
