### PR TITLE
Clang tidy performance

### PR DESCRIPTION
**Pull request by juan-lunarg**
Various clang-tidy performance fixes:
- [performance-unneccessary-value-param](https://clang.llvm.org/extra/clang-tidy/checks/performance/unnecessary-value-param.html)
- [performance-for-range-copy.](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-for-range-copy.html)
- [performance-faster-string-find](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-faster-string-find.html)
- [performance-type-promotion-in-math-fn](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-type-promotion-in-math-fn.html)

### CODE REVIEW

**Comment by juan-lunarg** [comment]
Each clang-tidy issue is put in it's own commit for reviewer readability

**Comment by juan-lunarg** [comment]
FWIW clang-tidy actually did most of the work for me so I didn't have to write much for this PR.

**Review by spencer-lunarg — APPROVED** [review]
thanks for breaking into 4 commits to easily see each passes fix

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM

**Pull request merged**
