### PR TITLE
layers: Fix index buffer size treatment

### LINKED ISSUE #5575: CoreChecks::ValidateCmdDrawIndexedBufferSize is double-counting the offset
Seeing failures in ANGLE, I took a look and this code is double-counting the index offset:

```
        VkDeviceSize end_offset = static_cast<VkDeviceSize>(index_size * (firstIndex + indexCount)) + index_buffer_binding.offset;
        if (end_offset > index_buffer_binding.size) {
```

I see that `index_buffer_binding.size + index_buffer_binding.offset` is the create info size, so clearly `index_buffer_binding.size` has already taken offset into account. `end_offset` can just drop `+ index_buffer_binding.offset`.

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Fixing earlier change that make bound index buffer size *consistent* with bound vertex buffers, but didn't account for it's usage a CoreChecks validation.

Fixes #5575

### CODE REVIEW

**Comment by jzulauf-lunarg** [comment]
@Tony-LunarG -- can you check against your case?

**Review by ncesario-lunarg — APPROVED** [review]

**Comment by ncesario-lunarg** [comment]
Should we have a test case for this? e.g., if the check for 07825 in `VkLayerTest.MultiDrawTests` used an offset other than 0, would we have caught this earlier?

**Comment by jzulauf-lunarg** [comment]
Would have needed a positive test with a non-zero offset.

**Comment by ncesario-lunarg** [comment]
> Would have needed a positive test with a non-zero offset.

Yes, that should probably be added.

**Review by juan-lunarg — DISMISSED** [review]
Add a positive test

**Comment by jzulauf-lunarg** [comment]
Add two cases to existing test, the first of which functions as a positive test, since we don't allow any unexpected at this point.

**Comment by jzulauf-lunarg** [comment]
Just noted I need to update the error message.

**Review by juan-lunarg — APPROVED** [review]
LGTM thanks for the added testing :+1:

**Pull request merged**
