### PR TITLE
scripts: Fix struct members not in IsFieldPointer

### PR DESCRIPTION
**Pull request by spencer-lunarg**
Fix typo in script and not populating the `IsFieldPointer` correctly

### CODE REVIEW

**Comment by aqnuep** [comment]
LGTM.

**Review by arno-lunarg — APPROVED** [review]
LGTM

I wonder about how efficient it is to have this `IsFieldPointer` logic in such a long case list?
I think that doing a lookup in a sorted `Field` array would be more efficient at this point

**Comment by spencer-lunarg** [comment]
> I wonder about how efficient it is to have this IsFieldPointer logic implemented using a huge case list?

Well this code is only every executed at error logging time, which we have historically put on the back of any performance bottle neck (since in theory it should never be hit if apps are good)

I agree this probably could be done more efficient, but argue that without measuring, the simplicity here out-weighs any real world benefits I imagine we would see in perf

**Comment by arno-lunarg** [comment]
Yes some quick perf test show that the case list is still completely ok

**Comment by artem-lunarg** [comment]
Was curious and checked codegen. It's efficient. For enum value `Field::pDependencyInfo` == 1328 it runs a dozen of instructions in total to get the result (lets see if github supports animated gifs).

is_field_pointer

**Pull request merged**
