### PR TITLE
[WIP] Move headers to include/vulkan subdir

### PR DESCRIPTION
**Pull request by stephanlachnit**
This is a WIP as followup for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2307.

Basically, if all headers are now installed with a `vulkan` prefix, so should the source code use this prefix as well. This also has the nice benefit of restoring the possibility to use this repo as fallback for Meson's Wrap DB.

### CODE REVIEW

**Comment by stephanlachnit** [comment]
To get this to work, this `if` statement needs to be dropped: https://github.com/KhronosGroup/Vulkan-Headers/blob/30e70cbd9850560cb55bffadb8017e90c04c42f5/registry/generator.py#L674

**Comment by mark-lunarg** [comment]
@stephanlachnit, obviously this is a sweeping change, and (as you have seen) has impacts on other upstream and downstream repositories. We'll discuss it internally in the next several days.

**Comment by mark-lunarg** [comment]
@stephanlachnit, after internal discussions we intend to keep the repo include structure as-is for the time being.  These files aren't intended to be public-facing as are the ones in Vulkan-Headers for instance.  There is also risk for down-stream repositories.  In any case it appears that the main motivation for these changes is related to the VulkanTools build, and it is our intention to remove the VulkanTools dependencies upon the Vulkan-ValidationLayers repo.

**Comment by stephanlachnit** [comment]
Alright, thanks for clarifying.

**Pull request closed without merging**
