### PR TITLE
layers: Make PreCallValidate const

### PR DESCRIPTION
**Pull request by jeffbolznv**
This is stacked on #1304. This new commit is entirely mechanical changes to make PreCallValidate methods const.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Will push through CI when green.

**Comment by jeffbolznv** [comment]
CI failure looks like a network hiccup.

**Comment by mark-lunarg** [comment]
It's in internal CI now.

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by mark-lunarg** [comment]
This is crashing on rel and dbg Linux builds in CI (tescase is VkLayerTest.BindImageMemorySwapchain) -- haven't been able to repro locally yet but am working on it.

**Comment by mark-lunarg** [comment]
CI issue was mine, looks great!  Pushed to Master.

**Pull request merged**
