### PR TITLE
Improve coverage for sparse image binds

### PR DESCRIPTION
**Pull request by r-potter**

### CODE REVIEW

**Comment by spencer-lunarg** [comment]
noting this will mark off a VU from https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4047

**Comment by r-potter** [comment]
@spencer-lunarg Do you happen to know what implementation the address sanitizer builds run on? One of the added tests appears to be failing to emit an expected validation error, and one possible reason might be that the image memory alignment requirement is one byte (and so it's impossible to misalign the bind). I'd like to confirm that before making any changes

**Comment by spencer-lunarg** [comment]
> Do you happen to know what implementation the address sanitizer builds run on?

that is just `TestICD` (aka `MockICD`) (since it is on github and there are not real GPUs there)

it is failing on the `Thread sanitizer` build as well, so it is not an issue with `address sanitizer` but rather Linux with TestICD

I see it is failing other real GPU as well that is not getting the check

My suggest would be to move the 2 new "sub-tests" to just be its own `TEST_F` for each variation, then it will be much easier to detect what is wrong with which one (currently I am not sure which of the 2 new sub-test is not hitting the VU, hence why I prefer smaller tests in general)

**Comment by spencer-lunarg** [comment]
@r-potter I can try and took a look locally later today why both tests are failing

**Comment by r-potter** [comment]
> @r-potter I can try and took a look locally later today why both tests are failing

Thanks @spencer-lunarg but hopefully no need. I just pushed what *should* be the solution. It appears to be minimum alignment of 1 making it impossible to violate the VU on those devices, so just added a skip in that case

**Comment by r-potter** [comment]
@spencer-lunarg I guess I have to take that back. MockICD tests are resolved, but I have no way to verify what the issue with the AMD 6800 in CI is

**Comment by spencer-lunarg** [comment]
>  but I have no way to verify what the issue with the AMD 6800 in CI is

We need to fix how the webhooks don't print the actual error, but it is

> Validation Error: [ VUID-vkAllocateMemory-deviceCoherentMemory-02790 ] | MessageID = 0x8830dc95 | vkAllocateMemory(): pAllocateInfo->memoryTypeIndex 4 includes the VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD memory property, but the deviceCoherentMemory feature is not enabled.

I am going to just mark this to skip on AMD Windows for now, I will soon have a better way to reproduce, otherwise you are just going to be sending guesses to get it to work and rather have someone with a local device reproduce it

**Pull request merged**
