### PR TITLE
Cache instrumented shaders when running with GPU-AV

### PR DESCRIPTION
**Pull request by Tony-LunarG**
Cache instrumented shaders to disk to keep from having to instrument them on every run.

### CODE REVIEW

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM! Have you run this on any of the traces yet or do you need me to do that on the perf machine?

**Comment by Tony-LunarG** [comment]
> LGTM! Have you run this on any of the traces yet or do you need me to do that on the perf machine?

I've only tried Doom Eternal 370 frames (which is trimmed and wouldn't reflect savings in FPS) and the surge, which went from 15.6 to 16.2 fps.  The Jenkins job didn't see anything. If you have the cycles to try it out, that would be helpful.

**Comment by jeremyg-lunarg** [comment]
I ran it last night and there wasn't a huge perf difference so go for it if you think this is ready to merge

**Comment by Tony-LunarG** [comment]
I'm going to run CTS on it tonight, then merge if nothing found

**Pull request merged**
