### PR TITLE
scripts: Report unassigned VUIDs in stats

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@shannon-lunarg, this LGTM, can you please make sure your workflow is still fine?

**Comment by mark-lunarg** [comment]
@shannon-lunarg, have you had a chance to check this one out?

**Comment by shannon-lunarg** [comment]
@mark-lunarg I started looking at this just before lunch. Will comment here once I can verify everything is working for me.

**Comment by shannon-lunarg** [comment]
This addition doesn't affect my workflow and produces the same output with and without these changes for what I use the script for.

**Comment by mark-lunarg** [comment]
Thank you very much @shannon-lunarg!

**Pull request merged**
