### PR TITLE
tests: Restore Sync ordering test.

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Fix the broken begin render pass and restore the test that required
success.

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]

**Comment by ncesario-lunarg** [comment]
Might be good to run these tests with core checks enabled. @paul-lunarg is seeing a lot of core validation failures in syncval tests.

**Review by jeremyg-lunarg — APPROVED** [review]

**Comment by jzulauf-lunarg** [comment]
@ncesario-lunarg  -- reworked the queue submit tests with to run cleanly with CoreChecks etc enabled.  Fixes in the last commit (the other is just a code relocation)

**Review by ncesario-lunarg — APPROVED** [review]
Great! So does this mean that all syncval tests now pass with core checks enabled?

**Comment by jzulauf-lunarg** [comment]
@ncesario-lunarg  -- only cleans up the Core/etc error for the tests that were sporadically failing.  A full cleanup isn't on my schedule until phase II sync val is alpha, but new tests are being checked for Core cleanness as they are added.

**Comment by ncesario-lunarg** [comment]
👍 that sounds good. I think I (or someone) can at least do a first pass looking at any core errors in syncval tests and hopefully get most of them sorted out.

**Pull request merged**
