### PR TITLE
layers: Rewrite flag validation 

### PR DESCRIPTION
**Pull request by krOoze**
- use proper VUID
- eliminate dependency on std::bitset
- do not use raw bool parameters
- make single bit, and unknown bit checks independent
- merge single bit and Flags generation script

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@krOoze, can you rebase this guy?

**Comment by krOoze** [comment]
@mark-lunarg Rebased, but PR is always a girl!

**Comment by mark-lunarg** [comment]
Might be that the girl needs to have her generated files regenerated! :grimacing:

**Comment by krOoze** [comment]
I guess I was too lazy trusting a merge tool.

**Comment by krOoze** [comment]
Actually seems like trunk is failing CI...

**Comment by krOoze** [comment]
Attempt numero deux.

**Comment by mark-lunarg** [comment]
Rebased and running through CI.

**Pull request merged**
