### PR TITLE
Support for VK_KHR_performance_query

### PR DESCRIPTION
**Pull request by djdeath**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@djdeath, the known_good.json file will be updated by @shannon-lunarg as part of the norm[al update process](https://github.com/KhronosGroup/Vulkan-Headers/wiki/Integrating-Updated-Vulkan-Headers-into-Vulkan-Repositories).  Until that happens, the build/CI may be unstable. After that has been completed and pushed to the repo, then we can rebase and continue with the merge.  Thanks for bringing it over.

**Comment by mark-lunarg** [comment]
@djdeath, please click through the CLA, we'll need that to get an all-green board.

**Comment by djdeath** [comment]
I'm afraid I have no idea about the linking error on one of the builder : 
```
python "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm" --sofile="./libVkLayer_khronos_validation.so" --tocfile="./libVkLayer_khronos_validation.so.TOC" --output="./libVkLayer_khronos_validation.so" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-Bsymbolic,--exclude-libs,ALL -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--color-diagnostics -m64 -Wl,--gdb-index -rdynamic --sysroot=../../build/linux/debian_sid_amd64-sysroot -L../../build/linux/debian_sid_amd64-sysroot/usr/local/lib/x86_64-linux-gnu -L../../build/linux/debian_sid_amd64-sysroot/lib/x86_64-linux-gnu -L../../build/linux/debian_sid_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath=\$ORIGIN -Werror -o "./libVkLayer_khronos_validation.so" -Wl,-soname="libVkLayer_khronos_validation.so" @"./libVkLayer_khronos_validation.so.rsp"
ld.lld: error: undefined symbol: vtable for CommandCounter
>>> referenced by command_counter.h:23 (../../layers/command_counter.h:23)
>>>               obj/VkLayer_khronos_validation/chassis.o:(CommandCounter::CommandCounter(CoreChecks*))
the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by djdeath** [comment]
Maybe the virtual destructor?

**Comment by djdeath** [comment]
Looking forward to tips on this. I can't reproduce on any of my Linux machines.

**Comment by mark-lunarg** [comment]
@djdeath, am checking now this with the new headers.  The newly implemented VU checks will also need accompanying tests, will these come in a follow-on PR?

**Comment by djdeath** [comment]
> @djdeath, am checking now this with the new headers. And I now see the tests!

Cool, your previous message got me to check the PR and I noticed a couple of VUID checks missing.

**Comment by mark-lunarg** [comment]
@djdeath, had to pick up a new vulkan-headers fix and then add command_counter_helper.cpp to the android build to get that to work -- running through CI again.

**Comment by mark-lunarg** [comment]
Split into separate commits for validation and tests, rebased, tested, and pushed to Master.  Thanks @djdeath for all the good work.

**Pull request closed without merging**
