### PR TITLE
gpu: Skip present submission

### PR DESCRIPTION
**Pull request by artem-lunarg**
Addresses performance regression https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7562

Present batch does not have any GPU-AV work to post process. This is also needed for correctness. QueuePresent does not have a PostSubmit call that signals timeline semaphore - timeline wait is invalid.

### CODE REVIEW

**Review by jeremyg-lunarg — APPROVED** [review]

**Comment by spencer-lunarg** [comment]
Ran locally, I still seem to be maxed at 60FPS for NVIDIA Windows cards (should be capable of more, AMD CPU gets like 200+ FPS), but it still seems to solve the issue of getting fully blocked like we were
cc @SaschaWillems @SRSaunders

**Comment by SRSaunders** [comment]
@artem-lunarg and @spencer-lunarg thanks for fixing this.  Was the issue specific to nVidia, or was it somehow broader?

I presume this fix will be in the next SDK - please confirm.

**Comment by spencer-lunarg** [comment]
> I presume this fix will be in the next SDK - please confirm.

100% - you can test it now if you want, we keep built binaries (for 3 days until github destroys them) of the latest CI runs

(https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/11581823228)

**Comment by SRSaunders** [comment]
>  you can test it now if you want, we keep built binaries (for 3 days until github destroys them) of the latest CI runs

@spencer-lunarg is there something special needed to test with this binary?  If I drop it into my Windows 10 + SDK 1.3.296 installation, replacing the older **VkLayer_khronos_validation.dll**, the application fails during `vkCreateInstance()` on my AMD GPU machine.  Have not tried it with nVidia yet.  Any advice?

**Comment by spencer-lunarg** [comment]
@SRSaunders I tried myself and just swapping the ` VkLayer_khronos_validation.dll` worked for me (saw it go from 0fps to 120fps)

Maybe something is wrong with the JSON, you can just replacing it with the latest JSON (that was since been changed from the SDK)
[VkLayer_khronos_validation.json](https://github.com/user-attachments/files/17581211/VkLayer_khronos_validation.json)

**Comment by SRSaunders** [comment]
@spencer-lunarg I finally had some time to retest on my nVidia machine and the updated binary (dropping in just the dll) works very well there - going from 0 fps to 1600 fps.

On my AMD machine I updated my GPU drivers and after dropping in the new dll I still get good performance (about 1200 fps), so no regression seen there now.

Thanks to you and @artem-lunarg for fixing this and I look forward to the improvement in the next SDK.

**Pull request merged**
