### PR TITLE
layers: Set Tessellation CreateInfo pNext

### PR DESCRIPTION
**Pull request by locke-lunarg**
Set VkPipelineTessellationDomainOriginStateCreateInfo 
in VkPipelineTessellationStateCreateInfo.pNext.
[Issue #747](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/747)

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@locke-lunarg, this looks great!  Our *general* policy is that new validation checks or bugfixes should come with an associated test -- would it be too much trouble to add a test (maybe a positive test) that would ensure this fix is working correctly?

**Comment by locke-lunarg** [comment]
> @locke-lunarg, this looks great! Our _general_ policy is that new validation checks or bugfixes should come with an associated test -- would it be too much trouble to add a test (maybe a positive test) that would ensure this fix is working correctly?

**Comment by locke-lunarg** [comment]
> @locke-lunarg, this looks great! Our _general_ policy is that new validation checks or bugfixes should come with an associated test -- would it be too much trouble to add a test (maybe a positive test) that would ensure this fix is working correctly?

Sure. I will add a new test.

**Comment by locke-lunarg** [comment]
> @locke-lunarg, this looks great! Our _general_ policy is that new validation checks or bugfixes should come with an associated test -- would it be too much trouble to add a test (maybe a positive test) that would ensure this fix is working correctly?

Sure. I have added a test for that.

**Pull request merged**
