### PR TITLE
state_tracker: remove 'using std::*' statements

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
Some of the types were no longer used in the code.

Change-Id: I810a172c7d84febd6272eca83373aa7ad1758e42

### CODE REVIEW

**Review by mark-lunarg — APPROVED** [review]
Welcome Jeremy, this looks great!  Only the tiniest nit, we capitalize the first word of the commit messages after the ':'.  LGTM after a green board.

**Comment by jeremyg-lunarg** [comment]
> Welcome Jeremy, this looks great! Only the tiniest nit, we capitalize the first word of the commit messages after the ':'. LGTM after a green board.



> Welcome Jeremy, this looks great! Only the tiniest nit, we capitalize the first word of the commit messages after the ':'. LGTM after a green board.

Thanks! If I re-upload the change with only the commit message different, will it invalidate or restart CI?

**Comment by mark-lunarg** [comment]
> Thanks! If I re-upload the change with only the commit message different, will it invalidate or restart CI?

Yeah, if you force-push to the same branch it all happens like magic. For code-review or CI-related changes like this it's preferable to modify or amend the original commits instead of just adding a fix-commit to the top anyway.

**Comment by mark-lunarg** [comment]
@jeremyg-lunarg, your PR is passing CI (internal and external) and you have an approval, so you can push the `Rebase and merge` button at your leisure.  Congratulations!

**Pull request merged**
