### PR TITLE
layers: Add extra api names to errors

### PR DESCRIPTION
**Pull request by sfricke-samsung**
General cleanup on some log messages to add API name to error

Labled `VUID-vkCreateSampler-maxSamplerAllocationCount-04110`

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
Running through internal CI.

**Comment by ncesario-lunarg** [comment]
Our travis builds are still having some issues, but this is failing in our internal CI with the following:
```
VkLayerTest.ExceedSamplerAllocationCount
Unexpected: Validation Error: [ VUID_Undefined ] Object 0: handle = 0x798d0c0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x79de34d4 | vkCreateSampler(): Number of currently valid sampler objects (32) is not less than the maximum allowed (32).
Other error messages logged for this test were:
     Validation Error: [ VUID_Undefined ] Object 0: handle = 0x798d0c0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x79de34d4 | vkCreateSampler(): Number of currently valid sampler objects (32) is not less than the maximum allowed (32).
```

Seeing as this change doesn't appear to change any logic, this doesn't make sense to me.

@sfricke-samsung, would you mind rebasing this on top of master and see if you can reproduce this? Also, if you rebase and push/force-push to this branch, that should hopefully re-trigger the travis job and it will _actually run_ this time.

**Comment by sfricke-samsung** [comment]
@ncesario-lunarg no need to rebase... CI doing its job correctly! (sorry, I must had my local setup messed up as I realized my internal CI was not running correctly, normally I catch these before pushing up PR)

So this actually is a good accident because I forgot `VUID-vkCreateSampler-maxSamplerAllocationCount-04110`  finally is pushed up in the headers and forgot to label the validation with it

Also the issue is that some of the older tests are like

```
m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "Number of currently valid sampler objects is not less than the maximum allowed");
```

where it tried to string match the messages when there wasn't a VUID assigned... so properly assigned the VUID, fixed CI, and should be all good to go now!!!

**Review by ncesario-lunarg — APPROVED** [review]

**Comment by ncesario-lunarg** [comment]
Awesome, thank you @sfricke-samsung!

**Pull request merged**
