### PR TITLE
[WIP] layers: Capitalize fn names in vk_layer_config.h

### PR DESCRIPTION
**Pull request by krOoze**
per styleguide

will fail CI, and needs to be synced with the other repo.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@krOoze, synchronizing with the other repo is quite a bit of work. Let's avoid this for a single rename (there are dozens that need to be updated). I've had the lvl_find_in_chain (and friends) in my sights for awhile now, but haven't proceeded for this same reason.

**Comment by krOoze** [comment]
@mark-lunarg Some other renames are at #1246. I split this because it specifically fails CI.

**Comment by mark-lunarg** [comment]
Ah, I see.  Just getting to that one...

**Comment by mark-lunarg** [comment]
Did some work to untangle the repos which should help.  Will revisit this one after this round of SDK-churn is over.

**Comment by mark-lunarg** [comment]
@krOoze, do you mind if I close this PR?  It's on our internal projects list to do a conformance pass for our 'guidelines', perhaps after the repos have been untangled a bit more.

**Comment by krOoze** [comment]
sure

**Comment by mark-lunarg** [comment]
Closing for now.  We will revisit and use these changes when the conformance scrub takes place, after some of the repo intern-dependencies have been reworked.  Thanks!

**Pull request closed without merging**
