### PR TITLE
AMD's best practices

### PR DESCRIPTION
**Pull request by nadavgevaAMD**
This PR extends the Best Practice layer with AMD specific recommendations. The PR follows the mechanism used by Arm to enable the layer, and includes unit tests for the new best practice checks.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@nadavgevaAMD, thanks for this, it's looking great.  Went over it quickly and noticed a few things -- once those are taken care of and CI is all clean (looks like a rebase is needed) we'll run it through the full process.

Ideally we'd prefer the changes split into a separate commits by intention.  For example , a commit for the code-cleanup and spell-checking, one for adding the `commands_in_buffer` tracking, maybe one or two for the new AMD layer options and for setting up BP to use the ARM/AMD-specific specifiers, a commit for the AMD BP changes and a final one for the new tests. At least as much as it makes sense (each commit should be bisectable, meaning the repo should build and run without error at any point in the git log, so it may not always be possible to split things cleanly).  This'll help reviewing, debugging, and maintenance over the long-term.  Lastly, local variable names need to be **lower_snake_case**, function names **UpperCamelCase**.

**Comment by nadavgevaAMD** [comment]
Need to sort some legal issues

**Comment by mark-lunarg** [comment]
@nadavgevaAMD, if it helps, a couple of other AMD folks have previously contributed.  You can find them [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/graphs/contributors).

**Comment by nadavgevaAMD** [comment]
@mark-lunarg, I need to clarify the legal status of contributing. Unfortunately, with the year end, seems unlikely to happen quickly. I've addressed your other comments (rebased, splitting the commits, fixing letter case, all unit tests passing locally), so should be good to go once that happens (up to rebase).

**Comment by mark-lunarg** [comment]
Thank you very much!  Looking forward to getting all this good stuff into the repo.

**Pull request closed without merging**
