### PR TITLE
layers: Update xxhash to 0.8.1

### PR DESCRIPTION
**Pull request by juan-lunarg**
While the main improvements have mainly been about new hashing algorithms. There have been performance improvments to XXH32 since 0.6.2, which is what VVL currently uses.

See release notes frome details:
https://github.com/Cyan4973/xxHash/releases

### CODE REVIEW

**Comment by juan-lunarg** [comment]
Also while XXH32 is the appropriate algorithm for usage with VUID's which require a 32 bit hash due to `VkDebugUtilsMessengerCallbackDataEXT` it may be worth looking into the newer hash algorithms for shader hashing. Which doesn't have the same limitation.

Metrics on hash performance:
https://github.com/Cyan4973/xxHash/tree/v0.8.1#benchmarks

**Review by arno-lunarg — APPROVED** [review]

**Review by jeremyg-lunarg — COMMENTED** [review]
LGTM. Should we at some point consider moving this to known_good.json?

**Comment by ncesario-lunarg** [comment]
> LGTM. Should we at some point consider moving this to known_good.json?

I'm guessing the rationale was that, "it's just 2 files, so might as well include it," but I do think it would be a bit clearer (and perhaps a bit easier) to have this be part of known_good.json.

**Comment by juan-lunarg** [comment]
> I'm guessing the rationale was that, "it's just 2 files, so might as well include it," but I do think it would be a bit clearer (and perhaps a bit easier) to have this be part of known_good.json.

I had 2 problems with having xxhash in known_good.json 

xxhash has CMake support, but in a subdirectory named `cmake_unofficial`
Also the xxhash files get installed as part of VVL for some reason, I'm not sure I understand.

**Pull request merged**
