### PR TITLE
Implement VUID 00683, mapping memory from multi-instance heap

### LINKED ISSUE #294: No error reported when attempting to map multi-instance mem allocation to process space
Consider the following use case:

1. vkAllocateMemory() is called with device mask set to include more than one device and with *flags* set to VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT. This makes the allocation multi-instance., even if the memory comes from host-visible heap.
2. vkMapMemory() is called against the memory block.

According to one of the VUs specified for vkMapMemory, *memory* must not have been allocated with multiple instances. However, no error is reported by the validation layers.

### PR DESCRIPTION
**Pull request by mark-lunarg**
Added state_tracker flag for multi-instance, validation check, and test.  Passes internal CI.

Fixes #294.

### CODE REVIEW

**Comment by null77** [comment]
Hey @mark-lunarg - we ran into a break in the ANGLE roll because of this CL. Can you help us diagnose if the bug is in the VVL or in the VulkanMemoryAllocator project from AMD? See failing build here:

https://ci.chromium.org/p/chromium/builders/try/win-angle-deqp-rel-32/7554?

Error:

DebugUtilsMessenger(332): [ VUID-vkMapMemory-memory-00683 ] Validation Error: [ VUID-vkMapMemory-memory-00683 ] Object 0: handle = 0x345107000000021b, type = VK_OBJECT_TYPE_UNKNOWN; | MessageID = 0xc05b3a9d | Memory (VkNonDispatchableHandle 0x345107000000021b[]) must not have been allocated with multiple instances -- either by supplying a deviceMask with more than one bit set, or by allocation from a heap with the MULTI_INSTANCE heap flag set. The Vulkan spec states: memory must not have been allocated with multiple instances (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkMapMemory-memory-00683)

Code in the VMA:

https://chromium.googlesource.com/external/github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator.git/+/6c656df63da5995a932aafd45b32af1974e497d9/src/vk_mem_alloc.h#16096

I couldn't see in the Vulkan spec exactly where this VU was coming from so it's hard to know if this is a bug. The VMA doesn't seem to intentionally pick this memory heap and it does not set a device mask or anything like that. Please advise.

**Comment by mark-lunarg** [comment]
The spec states that it is invalid to map a memory allocation from a heap with the `VK_MEMORY_HEAP_MULTI_INSTANCE_BIT   `bit set.  

> If VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT is not set, the number of instances allocated depends on whether VK_MEMORY_HEAP_MULTI_INSTANCE_BIT is set in the memory heap. If VK_MEMORY_HEAP_MULTI_INSTANCE_BIT is set, then memory is allocated for every physical device in the logical device (as if deviceMask has bits set for all device indices). If VK_MEMORY_HEAP_MULTI_INSTANCE_BIT is not set, then a single instance of memory is allocated (as if deviceMask is set to one).

Might you have access to the `PhysicalDeviceMemoryProperties `and the heap flags, or better yet, to the heap flags for the heap that VMA is allocating from?  We had an extremely difficult time finding a platform to exercise this check, so it is certainly suspect.

**Comment by null77** [comment]
@mark-lunarg do you have access to a Widows computer with an AMD GPU? I don't have one right now but I could get one if necessary. If you do, reproduction steps are:

1. follow instructions to build angle at https://chromium.googlesource.com/angle/angle/+/master/doc/DevSetup.md
2. use Gerrit cherry-pick to patch in this CL: https://chromium-review.googlesource.com/c/angle/angle/+/2336516
3. run gclient sync and rebuild
4. run `angle_deqp_gles2_tests --use-angle=vulkan --gtest_filter=dEQP.GLES2/functional_buffer_write_*`

**Comment by mark-lunarg** [comment]
@null77, our hunch is that the first AMD heap has the `VK_MEMORY_HEAP_MULTI_INSTANCE_BIT `set, and VMA doesn't make any distinction.  @Tony-LunarG has access to a working AMD/Windows platform and will attempt to verify this before the end of the week, and if it turns out to be the case will also look for a way to get VMA to return a non-multiinstance heap.

**Comment by null77** [comment]
That for the follow up. Will stay tuned.

**Comment by Tony-LunarG** [comment]
The check for 00683 was considering any allocation from a multi instance heap as a multi instance allocation, regardless of whether it actually specified more than one device.
Fix in #2097

**Pull request merged**
