### PR TITLE
scripts: Add extension VU coverage report

### PR DESCRIPTION
**Pull request by mikes-lunarg**
Add option -extension_coverage to generate a csv report with VUID counts broken down by extension. If a single VUID interacts with multiple extensions, it will be added to the counts for each one.

### CODE REVIEW

**Comment by mikes-lunarg** [comment]
@jeremyg-lunarg This generates the coverage report you asked about

**Review by ncesario-lunarg — APPROVED** [review]
Cool!

**Comment by jeremyg-lunarg** [comment]
works great!

**Comment by mikes-lunarg** [comment]
Once I looked at the diff again I couldn't resist fixing that awful argument parser

**Review by spencer-lunarg — APPROVED** [review]

**Comment by ncesario-lunarg** [comment]
> Once I looked at the diff again I couldn't resist fixing that awful argument parser

I was going to make a comment, but resisted the temptation 😆

**Pull request merged**
