### PR TITLE
layers: Check pipeline state for 06053 and 06054

### PR DESCRIPTION
**Pull request by zzoon**
The spec says:

```
VUID-VkGraphicsPipelineCreateInfo-renderPass-06053
If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment shader state and fragment output interface state, and either of VkPipelineRenderingCreateInfo::depthAttachmentFormat or VkPipelineRenderingCreateInfo::stencilAttachmentFormat are not VK_FORMAT_UNDEFINED, pDepthStencilState must be....
```
```
VUID-VkGraphicsPipelineCreateInfo-renderPass-06054
If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment output interface state, and VkPipelineRenderingCreateInfo::colorAttachmentCount is not equal to 0, pColorBlendState must be .....
```

### CODE REVIEW

**Comment by spencer-lunarg** [comment]
This is related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3805

**Review by ncesario-lunarg — COMMENTED** [review]
This LGTM, but is it possible to get a test for the original issue? This is probably relying on something like `rasterizerDiscardEnabled == VK_TRUE => !fragment_output_state` (or something along those lines), but I'm not sure that's true.

**Comment by zzoon** [comment]
> This LGTM, but is it possible to get a test for the original issue? This is probably relying on something like `rasterizerDiscardEnabled == VK_TRUE => !fragment_output_state` (or something along those lines), but I'm not sure that's true.

This issue can be found with both gpl and dynamic rendering enabled. If I understand correctly, a new test for this can be in `VkGraphicsLibraryLayerTest`.

**Comment by ncesario-lunarg** [comment]
Thanks for the test @zzoon! I went ahead and pushed a change to your branch that split the test code and layer code into separate commits and ran clang-format (which is required).

**Review by ncesario-lunarg — APPROVED** [review]

**Pull request merged**
