### PR TITLE
Revert "cmake: Add utility libraries repository dependence"

### PR DESCRIPTION
**Pull request by christophe-lunarg**
This reverts commit 192388c193d9a3bcebb9d38824f99c4df05e36bd.

### CODE REVIEW

**Review by ziga-lunarg — APPROVED** [review]

**Review by Tony-LunarG — APPROVED** [review]
LGTM as soon as CI passes

**Comment by juan-lunarg** [comment]
I'm out of the loop. Why was this reverted?

**Comment by ziga-lunarg** [comment]
> I'm out of the loop. Why was this reverted?

VulkanTools and VulkanProfiles had issues updating headers due to this commit

**Comment by juan-lunarg** [comment]
> VulkanTools and VulkanProfiles had issues updating headers due to this commit

Talking to Christophe I think I understand the situation now. I'll see if I can create a local repro so I can fix the issue.

**Pull request merged**
