### PR TITLE
layers: Report valid spec links on error

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
The CI failure is just for copyright dates.

I tried the first changed link in `vk_validation_error_messages`  ([https://github.com/KhronosGroup/Vulkan-Docs/tree/master/chapters#VUID-VkBindBufferMemoryInfo-buffer-01604](https://github.com/KhronosGroup/Vulkan-Docs/tree/master/chapters#VUID-VkBindBufferMemoryInfo-buffer-01604)) and it took me to the chapters directory of the repo and left me there -- does it need a specific filename for the reference to work maybe?

**Comment by mark-lunarg** [comment]
Also, any way to roll up (or avoid the need for) #1462 (or obviate the need for) into this change?

**Comment by krOoze** [comment]
@mark-lunarg Right, I left it in the code comments. Some VUIDs simply do not exist in neither version of the spec. `VUID-VkBindBufferMemoryInfo-buffer-01604`s pattern is `(VK_VERSION_1_1,VK_KHR_bind_memory2)+(VK_NV_dedicated_allocation)+!(VK_VERSION_1_1,VK_KHR_dedicated_allocation)`. The last term says it must not be in 1.1 nor KHR, but the first pattern says it is only in 1.1 or KHR. So it is nowhere.

I cannot solve #1462 here. I do not have the VUID=>chapter map. That would have to be generated from spec.

**Comment by mark-lunarg** [comment]
Running through CI.

**Pull request merged**
