### PR TITLE
Fix validation layer tests running on RADV

### PR DESCRIPTION
**Pull request by Tony-LunarG**
Fix 6 tests and skip 6 tests running on RADV

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
Nice! A _lot_ more tests passing on my local AMD system now.

A couple observations from my local run:

I think this crash:
```
[ RUN      ] VkLayerTest.DrawWithPipelineIncompatibleWithRenderPassMultiview
vk_layer_validation_tests: ../src/amd/vulkan/radv_pass.c:382: VkResult radv_CreateRenderPass2(VkDevice, const VkRenderPassCreateInfo2 *, const VkAllocationCall
backs *, VkRenderPass *): Assertion `pCreateInfo->sType == VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2' failed.
Aborted (core dumped)
```

Can be trivially fixed with:
```diff
diff --git a/tests/vklayertests_descriptor_renderpass_framebuffer.cpp b/tests/vklayertests_descriptor_renderpass_framebuffer.cpp
index 80fccce4..db559705 100644
--- a/tests/vklayertests_descriptor_renderpass_framebuffer.cpp
+++ b/tests/vklayertests_descriptor_renderpass_framebuffer.cpp
@@ -6557,8 +6557,7 @@ TEST_F(VkLayerTest, DrawWithPipelineIncompatibleWithRenderPassMultiview) {
     subpass2.colorAttachmentCount = 1;
     subpass2.pColorAttachments = &color_att2;
 
-    VkRenderPassCreateInfo2 rpci2 = {};
-    rpci2.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
+    auto rpci2 = LvlInitStruct<VkRenderPassCreateInfo2>();
     rpci2.attachmentCount = 1;
     rpci2.pAttachments = &attach2;
     rpci2.subpassCount = 1;
```

No idea how to get around this one, but my guess is we just need to disable the test for now:
<details>
<summary>VkLayerTest.InvailStorageAtomicOperation (NIR validation failure)</summary>
<pre>
[ RUN      ] VkLayerTest.InvailStorageAtomicOperation
NIR validation failed after spirv_to_nir
6 errors:
shader: MESA_SHADER_FRAGMENT
inputs: 0
outputs: 0
uniforms: 0
shared: 0
decl_var uniform INTERP_MODE_NONE restrict r8g8b8a8_unorm image2D si0 (~0, 0, 3)
decl_var uniform INTERP_MODE_NONE restrict r8g8b8a8_unorm image2D[2] si1 (~0, 0, 2)
decl_var uniform INTERP_MODE_NONE restrict r8_unorm imageBuffer stb2 (~0, 0, 1)
decl_var uniform INTERP_MODE_NONE restrict r8_unorm imageBuffer[2] stb3 (~0, 0, 0)
decl_function main (0 params)

impl main {
        block block_0:
        /* preds: */
        vec1 32 ssa_60 = load_const (0x3f800000 /* 1.000000 */)
        vec1 32 ssa_58 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_56 = undefined
        vec1 32 ssa_55 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_50 = load_const (0x3f800000 /* 1.000000 */)
        vec1 32 ssa_48 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_46 = undefined
        vec1 32 ssa_45 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_40 = load_const (0x3f800000 /* 1.000000 */)
        vec1 32 ssa_38 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_36 = undefined
        vec1 32 ssa_35 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_32 = load_const (0x3f800000 /* 1.000000 */)
        vec1 32 ssa_30 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_26 = undefined
        vec2 32 ssa_25 = load_const (0x00000000 /* 0.000000 */, 0x00000000 /* 0.000000 */)
        vec1 32 ssa_20 = load_const (0x3f800000 /* 1.000000 */)
        vec1 32 ssa_18 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_14 = undefined
        vec2 32 ssa_13 = load_const (0x00000000 /* 0.000000 */, 0x00000000 /* 0.000000 */)
        vec1 32 ssa_8 = load_const (0x3f800000 /* 1.000000 */)
        vec1 32 ssa_6 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_2 = undefined
        vec2 32 ssa_1 = load_const (0x00000000 /* 0.000000 */, 0x00000000 /* 0.000000 */)
        vec1 32 ssa_0 = deref_var &si0 (uniform image2D) 
        vec1 32 ssa_3 = mov ssa_1.x
        vec1 32 ssa_4 = mov ssa_1.y
        vec4 32 ssa_5 = vec4 ssa_3, ssa_4, ssa_2, ssa_2
        vec1 32 ssa_9 = intrinsic image_deref_atomic_exchange (ssa_0, ssa_5, ssa_6, ssa_8) (1) /* access=1 */
error: format == PIPE_FORMAT_R32_UINT || format == PIPE_FORMAT_R32_SINT || format == PIPE_FORMAT_R32_FLOAT || format == PIPE_FORMAT_R64_UINT || format == PIPE_
FORMAT_R64_SINT (../src/compiler/nir/nir_validate.c:743)

        vec1 32 ssa_10 = deref_var &si1 (uniform image2D[2]) 
        vec1 32 ssa_11 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_12 = deref_array &(*ssa_10)[0] (uniform image2D) /* &si1[0] */
        vec1 32 ssa_15 = mov ssa_13.x
        vec1 32 ssa_16 = mov ssa_13.y
        vec4 32 ssa_17 = vec4 ssa_15, ssa_16, ssa_14, ssa_14
        vec1 32 ssa_21 = intrinsic image_deref_atomic_exchange (ssa_12, ssa_17, ssa_18, ssa_20) (1) /* access=1 */
error: format == PIPE_FORMAT_R32_UINT || format == PIPE_FORMAT_R32_SINT || format == PIPE_FORMAT_R32_FLOAT || format == PIPE_FORMAT_R64_UINT || format == PIPE_
FORMAT_R64_SINT (../src/compiler/nir/nir_validate.c:743)

        vec1 32 ssa_22 = deref_var &si1 (uniform image2D[2]) 
        vec1 32 ssa_23 = load_const (0x00000001 /* 0.000000 */)
        vec1 32 ssa_24 = deref_array &(*ssa_22)[1] (uniform image2D) /* &si1[1] */
        vec1 32 ssa_27 = mov ssa_25.x
        vec1 32 ssa_28 = mov ssa_25.y
        vec4 32 ssa_29 = vec4 ssa_27, ssa_28, ssa_26, ssa_26
        vec1 32 ssa_33 = intrinsic image_deref_atomic_exchange (ssa_24, ssa_29, ssa_30, ssa_32) (1) /* access=1 */
error: format == PIPE_FORMAT_R32_UINT || format == PIPE_FORMAT_R32_SINT || format == PIPE_FORMAT_R32_FLOAT || format == PIPE_FORMAT_R64_UINT || format == PIPE_
FORMAT_R64_SINT (../src/compiler/nir/nir_validate.c:743)

        vec1 32 ssa_34 = deref_var &stb2 (uniform imageBuffer) 
        vec4 32 ssa_37 = vec4 ssa_35, ssa_36, ssa_36, ssa_36
        vec1 32 ssa_41 = intrinsic image_deref_atomic_exchange (ssa_34, ssa_37, ssa_38, ssa_40) (1) /* access=1 */
error: nir_dest_bit_size(instr->dest) == util_format_get_blocksizebits(format) (../src/compiler/nir/nir_validate.c:745)

        vec1 32 ssa_42 = deref_var &stb3 (uniform imageBuffer[2]) 
        vec1 32 ssa_43 = load_const (0x00000000 /* 0.000000 */)
        vec1 32 ssa_44 = deref_array &(*ssa_42)[0] (uniform imageBuffer) /* &stb3[0] */
        vec4 32 ssa_47 = vec4 ssa_45, ssa_46, ssa_46, ssa_46
        vec1 32 ssa_51 = intrinsic image_deref_atomic_exchange (ssa_44, ssa_47, ssa_48, ssa_50) (1) /* access=1 */
error: nir_dest_bit_size(instr->dest) == util_format_get_blocksizebits(format) (../src/compiler/nir/nir_validate.c:745)

        vec1 32 ssa_52 = deref_var &stb3 (uniform imageBuffer[2]) 
        vec1 32 ssa_53 = load_const (0x00000001 /* 0.000000 */)
        vec1 32 ssa_54 = deref_array &(*ssa_52)[1] (uniform imageBuffer) /* &stb3[1] */
        vec4 32 ssa_57 = vec4 ssa_55, ssa_56, ssa_56, ssa_56
        vec1 32 ssa_61 = intrinsic image_deref_atomic_exchange (ssa_54, ssa_57, ssa_58, ssa_60) (1) /* access=1 */
error: nir_dest_bit_size(instr->dest) == util_format_get_blocksizebits(format) (../src/compiler/nir/nir_validate.c:745)

        return
        /* succs: block_1 */
        block block_1:
}
</pre>
</details>

**Comment by Tony-LunarG** [comment]
After a quick look, I think both of those tests have real errors (more than just rcpi2 init) that should be fixed.  I'll take a closer look.

**Comment by Tony-LunarG** [comment]
@ncesario-lunarg want to take another try at it?

**Comment by ncesario-lunarg** [comment]
Getting closer :)

Now I get the following:
```
[ RUN      ] VkSyncValTest.SyncRenderPassWithWrongDepthStencilInitialLayout
vk_layer_validation_tests: ../src/amd/vulkan/radv_cmd_buffer.c:3677: VkResult radv_cmd_state_setup_attachments(struct radv_cmd_buffer *, struct radv_render_pas
s *, const VkRenderPassBeginInfo *, const struct radv_extra_render_pass_begin_info *): Assertion `info->clearValueCount > i' failed.
```

If the whole test suite is running for you, I'd vote for merging these changes as is and I can look at the failures I'm seeing; they might be specific to my version of radv + HW.

**Comment by Tony-LunarG** [comment]
> Getting closer :)
> 
> Now I get the following:
> 
> ```
> [ RUN      ] VkSyncValTest.SyncRenderPassWithWrongDepthStencilInitialLayout
> vk_layer_validation_tests: ../src/amd/vulkan/radv_cmd_buffer.c:3677: VkResult radv_cmd_state_setup_attachments(struct radv_cmd_buffer *, struct radv_render_pas
> s *, const VkRenderPassBeginInfo *, const struct radv_extra_render_pass_begin_info *): Assertion `info->clearValueCount > i' failed.
> ```
> 
> If the whole test suite is running for you, I'd vote for merging these changes as is and I can look at the failures I'm seeing; they might be specific to my version of radv + HW.

Nah, if you made it to syncval we've got to be close.  I'll take a look.  Thanks.

**Comment by Tony-LunarG** [comment]
I've never seen anything that says you must have a clear value for every attachment (which is how I read that assert), but I added another to the RenderPassBeginInfo.  @ncesario-lunarg can you give it a try?

**Comment by ncesario-lunarg** [comment]
So close! There was one more test that hit that same assert. This fixed it for me:
```diff
diff --git a/tests/vksyncvaltests.cpp b/tests/vksyncvaltests.cpp
index 1b67cf98..3a18a8f9 100644
--- a/tests/vksyncvaltests.cpp
+++ b/tests/vksyncvaltests.cpp
@@ -2791,7 +2791,7 @@ TEST_F(VkSyncValTest, RenderPassAsyncHazard) {
 
     VkClearValue clear = {};
     clear.color = m_clear_color;
-    std::array<VkClearValue, 3> clear_values = {{clear, clear, clear}};
+    std::array<VkClearValue, 4> clear_values = {{clear, clear, clear, clear}};
 
     // run the renderpass with no dependencies
     {
```

Once I made that change, the only failure I'm seeing now is
```
[ RUN      ] VkGpuAssistedLayerTest.GpuValidationInlineUniformBlockAndMiscGpu
../tests/vkrenderframework.cpp:208: Failure
Failed
Expected to succeed but got error: VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT not functioning as expected
```

**Comment by Tony-LunarG** [comment]
@ncesario-lunarg one more try 🤞

**Comment by ncesario-lunarg** [comment]
It works :tada: !!

My driver info for reference:
```
Mesa 21.2.0-devel (git-a1c56b8091) (ACO)
```

**Pull request merged**
