### PR TITLE
Fix for Bugs in Index-Buffer Scanning Checks in Arm Best Practices

### PR DESCRIPTION
**Pull request by samwalls-arm**
I was trying to use best practices out in the wild when I discovered a segfault in `ValidateIndexBufferArm(...)`!

I've identified the issue, fixed it, and included changes to the tests to reflect the fix.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Running through CI!

**Comment by mark-lunarg** [comment]
@samwalls-arm, this crashes hard on Windows platforms (systems needed a reboot!) and Pixel3 Android:

Nvidia Windows:

> [ RUN      ] VkArmBestPracticesLayerTest.SparseIndexBufferTest
> ERROR: -------------------------------------------------------------
> ERROR: FAIL during test after 22.53 minutes (1351.61 seconds) with execute(C:\j\w8\64-bit\Debug\dbuild\tests\Debug\vk_layer_validation_tests.exe --gtest_catch_exceptions=0 --gtest_filter=-VkLayerTest.NonSemanticInfoEnabled) failed after 22.53 minutes (1351.60 seconds) with returncode=3 (0x3)
> INFO: Test run complete after 26.30 minutes (1577.80 seconds)

AMD Windows:

> [ RUN      ] VkArmBestPracticesLayerTest.SparseIndexBufferTest
> ERROR: -------------------------------------------------------------
> ERROR: FAIL during test after 15.82 minutes (949.26 seconds) with execute(C:\j\w8\64-bit\Debug\dbuild\tests\Debug\vk_layer_validation_tests.exe --gtest_catch_exceptions=0 --gtest_filter=-VkLayerTest.NonSemanticInfoEnabled) failed after 15.82 minutes (949.14 seconds) with returncode=3 (0x3)
> INFO: Test run complete after 25.14 minutes (1508.19 seconds)

Pixel3 Android Logcat:

```
07-30 17:55:49.864 11204 11229 I VulkanLayerValidationTests: [ RUN      ] VkArmBestPracticesLayerTest.SparseIndexBufferTest
07-30 17:55:49.880 11204 11229 I vulkan  : Loaded layer VK_LAYER_KHRONOS_validation
07-30 17:55:49.882 11204 11229 I Adreno  : QUALCOMM build          : 4a00b69, I4e7e888065
07-30 17:55:49.882 11204 11229 I Adreno  : Build Date              : 04/09/19
07-30 17:55:49.882 11204 11229 I Adreno  : Shader Compiler Version : EV031.26.06.00
07-30 17:55:49.882 11204 11229 I Adreno  : Local Branch            : mybranche95a5ea3-cf05-f19a-a0e7-5cb90179c3d8
07-30 17:55:49.882 11204 11229 I Adreno  : Remote Branch           : quic/gfx-adreno.lnx.1.0
07-30 17:55:49.882 11204 11229 I Adreno  : Remote Branch           : NONE
07-30 17:55:49.882 11204 11229 I Adreno  : Reconstruct Branch      : NOTHING
07-30 17:55:49.882 11204 11229 I Adreno  : Build Config            : S P 8.0.6 AArch64
--------- beginning of crash
07-30 17:55:49.946 11204 11229 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3f in tid 11229 (Thread-2), pid 11204 (ValidationTests)
07-30 17:55:49.992 11259 11259 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
07-30 17:55:49.993  1039  1039 I /system/bin/tombstoned: received crash request for pid 11229
07-30 17:55:49.994 11259 11259 I crash_dump64: performing dump of process 11204 (target tid = 11229)
07-30 17:55:50.001 11259 11259 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-30 17:55:50.001 11259 11259 F DEBUG   : Build fingerprint: 'google/blueline/blueline:10/QP1A.190711.020.C3/5869620:user/release-keys'
07-30 17:55:50.001 11259 11259 F DEBUG   : Revision: 'MP1.0'
07-30 17:55:50.001 11259 11259 F DEBUG   : ABI: 'arm64'
07-30 17:55:50.002 11259 11259 F DEBUG   : Timestamp: 2020-07-30 17:55:49-0600
07-30 17:55:50.002 11259 11259 F DEBUG   : pid: 11204, tid: 11229, name: Thread-2  >>> com.example.VulkanLayerValidationTests <<<
07-30 17:55:50.002 11259 11259 F DEBUG   : uid: 11217
07-30 17:55:50.002 11259 11259 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3f
07-30 17:55:50.002 11259 11259 F DEBUG   : Cause: null pointer dereference
07-30 17:55:50.002 11259 11259 F DEBUG   :     x0  ffffffffffffffff  x1  0000000000000000  x2  0000007ac2652500  x3  0000000000000020
07-30 17:55:50.002 11259 11259 F DEBUG   :     x4  0000007ac2652240  x5  00000000000015a0  x6  0000007ac26535a0  x7  0000000000001500
07-30 17:55:50.002 11259 11259 F DEBUG   :     x8  0000007b1ef676c8  x9  0000000000000001  x10 0000007b1f50f060  x11 0000007ac0000000
07-30 17:55:50.002 11259 11259 F DEBUG   :     x12 0000000000002000  x13 00000000866032f8  x14 0000007ac26529a0  x15 0000007ac2652780
07-30 17:55:50.002 11259 11259 F DEBUG   :     x16 0000007b12294378  x17 0000007baeb09920  x18 0000000000000004  x19 0000007b1eeee680
07-30 17:55:50.002 11259 11259 F DEBUG   :     x20 0000007ac2652000  x21 0000007b1efc6d40  x22 0000007b1eeee680  x23 0000007b1ef675e0
07-30 17:55:50.002 11259 11259 F DEBUG   :     x24 0000007b1f50f020  x25 0000007b1efc6a00  x26 0000007b1ef675e0  x27 0000000000000000
07-30 17:55:50.002 11259 11259 F DEBUG   :     x28 0000007b1ee170f0  x29 0000007b1f50e7a0
07-30 17:55:50.002 11259 11259 F DEBUG   :     sp  0000007b1f50e750  lr  0000007b11f24b34  pc  0000007b12076fe0
07-30 17:55:50.037 11259 11259 F DEBUG   : 
07-30 17:55:50.037 11259 11259 F DEBUG   : backtrace:
07-30 17:55:50.037 11259 11259 F DEBUG   :       #00 pc 0000000000c76fe0  /vendor/lib64/libllvm-glnext.so (TPoolAllocator::pop()) (BuildId: 270c9831374d0b52e3e9039997d89131)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #01 pc 0000000000b24b30  /vendor/lib64/libllvm-glnext.so (CompilerContext::cleanup()+104) (BuildId: 270c9831374d0b52e3e9039997d89131)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #02 pc 0000000000c1bcf4  /vendor/lib64/libllvm-glnext.so (QGLCDestroyContext(void*)+12) (BuildId: 270c9831374d0b52e3e9039997d89131)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #03 pc 00000000001b9348  /vendor/lib64/hw/vulkan.sdm845.so (BuildId: 203351df0394c33cc996eba69162878c)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #04 pc 00000000001aaa80  /vendor/lib64/hw/vulkan.sdm845.so (BuildId: 203351df0394c33cc996eba69162878c)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #05 pc 00000000001ada5c  /vendor/lib64/hw/vulkan.sdm845.so (BuildId: 203351df0394c33cc996eba69162878c)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #06 pc 0000000000163764  /vendor/lib64/hw/vulkan.sdm845.so (qglinternal::vkDestroyInstance(VkInstance_T*, VkAllocationCallbacks const*)+60) (BuildId: 203351df0394c33cc996eba69162878c)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #07 pc 0000000000019e54  /system/lib64/libvulkan.so (vulkan::driver::DestroyInstance(VkInstance_T*, VkAllocationCallbacks const*)+44) (BuildId: e42b2cfc977d1600a2bc2e39acea3eb3)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #08 pc 00000000009dead8  /data/app/com.example.VulkanLayerValidationTests-TJ0PLrK0-2GGj6HZaJZ2Eg==/lib/arm64/libVkLayer_khronos_validation.so (BuildId: 4ed41dd63ee3d6dda18e487d3977c976ea553ea5)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #09 pc 0000000000011c30  /system/lib64/libvulkan.so (vulkan::api::DestroyInstance(VkInstance_T*, VkAllocationCallbacks const*)+156) (BuildId: e42b2cfc977d1600a2bc2e39acea3eb3)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #10 pc 0000000000360364  /data/app/com.example.VulkanLayerValidationTests-TJ0PLrK0-2GGj6HZaJZ2Eg==/lib/arm64/libVulkanLayerValidationTests.so (BuildId: 424a49657f3f53373f42b1bcb9ab34195b685006)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #11 pc 00000000003600ac  /data/app/com.example.VulkanLayerValidationTests-TJ0PLrK0-2GGj6HZaJZ2Eg==/lib/arm64/libVulkanLayerValidationTests.so (BuildId: 424a49657f3f53373f42b1bcb9ab34195b685006)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #12 pc 0000000000318390  /data/app/com.example.VulkanLayerValidationTests-TJ0PLrK0-2GGj6HZaJZ2Eg==/lib/arm64/libVulkanLayerValidationTests.so (BuildId: 424a49657f3f53373f42b1bcb9ab34195b685006)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #13 pc 00000000003cc500  /data/app/com.example.VulkanLayerValidationTests-TJ0PLrK0-2GGj6HZaJZ2Eg==/lib/arm64/libVulkanLayerValidationTests.so (testing::TestInfo::Run()+476) (BuildId: 424a49657f3f53373f42b1bcb9ab34195b685006)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #14 pc 00000000003cca50  /data/app/com.example.VulkanLayerValidationTests-TJ0PLrK0-2GGj6HZaJZ2Eg==/lib/arm64/libVulkanLayerValidationTests.so (testing::TestCase::Run()+248) (BuildId: 424a49657f3f53373f42b1bcb9ab34195b685006)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #15 pc 00000000003d57a8  /data/app/com.example.VulkanLayerValidationTests-TJ0PLrK0-2GGj6HZaJZ2Eg==/lib/arm64/libVulkanLayerValidationTests.so (testing::internal::UnitTestImpl::RunAllTests()+1080) (BuildId: 424a49657f3f53373f42b1bcb9ab34195b685006)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #16 pc 00000000003d533c  /data/app/com.example.VulkanLayerValidationTests-TJ0PLrK0-2GGj6HZaJZ2Eg==/lib/arm64/libVulkanLayerValidationTests.so (testing::UnitTest::Run()+164) (BuildId: 424a49657f3f53373f42b1bcb9ab34195b685006)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #17 pc 00000000001e4fec  /data/app/com.example.VulkanLayerValidationTests-TJ0PLrK0-2GGj6HZaJZ2Eg==/lib/arm64/libVulkanLayerValidationTests.so (BuildId: 424a49657f3f53373f42b1bcb9ab34195b685006)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #18 pc 00000000003b9260  /data/app/com.example.VulkanLayerValidationTests-TJ0PLrK0-2GGj6HZaJZ2Eg==/lib/arm64/libVulkanLayerValidationTests.so (BuildId: 424a49657f3f53373f42b1bcb9ab34195b685006)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #19 pc 00000000000e1100  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 676a709a0ee633ec9cf6ab05ec6410ae)
07-30 17:55:50.037 11259 11259 F DEBUG   :       #20 pc 0000000000083ab0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 676a709a0ee633ec9cf6ab05ec6410ae)
07-30 17:55:50.258  1039  1039 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_03
```

**Comment by samwalls-arm** [comment]
Hey @mark-lunarg, I think the changes I added should fix things on windows. I'm not sure if the same can be said for the Pixel 3, looks like the error is coming from a teardown step? Might be worth trying a run through the CI again - perhaps the null pointer deref in the teardown step was caused by the same underlying issue as on windows (index out of bounds).

**Comment by mark-lunarg** [comment]
Running through CI!

**Comment by samwalls-arm** [comment]
Hey @mark-lunarg, any update on this?

**Comment by mark-lunarg** [comment]
Sorry, we had some CI trouble last week and the results were indeterminate.  Resubmitted!

**Comment by mark-lunarg** [comment]
Looks great, sorry for the delay!  Rebased and pushed to Master.

**Comment by samwalls-arm** [comment]
Great, thanks!

**Pull request closed without merging**
