### PR TITLE
WIP scripts: Remove hardcode API string in extension helper

### PR DESCRIPTION
**Pull request by spencer-lunarg**
to help reduce the workaround needed for the code in #6150 

Will also make a Vulkan 1.4 much easier as it will be generated automatically for us (which is what we want!)

### CODE REVIEW

**Review by juan-lunarg — APPROVED** [review]

**Comment by spencer-lunarg** [comment]
cc @aqnuep

**Comment by aqnuep** [comment]
PR #6150 provides a better solution for this already. Also, if really needed, we can further refine that instead to generate the variable names for `vk_feature_*` and `v_*_promoted` based on the version string instead. But this PR is just a partial solution for the overall problem with still many of the things left hard-coded.

**Comment by spencer-lunarg** [comment]
> PR #6150 provides a better solution for this already.

I think hard-coding version like we were was bad, we should just be using the new `self.vk.versions` to make Vulkan 1.4 intergration for use easier... this also should remove the need for you to need logic to decide which hardcoded array  to use

**Comment by aqnuep** [comment]
> I think hard-coding version like we were was bad, we should just be using the new self.vk.versions to make Vulkan 1.4 intergration for use easier... this also should remove the need for you to need logic to decide which hardcoded array to use

Not quite, as unlike in Vulkan, where versions are strictly linear, with SC we have cross-dependencies, like Vulkan SC 1.0 requiring Vulkan 1.2 with modifications. The dependency possibilities enabled by `vk.xml` for versions is almost like that for extensions. Any version can depend on any other version, just like with extensions. Ignoring that would only cause problems down the road.

**Comment by spencer-lunarg** [comment]
this logic is rarely ever touched, would be more churn to push this forward then just leave it

**Pull request closed without merging**
