### PR TITLE
Consolidate commit msg formatting with code formatting and make it a must-pass CI test

### PR DESCRIPTION
**Pull request by mark-lunarg**
This PR will move the commit message format checking script into the main format checking script, making it a must-pass CI test.  
Additionally, the script can now be run from the repo root in a terminal command line _outside of Travis_, allowing a developer to know if the PR is correctly formatted before sending it through CI.

Sample output showing clang-format errors and half-a-dozen bad-commit errors:

```
Checking PR source code for clang-format errors:

Found formatting errors!
--- layers/buffer_validation.cpp        (before formatting)
+++ layers/buffer_validation.cpp        (after formatting)
@@ -359,27 +359,35 @@
 }

 bool IMAGE_VIEW_STATE::OverlapSubresource(const IMAGE_VIEW_STATE &compare_view) const {
-    if (image_view == compare_view.image_view) { return true; }
-    if (image_state->image != compare_view.image_state->image) { return false; } if (normalized_subresource_range.aspectMask != compare_view.normalized_subresource_range.aspectMask) { return false;
+    if (image_view == compare_view.image_view) {
+        return true;
+    }
+    if (image_state->image != compare_view.image_state->image) {
+        return false;
+    }
+    if (normalized_subresource_range.aspectMask != compare_view.normalized_subresource_range.aspectMask) {
+        return false;
     }

     // compare if overlap mip level
     if ((normalized_subresource_range.baseMipLevel < compare_view.normalized_subresource_range.baseMipLevel) &&
         ((normalized_subresource_range.baseMipLevel + normalized_subresource_range.levelCount) <=
-         compare_view.normalized_subresource_range.baseMipLevel)) { return false;
+         compare_view.normalized_subresource_range.baseMipLevel)) {
+        return false;
     }

     if ((normalized_subresource_range.baseMipLevel > compare_view.normalized_subresource_range.baseMipLevel) &&
         (normalized_subresource_range.baseMipLevel >=
          (compare_view.normalized_subresource_range.baseMipLevel + compare_view.normalized_subresource_range.levelCount))) {
-        return false; }
+        return false;
+    }

     // compare if overlap array layer
     if ((normalized_subresource_range.baseArrayLayer < compare_view.normalized_subresource_range.baseArrayLayer) &&
         ((normalized_subresource_range.baseArrayLayer + normalized_subresource_range.layerCount) <=
          compare_view.normalized_subresource_range.baseArrayLayer)) {
         return false;
-               }
+    }

     if ((normalized_subresource_range.baseArrayLayer > compare_view.normalized_subresource_range.baseArrayLayer) &&
         (normalized_subresource_range.baseArrayLayer >=

Checking PR source files for correct copyright information:

cat: scripts/check_commit_message_format.sh: No such file or directory

Checking PR commit messages for consistency issues:

The following subject line must start with a single word specifying the functional area of the change, followed by a colon and space.
e.g., 'layers: Subject line here' or 'corechecks: Fix off-by-one error in ValidateFences'
Other common module names include layers, build, cmake, tests, docs, scirpts, stateless, gpu, syncval, practices, etc.
     'tobin:Wish you were here'

The first word of the subject line after the ':' character must be capitalized.
     'tobin:Wish you were here'

The following subject line exceeds 64 characters in length.
     'bob: So far this is all looking good, but how long must this error'

The first word of the subject line after the ':' character must be capitalized.
     'layers: dangit forgot the big D'

The following subject line must start with a single word specifying the functional area of the change, followed by a colon and space.
e.g., 'layers: Subject line here' or 'corechecks: Fix off-by-one error in ValidateFences'
Other common module names include layers, build, cmake, tests, docs, scirpts, stateless, gpu, syncval, practices, etc.
     'layers this one has no colon'

The first word of the subject line after the ':' character must be capitalized.
     'layers this one has no colon'

The first word of the subject line must be lower case.
     'Layers: First error'


Commit Message Format Requirements:
-----------------------------------
o  Subject lines must be <= 64 characters in length
o  Subject lines must start with a module keyword which is lower-case and followed by a colon and a space
o  The first word following the colon must be capitalized and the subject line must not end in a '.'
o  The subject line must be followed by a blank line
o  The commit description must be <= 72 characters in width

Examples:
---------
     build: Fix Vulkan header/registry detection for SDK
     tests: Fix QueryPerformanceIncompletePasses stride usage
     corechecks: Fix validation of VU 03227
     state_tracker: Remove 'using std::*' statements
     stateless: Account for DynStateWithCount for multiViewport

Refer to this document for additional detail:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/CONTRIBUTING.md#coding-conventions-and-formatting
```

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
Tried it out it worked great and seems really useful; LGTM!

One general comment is that the `check_code_format.sh` "script" seems like it wants to "graduate" to something like python, but that's just my own personal preference/bias :)

**Comment by mark-lunarg** [comment]
@ncesario-lunarg, I was thinking the same thing!  I guess the only reason I didn't go down that path was that WSL works so well, but I may do the conversion, not sure yet. Anybody else?

**Comment by mikes-lunarg** [comment]
+1 @ncesario-lunarg .sh made sense when it was simple and only for Travis (Linux). If we are going to encourage developers to run this thing on their local machines then python would be more consistent with our other scripts. I can tell you which one I would rather maintain :wink:

**Comment by mark-lunarg** [comment]
Closing in favor of a python-based version.

**Pull request closed without merging**
