### PR TITLE
Update appveyor/travis for INSTALL_DIR builds

### PR DESCRIPTION
**Pull request by mark-lunarg**
Removed submodule cruft, removed *_REPO_ROOT references, changed to new install targets for loader, headers, and glslang.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Removed the 'recurse-submodules' parameter for the Vulkan-Tools build now that it is unnecessary.

**Comment by karl-lunarg** [comment]
I don't know if this should be another PR or not, but:

The test step is still using components from the Vulkan-Tools build directory instead of its install dir.

To fix this:

* Vulkan-Tools needs to be built with the install target and INSTALL_ICD=ON
* Need to change the VK_ICD_FILENAMES to point at the icd json in the V-Tools' install dir
* Since the library_path in the icd json is just a filename, you'll need to add V-Tools' lib dir to LD_LIBRARY_PATH

If you'd rather not do this now, create an issue and assign to me, or add it to our internal tracker.

**Comment by karl-lunarg** [comment]
To fix the Travis failure, you need to add the headers and loader INSTALL_DIRS to the cmake generation step for Vulkan-Tools.

**Comment by mark-lunarg** [comment]
Added the CI update needs to the internal tracker.

**Pull request merged**
