### PR TITLE
VK_KHR_imageless_framebuffer support

### PR DESCRIPTION
**Pull request by Tobski**

### CODE REVIEW

**Comment by Tobski** [comment]
NB: this needs master to be updated to the latest header before it will build (and then this to be rebased)

**Comment by mark-lunarg** [comment]
@shannon-lunarg will be handling the appropriate header update.

**Comment by shannon-lunarg** [comment]
@Tobski The 114 VVL known-good update just went live! So you should be unblocked and able to rebase.

**Comment by Tobski** [comment]
I've rebased, but haven't tested - figure the CI can probably get up and running before I can to be honest...

**Comment by Tobski** [comment]
Oof and just realised I left test code in there, will be fixing that ASAP...

**Comment by Tobski** [comment]
Ok, fixed some changes that didn't work against the new ToT, should be good to build now. I'll check back later...

**Comment by Tobski** [comment]
The Appveyor build has passed but the travis build is still waiting to be queued... @mark-lunarg any idea what's happening?

**Comment by mark-lunarg** [comment]
Travis has been lagging significantly over the last month or two.  Looks like it's just an unused variable anyhow...

**Comment by Tobski** [comment]
@mark-lunarg ok so I fixed what I could, but _testing_ is still going to fail - there's an implicit VU I left in the spec by mistake which checks that the pAttachments parameter of VkFramebufferCreateInfo is not NULL, though this extension should allow that. Subsequently, all the tests are going to fail.

I'll have to fix the spec to make it work, but the question is what to do about it in the meantime? If we want a quick turnaround, I could, for example, just add an array of image views into that parameter in the tests for the timebeing, which would get past that check - but that still means developers are going to walk into it.

Is there a sane way to disable an implicit VU, at least until we get it out of the spec?

**Comment by mark-lunarg** [comment]
Ugh.  I think the best option here is probably to remove the implicit VUID from the validusage.json file in Vulkan-Headers, which would then mean updating the known-good in VVL to pick up that change (shouldn't affect any of the other repos, so they shouldn't need to be updated).  I think code-freeze for the SDK might be Monday (?), so I'll loop in @shannon-lunarg, @mikes-lunarg, and @KarenGhavam-lunarG, and they can decide where to go from here.

**Comment by mikes-lunarg** [comment]
Removing the VUID from validusage.json won't be enough to squash the check, it will still come out with an undefined error message.  You would have to fix the `optional` attribute in vk.xml (ie the real fix) or kludge the generator like [this](https://gist.github.com/mikes-lunarg/60c605b0cbb5d95e6e325c16ba662e65)

The CI failures are more than an unexpected VUID.  I'm seeing segfaults from `CoreChecks::PostCallRecordCreateFramebuffer` and `CoreChecks::VerifyFramebufferAndRenderPassLayouts` when they try to access a null VkFramebufferCreateInfo.pAttachments array.

There's also a CI failure in VkLayerTest.ImagelessFramebufferDepthStencilResolveAttachmentTests because of our non-conformant mock driver.  I put up a fix here: https://github.com/KhronosGroup/Vulkan-Tools/pull/223

**Comment by Tobski** [comment]
@mikes-lunarg Yea unfortunately I've been testing on a setup that doesn't have support for the extension, so was fudging values to avoid driver crashes during development. Now I know all my tests are hitting the right VUIDs, I will go back and look again... but should have a fix shortly.

As for the broken VUID, I guess it's a judgement call on your guys part - I don't mind temporarily breaking the generator with a hack, but it's not my codebase 😅 

I'll submit a fix for the Vulkan XML as well.

**Comment by Tobski** [comment]
@mikes-lunarg actually no wait there's no segfaults anymore, as expected. So that's.. fine? The only build failures I currently see are:
 - yet another unused variable (developing on windows means I don't get to see these locally... :()
 - some (what I can only assume are spurious?) failures to pull packages on the CI
 - the VUID I've mentioned

Where are you seeing segfaults? Or were you just looking at an earlier build?

**Comment by Tobski** [comment]
Right, just the implicit VU left as an issue now.

**Comment by Tobski** [comment]
For the sake of having the options on the table, I've pushed a change to hack the offending VU out of the spec for now, and I'm about to follow it up with a change to add in a placeholder check for the explicit VU that will replace it.

**Comment by mikes-lunarg** [comment]
I'm still seeing a seg fault at [core_validation.cpp:9460](https://github.com/Tobski/Vulkan-ValidationLayers/blob/fc6df198ec0c984d25f6e256324b8de188de3583/layers/core_validation.cpp#L9460). That whole loop looks like a leftover from an earlier refactor.

If I take it out, then I get a seg fault at [buffer_validation.cpp:475](https://github.com/Tobski/Vulkan-ValidationLayers/blob/fc6df198ec0c984d25f6e256324b8de188de3583/layers/buffer_validation.cpp#L475)

If I early-exit that function when `flags & VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT_KHR`, then I can get through the tests against the mock driver.

**Comment by Tobski** [comment]
> 
> 
> I'm still seeing a seg fault at [core_validation.cpp:9460](https://github.com/Tobski/Vulkan-ValidationLayers/blob/fc6df198ec0c984d25f6e256324b8de188de3583/layers/core_validation.cpp#L9460). That whole loop looks like a leftover from an earlier refactor.
> 
> If I take it out, then I get a seg fault at [buffer_validation.cpp:475](https://github.com/Tobski/Vulkan-ValidationLayers/blob/fc6df198ec0c984d25f6e256324b8de188de3583/layers/buffer_validation.cpp#L475)
> 
> If I early-exit that function when `flags & VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT_KHR`, then I can get through the tests against the mock driver.

Ack ok this explains some things, I'll fix that, not sure why I couldn't see it.

**Comment by mikes-lunarg** [comment]
Just a heads up, we are planning to cut initial SDK builds in about 3 hours.  If this feature doesn't make it to master by then, we have a little bit of time to try and cherry pick it into the SDK branch.  If that doesn't work, we will have to put some kind of warning in the release notes not to use the validation layers with VK_KHR_imageless_framebuffer.

**Comment by Tobski** [comment]
Ok I've pushed changes but now there's merge conflicts so I'll sort those out... hopefully it'll build in time now eep

**Comment by Tobski** [comment]
@mikes-lunarg Ok it builds and runs fine on my machine with the latest changes I've pushed, and I haven't changed the commit messages or anything else so in _theory_ this should all work. I have to head out for a bit but I'll check back in a couple hours to see how things are going...

**Comment by mikes-lunarg** [comment]
@Tobski I'm still seeing a seg fault at buffer_validation.cpp:475 with the latest changes.  Does something like this make sense to reuse those existing attachment checks?
https://gist.github.com/mikes-lunarg/524c349286730b6cec241f7d47230547

**Comment by Tobski** [comment]
Yea I realised what the issue was - I'm building the MockICD now that I realise it's a thing, and will run against that, hopefully will show up the issues and get this done, hopefully it's not too late to cherry pick 😬 .

**Comment by Tobski** [comment]
@mark-lunarg ok for whatever reason I can't seem to get the MockICD working no matter how I try to set the environment variables, so I'm just going to take your patch changes as-is and see if they get CI passing 🤦‍♂

**Comment by Tobski** [comment]
(Though I'll at least build it first and eyeball it in place..)

**Comment by Tobski** [comment]
Well, appveyor is passing, so just waiting on Travis to pass now 🤞

**Comment by Tobski** [comment]
Oof. Ok your change (with some modifications) worked as-is. Had kind of forgotten about VK_KHR_depth_stencil_resolve interactions; my local machine doesn't have that extension either. Ick. Hopefully easy to fix though...

**Comment by Tobski** [comment]
> Oof. Ok your change (with some modifications) worked as-is. Had kind of forgotten about VK_KHR_depth_stencil_resolve interactions; my local machine doesn't have that extension either. Ick. Hopefully easy to fix though...

Ok I'm getting a validation error stating that a bit that I've set isn't valid because it isn't supported by the implementation (for both depth and stencil):

> Unexpected:  [ VUID-VkSubpassDescriptionDepthStencilResolveKHR-depthResolveMode-03183 ] Object: VK_NULL_HANDLE (Type = 0) | vkCreateRenderPass2KHR(): Subpass 0 includes a VkSubpassDescriptionDepthStencilResolveKHR structure with invalid depthResolveMode=1. The Vulkan spec states: The value of depthResolveMode must be one of the bits set in VkPhysicalDeviceDepthStencilResolvePropertiesKHR::supportedDepthResolveModes or VK_RESOLVE_MODE_NONE_KHR (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSubpassDescriptionDepthStencilResolveKHR-depthResolveMode-03183)

> Unexpected:  [ VUID-VkSubpassDescriptionDepthStencilResolveKHR-stencilResolveMode-03184 ] Object: VK_NULL_HANDLE (Type = 0) | vkCreateRenderPass2KHR(): Subpass 0 includes a VkSubpassDescriptionDepthStencilResolveKHR structure with invalid stencilResolveMode=1. The Vulkan spec states: The value of stencilResolveMode must be one of the bits set in VkPhysicalDeviceDepthStencilResolvePropertiesKHR::supportedStencilResolveModes or VK_RESOLVE_MODE_NONE_KHR (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSubpassDescriptionDepthStencilResolveKHR-stencilResolveMode-0318

...but the bit in question is VK_RESOLVE_MODE_SAMPLE_ZERO_BIT_KHR which _must_ be supported by the implementation for both depth and stencil. I'm only getting this for one of the tests, so I'm assuming this is incorrectly triggering the wrong VUs, but still... investigation required. Sigh. If I could get the MockICD working this would be a lot easier :|

**Comment by mikes-lunarg** [comment]
Ok! I think that last error can just be resolved by updating the version of Vulkan-Tools in scripts/known_good.json

**Comment by Tobski** [comment]
> 
> 
> Ok! I think that last error can just be resolved by updating the version of Vulkan-Tools in scripts/known_good.json

Ah, is this a case of the MockICD not reporting limits correctly? That's then fine...

**Comment by Tobski** [comment]
> https://github.com/KhronosGroup/Vulkan-Tools/commit/9375e6c3b784aa9eef1dfe787e222cb8a2765b03

Aha 😅

**Comment by Tobski** [comment]
@mark-lunarg should I update it to ToT or just the change that fixed it?

**Comment by mikes-lunarg** [comment]
Yep, you found it

I can push up a known good update to your branch and see if that works, there's currently a weird interaction with known_good.json and generated/spirv_tools_commit_id.h

**Comment by Tobski** [comment]
@mikes-lunarg yes please!

**Comment by mikes-lunarg** [comment]
Ugh, of course that created a conflict.  I'm going to rebase your branch and cross my fingers.

**Comment by Tobski** [comment]
@mikes-lunarg 😬

**Comment by mark-lunarg** [comment]
@Tobski, ​Looks like you've probably already figured this out, but JIC, you need to:

`set VK_ICD_FILENAMES=/home/mark/dev/xgl/Vulkan-Tools/build/icd/VkICD_mock_icd.json`
Add the path for the vulkantools layers to your layers path:
`VK_LAYER_PATH=/home/mark/dev/xgl/Vulkan-ValidationLayers/build/layers:/home/mark/dev/xgl/VulkanTools/build/layersvt​`

For Windows, the path separator is a semicolon.  And of course, you need to specify the profile you want and to tell the tests to use devsim -- here's the whole mess (for Linux, I don't have notes for Windows):

`VK_DEVSIM_FILENAME=/home/mark/dev/xgl/Vulkan-ValidationLayers/tests/device_profiles/geforce_1080_ti.json VK_ICD_FILENAMES=/home/mark/dev/xgl/Vulkan-Tools/build/icd/VkICD_mock_icd.json  VK_LAYER_PATH=/home/mark/dev/xgl/Vulkan-ValidationLayers/build/layers:/home/mark/dev/xgl/VulkanTools/build/layersvt  ./vk_layer_validation_tests --devsim`

Good luck!

**Comment by Tobski** [comment]
@mikes-lunarg It passed! Thanks!

**Comment by Tobski** [comment]
@mark-lunarg yea I literally just figured out it's the dev sim profile I was missing 🤦‍♂

**Comment by Tobski** [comment]
(but also thanks!)

**Comment by Tobski** [comment]
🎉

**Pull request merged**
