### PR TITLE
Implement vkCmdExecuteCommands render pass scope checks

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@krOoze, looks great.  FFR, can you take a peek at the build details on one if the travis builds?  There's a non-blocking check there for the commit messages, that'll help things in the future.  Thanks!

**Comment by krOoze** [comment]
@mark-lunarg 50 char limit with combination with the mandatory "layers: " is practically impossible half the time to follow if one wants to write something actually representative of the commit contents. Consider rising it; real technical limit is 72 I think.

**Comment by mark-lunarg** [comment]
The 50/72 thing [is not arbitrary](https://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting).  And the description fulfills the actually-representative-of-commit-contents' part of the commit, and its limit is 72.

**Comment by mark-lunarg** [comment]
In any case, we'll discuss the idea with the VVL team and see what they say.

**Comment by krOoze** [comment]
@mark-lunarg Great!

The linked blog itself says "(though this isn’t a hard maximum)". And describes it as "This first line should be a concise summary of the changes introduced by the commit;"

The distribution graph provided in the linked SO, shows 50 is somewhat a median to strive for, rather than a limit. And it probably does not account for mandatory prefixes (e.g. "layers: ") in this repo.

**Comment by tobine** [comment]
My vote is to extend summary line to 72 chars as well.

**Pull request merged**
