### PR TITLE
layers: Move state tracker methods to CMD_BUFFER_STATE

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
Moving these methods requires a back pointer to the state
tracker in the command buffer objects for doing handle lookups.

### CODE REVIEW

**Comment by jeremyg-lunarg** [comment]
FYI @nadavgevaAMD

**Review by ncesario-lunarg — APPROVED** [review]
Didn't look terribly close, but LGTM!

**Comment by jzulauf-lunarg** [comment]
LGTM -- though with code movement changes, hard to assess.  Recommend additional testing (CTS/perf traces).

**Comment by jeremyg-lunarg** [comment]
This went through perf and error count vvltraces runs last night without regressions.

**Pull request merged**
