### PR TITLE
WIP: layers: Use shared_mutex (multi-read, single-write) lock for chassis dispatch functions

### PR DESCRIPTION
**Pull request by jeffbolznv**
Reduces parameter_validation-only time by 30% in my test app.

Older compilers may not support std::shared_mutex, but if so it should just be a matter of ifdefing the typedefs. Hopefully CI can flush out which compilers would need such a change.

### CODE REVIEW

**Comment by jeffbolznv** [comment]
Hmm, I was hoping for a better mix of supported/notsupported on Linux. Looks like all the CI jobs use older compilers/stdlibs that don't support shared_mutex. One even errored on shared_lock which is C++14.

One option would be to make this MSVC only, at least for now? @mark-lunarg or others, any thoughts?

**Comment by jeffbolznv** [comment]
I've made this optimization MSVC-only for now, so it's passing CI. Same for #1138.

**Comment by jeffbolznv** [comment]
Rebased past v119 (new generated functions)

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by jeffbolznv** [comment]
I've set this to WIP for now. I'm looking into further enhancing this with the bucket optimization from #1139, via a new concurrent_unordered_map class. I hope to have some results soon.

**Comment by jeffbolznv** [comment]
Closing in favor of #1159.

**Pull request closed without merging**
