### PR TITLE
Add validation and test for VUID 03421

### PR DESCRIPTION
**Pull request by souravpNV**

### CODE REVIEW

**Comment by souravpNV** [comment]
@mark-lunarg : failure is due to unrelated test VkPositiveLayerTest.TestAliasedMemoryTracking.
Looks like regression due to some other change.
#1736 also has the same failure

**Comment by mark-lunarg** [comment]
@souravpNV -- I will run this through CI, but first would you mind rebasing this please?  I would suggest updating your Master branch (git pull), creating a new branch, cherry-picking your layers commit to that branch, then cherry-picking your two tests commits.  Then you can force push that branch to this one 'vali'.  Let us know if you have any questions -- Thanks!

**Comment by souravpNV** [comment]
Thanks @mark-lunarg, updated.  
I have set up a remote upstream branch, but when I clone my repository to a new location and fetch upstream, my latest changes didn't show. That is why I Initiated one pull request from Khronos master -> fork.

I have one more relatively big change upcoming so looking to clean up my local repo.

**Comment by mark-lunarg** [comment]
Thanks @souravpNV, this looks much better!  Running through CI.

**Comment by mark-lunarg** [comment]
Tweaked commit msgs for style and pushed to Master.  Thanks @souravpNV...

**Pull request closed without merging**
