### PR TITLE
Fixing compilation error by CLANG

### PR DESCRIPTION
**Pull request by Artyom17**
By default, small_vector class uses uint8_t as size_type. However, there are a couple of spots where uint32_t is used as index for such small_vectors and this generates error in CLANG in strict mode. This PR fixes this error.

The errors look as follows:
```
../layers/subresource_adapter.h:365:88: error: implicit conversion loses integer precision: 'uint32_t' (aka 'unsigned int') to 'small_vector<unsigned long, 4, unsigned char>::size_type' (aka 'unsigned char') [-Werror,-Wimplicit-int-conversion]
    inline IndexType GetAspectSize(uint32_t aspect_index) const { return aspect_sizes_[aspect_index]; }
                                                                         ~~~~~~~~~~~~~ ^~~~~~~~~~~~
../layers/synchronization_validation.cpp:2748:49: error: implicit conversion loses integer precision: 'uint32_t' (aka 'unsigned int') to 'small_vector<ResourceAccessState::ReadState, 3, unsigned char>::size_type' (aka 'unsigned char') [-Werror,-Wimplicit-int-conversion]
            auto &other_read = other.last_reads[other_read_index];
```

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
Thanks for the PR @Artyom17, I'm not running into these particular warnings when running clang. Can you share the flags your using?

@jzulauf-lunarg @jeremyg-lunarg can one of you take a quick look please?

**Comment by jeremyg-lunarg** [comment]
We've hit this problem at least once before. I wonder if the default SizeType should be uint32_t. I'm pretty sure any possible space saving is just eaten up by alignment padding.

**Comment by jzulauf-lunarg** [comment]
Changing the default will likely break stuff in the opposite direction -- unless the interface to classes using small vector are using the same definition as is used by the small vector, this is going to happen.  So whatever we do, we'll need the correct flags/version to validate that it's good after.

the other choice would be to add "assert and cast" to the small_vector accessesors...

**Comment by jzulauf-lunarg** [comment]
@jeremyg-lunarg -- You spurred my curiosity... assuming a 64bit aligned value type... (which all uses are AFAICT). 

* With size_ and capacity_ first, as they are, SizeType < uint32_t never helps. 
* On 32bit, moving size_ and capacity_ to the end of the struct saves 8 bytes for SizeType  uint8_t and uint16_t -- though SizeType < uint16 never helps. 
* On 64 bit the location of size_ and capacity_ don't matter, and SizeType < uint32_t never helps.

[Code I used...](https://godbolt.org/z/dxPqTffzv)

**Comment by jeremyg-lunarg** [comment]
@jzulauf-lunarg, alignment is fun! I agree that we do need to have a way to reproduce the compiler errors before changing anything...

**Comment by jzulauf-lunarg** [comment]
agree that default SizeType uint32_t  makes sense as well.  Given the size of the "small vector allocation" and the restricted number of situations where there is *any* help with a smaller size, the larger default makes sense.  Probably was "too clever" to start off that way. Don't even know if it's useful to move cap/size to then end, as in a small mode there's better access propinquity for trivial small_vector

**Comment by Artyom17** [comment]
> Thanks for the PR @Artyom17, I'm not running into these particular warnings when running clang. Can you share the flags your using?
> 
> @jzulauf-lunarg @jeremyg-lunarg can one of you take a quick look please?

It is 
```
Clang version 11.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
```
The cmd line:
```
clang++ --target=aarch64-unknown-xros -DAPI_NAME=\"Vulkan\" -DDE_COMPILER=DE_COMPILER_CLANG -DDE_CPU=DE_CPU_ARM_64 -DDE_DEBUG -DDE_OS=DE_OS_XROS -DDE_PTR_SIZE=8 -DVK_ENABLE_BETA_EXTENSIONS -I../layers -I../layers/generated -I../external/Vulkan-Headers/src/include -I../external/glslang/src/SPIRV -I../external/SPIRV-Tools/src/include -I../external/SPIRV-Headers/src/include -I. -Ilayers -Wall -Wextra -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion     -nostdinc++     -D_LIBCPP_ABI_VERSION=2     -D_LIBCPP_HAS_MUSL_LIBC     -D_LIBCPP_HAS_THREAD_API_PTHREAD     -D_LIBCPP_HAS_NO_STDIN     -D_LIBCPP_HAS_THREAD_SAFETY_ANNOTATIONS     -frtti     -fexceptions          -D_ALL_SOURCE=1     -DZIRCON_TOOLCHAIN=1     -DWITH_FRAME_POINTERS=1     -fPIC     -ffreestanding     -fno-asynchronous-unwind-tables     -fno-common     -no-canonical-prefixes     -ffunction-sections     -fdata-sections     -mcpu=cortex-a53     --target=aarch64-xros     -fno-sanitize=safe-stack     -fno-sanitize=shadow-call-stack     -fno-stack-protector     -fno-omit-frame-pointer     -pthread      -fno-inline         -Wno-enum-conversion     -Wno-float-conversion     -Wno-gnu-empty-initializer     -Wno-shadow     -Wno-gnu-zero-variadic-macro-arguments     -Wno-gnu-statement-expression              -D__Fuchsia__ -std=c++14 -Wno-delete-non-virtual-dtor -fwrapv -fvisibility=hidden -fvisibility-inlines-hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -g -fPIC   -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -fvisibility=hidden -Werror -std=gnu++11 -MD -MT layers/CMakeFiles/VkLayer_khronos_validation.dir/synchronization_validation.cpp.obj -MF layers/CMakeFiles/VkLayer_khronos_validation.dir/synchronization_validation.cpp.obj.d -o layers/CMakeFiles/VkLayer_khronos_validation.dir/synchronization_validation.cpp.obj -c ../layers/synchronization_validation.cpp
```

**Comment by ncesario-lunarg** [comment]
@jzulauf-lunarg @jeremyg-lunarg it sounds like you're good with this change?

If so, would it also make sense to add `-Wconversion` to our build flags (apparently this is not included in `-Wall`, but rather `-Weverything`)?

**Comment by jeremyg-lunarg** [comment]
> @jzulauf-lunarg @jeremyg-lunarg it sounds like you're good with this change?
> 
> If so, would it also make sense to add `-Wconversion` to our build flags (apparently this is not included in `-Wall`, but rather `-Weverything`)?

Yeah I'm good with this change and agree with adding -Wconversion.  The other stuff we discussed is 'nice to have' but I'm not sure when I can get to it.

**Comment by ncesario-lunarg** [comment]
:+1: 

@Artyom17 would you mind adding `-Wconversion` to the list at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/09cdd47b9e5bd98d340e7e21736af5c1d76ddf29/CMakeLists.txt#L165 so we can catch this in the future? After that I think this change is good to go!

**Comment by Artyom17** [comment]
> @Artyom17 would you mind adding `-Wconversion` to the list at
> 
> https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/09cdd47b9e5bd98d340e7e21736af5c1d76ddf29/CMakeLists.txt#L165
> 
> so we can catch this in the future? After that I think this change is good to go!

Done. Also fixed several new issues revealed by the -Wconversion.

**Comment by ncesario-lunarg** [comment]
Looks like we'll have to hold off on enabling `-Wconversion`. I'll create an issue to track it, but there are a lot more changes that need to be made.

@Artyom17 are you able to build the x86_64 desktop version? Looks like you're cross compiling to arm; if you can do a "standard" build, you might see more warnings.

**Comment by Artyom17** [comment]
> Looks like we'll have to hold off on enabling `-Wconversion`. I'll create an issue to track it, but there are a lot more changes that need to be made.
> 
> @Artyom17 are you able to build the x86_64 desktop version? Looks like you're cross compiling to arm; if you can do a "standard" build, you might see more warnings. 

I've built a regular Linux build and fixed all the found warnings. You can see the additional commits in this PR.

**Comment by ncesario-lunarg** [comment]
@Artyom17 do you have the robin hood hash disabled? I'm still getting errors with this branch locally, but it looks like they might all be related to the robin hood hash library.

**Comment by Artyom17** [comment]
> robin hood

I have it enabled. How do you config the build exactly and how do you build?

**Comment by Artyom17** [comment]
> @Artyom17 do you have the robin hood hash disabled? I'm still getting errors with this branch locally, but it looks like they might all be related to the robin hood hash library.

I actually fixed a couple more warnings in this PR, can you approve the workflows to test?

**Comment by ncesario-lunarg** [comment]
@Artyom17

> How do you config the build exactly and how do you build?

```bash
CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -DUPDATE_DEPS=ON -B build
```

With clang version 11.1.0.

**Comment by ncesario-lunarg** [comment]
[tmp.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/6611371/tmp.txt)

These are the errors I'm getting locally.

**Comment by Artyom17** [comment]
Ok, I see the errors in robin-hood on my local Linux build as well, but those are caused by the -Wsign-conversion which was not added into my Linux build by default, I had to add that option manually into CMakeList.txt to see those errors.

I am not sure what to do with those, it seems like those warnings are out of the scope of this PR. Please, advise what to do. I can remove the -Wconversion option for this PR ( I am not sure if the -Wsign-conversion is a part of -Wconversion for the Linux compiler used by the automation builder), but the rest of the PR still should be useful, imo.

**Comment by ncesario-lunarg** [comment]
Ah, interesting. I also did not explicitly add `-Wsign-conversion` (I was just using this branch as is). It looks like `-Wconversion` is something of a "meta" flag, at least for the version of clang I'm using. Could you try the following patch? If this doesn't work for CI, then I would vote for leaving `-Wconversion` off, but keep the rest of this PR.
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 52950e54..1fad694a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -164,6 +164,15 @@ option(BUILD_WERROR "Treat compiler warnings as errors" ON)
 if(CMAKE_COMPILER_IS_GNUCC OR CMAKE_C_COMPILER_ID MATCHES "Clang")
     add_compile_options(-Wall
                         -Wconversion
+
+                        # TODO These warnings also get turned on with -Wconversion in some versions of clang.
+                        #      Leave off until further investigation.
+                        -Wno-sign-conversion
+                        -Wno-shorten-64-to-32
+                        -Wno-string-conversion
+                        -Wno-implicit-int-conversion
+                        -Wno-enum-enum-conversion
+
                         -Wextra
                         -Wno-unused-parameter
                         -Wno-missing-field-initializers
```

**Comment by ncesario-lunarg** [comment]
Now gcc isn't happy (I should have checked gcc last time 🤦‍♂️). How about we only enable these checks on clang for now? I did the following to get gcc happy:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c180bb219..1937059e7 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -161,9 +161,8 @@ endif()

 # Platform-specific compiler switches
 option(BUILD_WERROR "Treat compiler warnings as errors" ON)
-if(CMAKE_COMPILER_IS_GNUCC OR CMAKE_C_COMPILER_ID MATCHES "Clang")
-    add_compile_options(-Wall
-                        -Wconversion
+if(MAKE_C_COMPILER_ID MATCHES "Clang")
+    add_compile_options(-Wconversion

                         # TODO These warnings also get turned on with -Wconversion in some versions of clang.
                         #      Leave off until further investigation.
@@ -171,8 +170,11 @@ if(CMAKE_COMPILER_IS_GNUCC OR CMAKE_C_COMPILER_ID MATCHES "Clang")
                         -Wno-shorten-64-to-32
                         -Wno-string-conversion
                         -Wno-implicit-int-conversion
-                        -Wno-enum-enum-conversion
+                        -Wno-enum-enum-conversion)

+endif()
+if(CMAKE_COMPILER_IS_GNUCC OR CMAKE_C_COMPILER_ID MATCHES "Clang")
+    add_compile_options(-Wall
                         -Wextra
                         -Wno-unused-parameter
                         -Wno-missing-field-initializers
@@ -211,6 +213,19 @@ elseif(MSVC)
     add_compile_options("/w34245")
 endif()

+if(MAKE_C_COMPILER_ID MATCHES "Clang")
+    add_compile_options(-Wconversion
+
+                        # TODO These warnings also get turned on with -Wconversion in some versions of clang.
+                        #      Leave off until further investigation.
+                        -Wno-sign-conversion
+                        -Wno-shorten-64-to-32
+                        -Wno-string-conversion
+                        -Wno-implicit-int-conversion
+                        -Wno-enum-enum-conversion)
+
+endif()
+
 if(TARGET gtest OR IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/external/googletest)
     option(BUILD_TESTS "Build tests" ON)
 else()
```

**Comment by Artyom17** [comment]
@ncesario-lunarg  Done!

**Comment by ncesario-lunarg** [comment]
💯 time's the charm :)

Thanks @Artyom17, I think all the compilers we test with are finally happy!

**Pull request merged**
