### PR TITLE
tracker: Retire work when checking Timeline Semaphore Value

### PR DESCRIPTION
**Pull request by coki04**
Retire Queue submissions when Timeline Semaphore value is checked.

### CODE REVIEW

**Comment by coki04** [comment]
Aiming to fix issue #1999

**Review by farnoy — APPROVED** [review]
Looks good to me.

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by mark-lunarg** [comment]
Rebased and pushed to Master -- Thanks a bunch!

**Pull request closed without merging**
