### PR TITLE
layers: Fix YCbCr Format VUIDs

### LINKED ISSUE #1934: Missing validation for VkExternalMemoryImageCreateInfo with valid externalFormat
While adding support to ANGLE for importing external images I ran into validation errors that I don't think are errors.

In particular, I was getting complaints about an invalid VkFormat of VK_FORMAT_UNDEFINED. While it's generally true that having a VkFormat of VK_FORMAT_UNDEFINED is not valid, there are cases when using the VK_KHR_external_memory extension where it's required.

### PR DESCRIPTION
**Pull request by sfricke-samsung**
Closes #1934 

Removes: `VUID-VkSamplerYcbcrConversionCreateInfo-format-01649` (not a VU anymore)

Add: `VUID-VkSamplerYcbcrConversionCreateInfo-format-04060` and `VUID-VkSamplerYcbcrConversionCreateInfo-format-04061`

Fix: `VUID-VkSamplerYcbcrConversionCreateInfo-format-01904`

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by mark-lunarg** [comment]
@sfricke-samsung, this glitched on a couple of CI platforms:

This is on Linux Nvidia:
```
[ RUN      ] VkLayerTest.CreateYCbCrSampler
Unexpected: Validation Error: [ VUID-VkSamplerYcbcrConversionCreateInfo-format-01650 ] Object 0: handle = 0x74c3080, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x9f80a3e9 | vkCreateSamplerYcbcrConversionKHR(): Format VK_FORMAT_R8G8B8A8_SNORM does not support either VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT or VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT The Vulkan spec states: The potential format features of the sampler {YCbCr} conversion must support VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT or VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSamplerYcbcrConversionCreateInfo-format-01650)
/home/lunarg/.jenkins/w8/64-bit/Debug/tests/vkrenderframework.cpp:195: Failure
Failed
Received unexpected error(s).
[  FAILED  ] VkLayerTest.CreateYCbCrSampler (398 ms)
```

And same thing on AMD Windows:

```
[ RUN      ] VkLayerTest.CreateYCbCrSampler
Unexpected: Validation Error: [ VUID-VkSamplerYcbcrConversionCreateInfo-format-01650 ] Object 0: handle = 0x18a1697da30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x9f80a3e9 | vkCreateSamplerYcbcrConversionKHR(): Format VK_FORMAT_R8G8B8A8_SNORM does not support either VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT or VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT The Vulkan spec states: The potential format features of the sampler {YCbCr} conversion must support VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT or VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSamplerYcbcrConversionCreateInfo-format-01650)
C:\j\w8\64-bit\Debug\tests\vkrenderframework.cpp(195): error: Failed
Received unexpected error(s).
[  FAILED  ] VkLayerTest.CreateYCbCrSampler (1025 ms)
```

**Comment by sfricke-samsung** [comment]
@mark-lunarg was able to reproduce and failed as expected (amen for unit test) so just had to add an `SetUnexpectedError` for non-devsim runs

also rebased to fix merge conflict

**Comment by mark-lunarg** [comment]
Running through the farm...

**Pull request merged**
