### PR TITLE
layers: Check correct flag for SetColorBlendEnable

### PR DESCRIPTION
**Pull request by Darianopolis**
The SetColorBlendEnable check VUID-08643 should check for the relevant `pColorBlendEnables[i]` bit set, which is tracked by `cb_state->dynamic_state_value.color_blend_enabled` in [state_tracker.cpp:5830-5843](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/bea5beb302dc1add1bb9b52c8de37c0b92687159/layers/state_tracker/state_tracker.cpp#L5830-L5843)
Instead, it checks `cb_state->dynamic_state_value.color_blend_enable_attachments` which is set unconditionally.

Thus, with a color attachment that doesn't support `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT`, this validation check always fails even when `VK_FALSE` is correctly passed to `vkCmdSetColorBlendEnableEXT` for the relevant attachment.

### CODE REVIEW

**Review by juan-lunarg — COMMENTED** [review]
A test needs to be added to `tests/unit/shader_object.cpp` to prevent a regression. We have documentation explaining the process for adding a test. Although you should be able to figure it out from the tests in that file.

**Review by ziga-lunarg — APPROVED** [review]

**Comment by juan-lunarg** [comment]
Ah looks like there is an existing test case that needs modification with this change `NegativeShaderObject.MissingCmdSetColorBlendEnable` is failing now. So fixing that test should be good enough to get this PR merged in.

**Comment by Darianopolis** [comment]
@juan-lunarg Thanks, I've updated the tests now.

I had a look at `MissingCmdSetColorBlendEnable` and realized that it was indeed trying to test the negative case for this issue, however it was missing some setup and the name seemed to be copied from `MissingCmdSetColorBlendEnableEXT`.
I renamed it to `BlendEnabledWithNonBlendableFormat` and fixed the setup to match the required test case.

I also added a positive test case `DrawWithNonBlendableFormat` to catch any regressions (this new test correctly catches the original issue with `color_blend_enable_attachments`).

**Review by juan-lunarg — APPROVED** [review]
🥇 

Thanks for adding the additional testing. Fixes are nice, but fixes with tests are fantastic 👍🏾

**Pull request merged**
