### PR TITLE
build: Update to header 1.3.239

### PR DESCRIPTION
**Pull request by mikes-lunarg**
- Update known-good
- Add VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR stage to sync_val_gen.py
- Exclude ClusterCullingShadingHUAWEI from spirv_validation_generator.py
- Generate source
- Re-number VUID-vkCmdDrawIndexed-robustBufferAccess2-07788 to VUID-vkCmdDrawIndexed-robustBufferAccess2-07825
- Re-number VUID-vkCmdDrawMultiIndexedEXT-firstIndex-04938 to VUID-vkCmdDrawMultiIndexedEXT-robustBufferAccess2-07825
- Update copyright dates in code generators and generated files

- Update shader toolchain

### CODE REVIEW

**Comment by juan-lunarg** [comment]
Make sure to run `python3 scripts/check_code_format.py`, CI is failing due to out of date copyright notices

**Review by ncesario-lunarg — APPROVED** [review]
LGTM once CI is happy!

**Review by juan-lunarg — APPROVED** [review]
:+1:

**Comment by juan-lunarg** [comment]
Going to need to rebase on master to fix the macOS build warnings.

**Review by spencer-lunarg — APPROVED** [review]

**Pull request merged**
