### PR TITLE
layers: Changes required for VK_NV_optical_flow implementation

### PR DESCRIPTION
**Pull request by crohdewm**

### CODE REVIEW

**Comment by sjfricke** [comment]
@crohdewm you need to run `python3 ./scripts/generate_source.py ./external/Vulkan-Headers/registry/ ./external/SPIRV-Headers/include/spirv/unified1/` or the changes aren't going to take effect

**Comment by crohdewm** [comment]
> @crohdewm you need to run `python3 ./scripts/generate_source.py ./external/Vulkan-Headers/registry/ ./external/SPIRV-Headers/include/spirv/unified1/` or the changes aren't going to take effect

I think these manual changes are still required, there are similar changes for VK_QUEUE_VIDEO_DECODE_BIT_KHR/VK_QUEUE_VIDEO_ENCODE_BIT_KHR and VK_PIPELINE_STAGE_2_VIDEO_DECODE_BIT_KHR/VK_PIPELINE_STAGE_2_VIDEO_ENCODE_BIT_KHR in these files.

**Comment by jeremyg-lunarg** [comment]
> > @crohdewm you need to run `python3 ./scripts/generate_source.py ./external/Vulkan-Headers/registry/ ./external/SPIRV-Headers/include/spirv/unified1/` or the changes aren't going to take effect
> 
> I think these manual changes are still required, there are similar changes for VK_QUEUE_VIDEO_DECODE_BIT_KHR/VK_QUEUE_VIDEO_ENCODE_BIT_KHR and VK_PIPELINE_STAGE_2_VIDEO_DECODE_BIT_KHR/VK_PIPELINE_STAGE_2_VIDEO_ENCODE_BIT_KHR in these files.

Your changes to the scripts aren't in dispute. You just need to run the generate_source.py script and include the changed generated files in this PR. As you'll shortly see, there's a check in CI for this. :)

**Comment by jeremyg-lunarg** [comment]
Looks like most of the problems are that this needs the latest vulkan-headers to be pulled in to known_good.json, which should be in process.  But there's also some errors from the commit message format checker.

**Comment by crohdewm** [comment]
> Looks like most of the problems are that this needs the latest vulkan-headers to be pulled in to known_good.json, which should be in process. But there's also some errors from the commit message format checker.

Sorry, I wasn't aware of these format requirements. I've already changed the PR message accordingly but how can I modify the commit messages?

**Comment by jeremyg-lunarg** [comment]
> > Looks like most of the problems are that this needs the latest vulkan-headers to be pulled in to known_good.json, which should be in process. But there's also some errors from the commit message format checker.
> 
> Sorry, I wasn't aware of these format requirements. I've already changed the PR message accordingly but how can I modify the commit messages?

You can use git rebase -i  to change the commit messages and then git push -f to your branch and it'll update the PR.  You might as well wait to push until you can rebase on top of the headers update.  You can run scripts/check_code_format.py to catch these problems before pushing.

**Comment by crohdewm** [comment]
> > > Looks like most of the problems are that this needs the latest vulkan-headers to be pulled in to known_good.json, which should be in process. But there's also some errors from the commit message format checker.
> > 
> > 
> > Sorry, I wasn't aware of these format requirements. I've already changed the PR message accordingly but how can I modify the commit messages?
> 
> You can use git rebase -i to change the commit messages and then git push -f to your branch and it'll update the PR. You might as well wait to push until you can rebase on top of the headers update. You can run scripts/check_code_format.py to catch these problems before pushing.

I'm not so familiar with git, and somehow I messed up my local repo. Unfortunately I'm out for a couple of day, returning Tuesday, Could you perhaps make these changes?

**Comment by crohdewm** [comment]
> > > Looks like most of the problems are that this needs the latest vulkan-headers to be pulled in to known_good.json, which should be in process. But there's also some errors from the commit message format checker.
> > 
> > 
> > Sorry, I wasn't aware of these format requirements. I've already changed the PR message accordingly but how can I modify the commit messages?
> 
> You can use git rebase -i to change the commit messages and then git push -f to your branch and it'll update the PR. You might as well wait to push until you can rebase on top of the headers update. You can run scripts/check_code_format.py to catch these problems before pushing.

Ok, I've had some problems because I'm not so familiar with git, but I think I've made it finally. ;-)

**Pull request closed without merging**
