### PR TITLE
build: Update known-good files for 1.2.143 header [WIP]

### PR DESCRIPTION
**Pull request by shannon-lunarg**
Changes:
- Updated known-good files
- Modified `vk_validation_stats.py` to handle new latex expressions
- Generated new source files using `generate_source.py`
- Modified layer code and tests to clean up VUID consistency checks

### CODE REVIEW

**Comment by sfricke-samsung** [comment]
Heads up on a slightly nasty VU bug fixed in this header update:

`VUID-VkSamplerYcbcrConversionCreateInfo-format-01649` was removed and should now be `VUID-VkSamplerYcbcrConversionCreateInfo-format-04060`, (should be obvious as it replaced it in the same spot in the Vulkan-Doc repo, but wanted to give a heads up here)

I also will supply patch and tests for `VUID-VkSamplerYcbcrConversionCreateInfo-format-04061` after this merges

**Comment by shannon-lunarg** [comment]
An update: Header work is still progressing. I have all but a handful completed. Ran into some issues on my build machine that should be sorted tomorrow. As far as I can tell the 144 header did not introduce new VUID inconsistencies.

@sfricke-samsung, Is `VUID-VkSamplerYcbcrConversionCreateInfo-format-04060` a straightforward substitution in the layer code or does it also need to be accompanied by code changes? The wording is different enough for the new VUID that I wouldn't have known if the logic changed or not, so thank you for the help!

**Comment by sfricke-samsung** [comment]
@shannon-lunarg the simple code fix is

```
-        if (VK_FORMAT_UNDEFINED == conversion_format) {
-            skip |= LogError(device, "VUID-VkSamplerYcbcrConversionCreateInfo-format-01649",
-                             "%s: CreateInfo format type is VK_FORMAT_UNDEFINED.", func_name);
+        if (FormatIsUNorm(conversion_format) == false) {
+            skip |= LogError(device, "VUID-VkSamplerYcbcrConversionCreateInfo-format-04060",
+                             "%s: CreateInfo format type (%s) is not an UNORM format.", func_name, string_VkFormat(conversion_format));
```

So I would just apply that!

**Comment by shannon-lunarg** [comment]
Thank you for your help, @sfricke-samsung. I have included this modification in #1952.

I am closing this PR because #1952 absorbs all of the changes found here.

**Pull request closed without merging**
