### PR TITLE
tests: Test vkCmdExecuteCommands into a Secondary

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by krOoze** [comment]
nah, just the usual clang-formatting...

**Comment by krOoze** [comment]
fixt.

BTW Do the copyright notices serve any purpose? The Google Style says:

>New files should usually not contain copyright notice or author line.

**Comment by mark-lunarg** [comment]
@krOoze, I'm guessing that's for their internal stuff? -- in any case copyright notices are all over the AOSP source.  We do it to satisfy legal obligations.

**Comment by mark-lunarg** [comment]
Running through the farm.

**Pull request merged**
