### PR TITLE
layers: Update VkAttachmentDescription VUs

### PR DESCRIPTION
**Pull request by sfricke-samsung**
Will be valid when https://github.com/KhronosGroup/Vulkan-Docs/pull/1708 is merged (I will update the `TODO` with VUIDs when they are generated)

cc @oddhack

### CODE REVIEW

**Review by ncesario-lunarg — COMMENTED** [review]
LGTM (though the ternary operator looks like it's on the verge of getting abused IMHO :)).

@sfricke-samsung, I'll try to keep an eye on the Vulkan-Docs change, but just updating this PR once that goes in should be sufficient for me to pick it up.

**Comment by sfricke-samsung** [comment]
added VUs, will be in 202 headers (cc @mikes-lunarg if you want to just cherry pick this)

@ncesario-lunarg I agree the ternary is ugly, but it was that or break

```cpp
if (initial_layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL ||
initial_layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL ||
initial_layout == VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL ||
initial_layout == VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL) { }

if (final_layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL ||
final_layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL ||
final_layout == VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL ||
final_layout == VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL) { }
```

to

```cpp
if (initial_layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL ||
    initial_layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL) {
    vuid = use_rp2 ? "" : "";
} else if (initial_layout == VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL ||
    initial_layout == VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL) {
    vuid = use_rp2 ? "" : "";
}

if (final_layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL ||
    final_layout == VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL) {
    vuid = use_rp2 ? "" : "";
} else if (final_layout == VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL ||
    final_layout == VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL) {
    vuid = use_rp2 ? "" : "";
}
```

so open to either option to be honest

**Comment by ncesario-lunarg** [comment]
Thanks @sfricke-samsung! I'll hold off until we pick up 1.2.202 headers.

**Comment by mikes-lunarg** [comment]
Rolled into #3618

**Pull request closed without merging**
