### PR TITLE
Update AHB Documentation to Android Q and better logging

### PR DESCRIPTION
**Pull request by sfricke-samsung**
Main goal was to improve logging messages from AHB errors, but also updated documentation to represent Android Q (nothing to AHB in terms of effecting tests with Android Q)

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by sfricke-samsung** [comment]
rebased merge conflict

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by mark-lunarg** [comment]
Passed CI.  Fixed clang-format issue and pushed to Master.

**Pull request closed without merging**
