### PR TITLE
Update to vulkan header version 1.1.117

### PR DESCRIPTION
**Pull request by jekstrand**
This PR contains two commits.  The first just re-runs the generator scripts against the 1.1.117 headers and commits the changes.  The second fixes shader validation for the new denorm and rounding mode independence enum that was added in Vulkan 1.1.116

### CODE REVIEW

**Comment by shannon-lunarg** [comment]
Hello! The ValidationLayers known-good (which includes freshly generated source files) has not yet been updated because we are waiting for a code change concerning build dependencies to be merged to master. This has been in the works for about a week. We are currently performing internal testing on the required changes and the known-good will be updated shortly after they are merged. In the future, I will be creating an issue in this repo if known-good updates are delayed for a significant amount of time. I will comment here once the 117 known-good has been updated.

**Comment by shannon-lunarg** [comment]
The changes I was waiting on that I mentioned earlier have been merged to VVL master and exposed a new problem with `vulkan.hpp`. An issue has been raised in the Vulkan-Hpp repo to address this new issue but will further delay updating this repo's known-good.

**Comment by locke-lunarg** [comment]
Related [issue #1133 ](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1133)

**Comment by jekstrand** [comment]
This has been subsumed by 3cc90bcf8cfef52366a93c62d66ec8eef09b7059

**Pull request closed without merging**
