### PR TITLE
syncval support for acquire/present

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Functionally complete with unit test.  Need to move on to application level testing to call it beta quality.

### CODE REVIEW

**Comment by jzulauf-lunarg** [comment]
@jeremyg-lunarg  -- CI'd /  ULT'd  and ready for review.

**Review by jeremyg-lunarg — COMMENTED** [review]
Mostly LGTM. The only real concerns are the UINT64_MAX timeouts in the tests, and clarification about the empty PreCallValidate methods.

**Comment by jeremyg-lunarg** [comment]
LGTM, UINT64_MAX -> kWaitTimeout and empty validate methods were fixed

**Comment by jzulauf-lunarg** [comment]
@jeremyg-lunarg  -- the lambda to wrap that might be useful to find a way to generify.

**Pull request merged**
