### PR TITLE
layers: support FreeBSD

### PR DESCRIPTION
**Pull request by hikiko**
Modifications for Validation-Layers to compile and run on FreeBSD.

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
LGTM, thanks!

**Comment by ncesario-lunarg** [comment]
@hikiko if you could please update the copyright in [tests/test_common.h](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3380/checks?check_run_id=3783497117#step:4:15) (i.e., `2020` -> `2021`), I think this should be good to go!

**Comment by ncesario-lunarg** [comment]
This was merged in #3390.

**Comment by hikiko** [comment]
> @hikiko if you could please update the copyright in [tests/test_common.h](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3380/checks?check_run_id=3783497117#step:4:15) (i.e., `2020` -> `2021`), I think this should be good to go!

@ncesario-lunarg apologies I didn't, thanks you merged this with your other branch!

**Pull request closed without merging**
