### PR TITLE
spirv-hopper: Add non 32-bit support and sort structs by ID

### PR DESCRIPTION
**Pull request by spencer-lunarg**
Fixes from adding glslang test suite shaders

### CODE REVIEW

**Comment by spencer-lunarg** [comment]
seems spriv-reflect is hitting a `maybe-uninitialized` compiler error with gcc, will fix in spirv-reflect and update the commit in the known_good

**Review by juan-lunarg — DISMISSED** [review]

**Comment by spencer-lunarg** [comment]
Sorry, I am just pushing things up, but waiting for SPIRV-Reflect changes to get merged, until then, this will fail

**Comment by juan-lunarg** [comment]
> Sorry, I am just pushing things up, but waiting for SPIRV-Reflect changes to get merged, until then, this will fail

It doesn't really matter but in cases like this I like to work in my fork, until I'm reasonably ready to present. Since that way I can still get the benefit of github actions CI testing. While avoiding making a PR.

**Comment by spencer-lunarg** [comment]
ya, well this "was" going to be ready, then there was an issue with spirv-reflect caught in the GCC build and things snowballed from there... I am going to just close this PR to prevent wasteful internal CI builds while I get things all cleaned up

**Pull request closed without merging**
