### PR TITLE
Cmayer vk nv clip space w scaling

### PR DESCRIPTION
**Pull request by cmayer1**

### CODE REVIEW

**Comment by cmayer1** [comment]
@mark-lunarg 
I re-based locally and run the layer tests on a system that has the extension VK_NV_cooperative_matrix enabled and on a system that has the extension disabled. On both systems I saw all tests passing. Where did the CooperativeMatrixNV test fail for you? Do you have some additional details how to reproduce the failure.
Thanks
Chris

**Comment by mark-lunarg** [comment]
@cmayer1, you are absolutely right -- we had a regression that was reverted and I believe you were in the middle of it.  Rebased and am running through CI again -- thanks for your patience.

**Comment by mark-lunarg** [comment]
@cmayer1, started to rebase this and noticed when moving the statetracker function (these now live in another file) that the record func is misnamed (PreCallRecord**Validate**CmdSetViewportWScalingNV) and so was not getting called by the chassis.  Anyway, would you mind rebasing and making sure everything is working as you intended?  Thanks!

**Comment by cmayer1** [comment]
@mark-lunarg, I rebased, renamed the function to PreCallRecordCmdSetViewportWScalingNV (thanks for catching this) and moved the function to state_tracker.cpp

**Comment by mark-lunarg** [comment]
Thanks!  Running through CI again.

**Comment by cmayer1** [comment]
@mark-lunarg, thanks for reviewing and merging

**Pull request merged**
