### PR TITLE
Invalid message "...sizeof(vkCmdDrawIndexedIndirectCount)..."

### PR DESCRIPTION
**Pull request by Andreyogld3d**
drawdispatch: Fix Invalid message '...sizeof(vkCmdDrawIndexedIndirectCount)...'

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]

**Comment by ncesario-lunarg** [comment]
So, something like
```
layers: Fix Invalid message

Fix '...sizeof(vkCmdDrawIndexedIndirectCount)...'.
```

Should make the format check happy. The subject line (first line in the commit) needs start with a "module" keyword and follow the above format. You should be able to `git commit --amend` to fix this commit message and then run `python ./scripts/check_code_format.py` to see if the commit is formatted correctly.

**Comment by sfricke-samsung** [comment]
If it isn't too much to ask `CoreChecks::ValidateCmdDrawIndirectCount` 

there is 

```
skip |= ValidateCmdDrawStrideWithStruct(commandBuffer, "VUID-vkCmdDrawIndirectCount-stride-03110", stride, apiName, sizeof(VkDrawIndirectCommand));
```

Could you fix that as well, since it has the same issue I realize

**Comment by Andreyogld3d** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3017

**Comment by Andreyogld3d** [comment]
Hi @ncesario-lunarg,  @sfricke-samsung 
we can merge https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3021 :)
sorry for my errors

**Comment by ncesario-lunarg** [comment]
No worries :) Please see my comment on #3021.

**Pull request closed without merging**
