### PR TITLE
Add privateData feature VUID

### PR DESCRIPTION
**Pull request by sfricke-samsung**
VUID-vkCreatePrivateDataSlotEXT-privateData-04564

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
[Internal CI running](http://erusea:4040/8157).

**Review by ncesario-lunarg — APPROVED** [review]
LGTM! Waiting on internal CI and also trying to figure out what's going with Github actions.

**Comment by ncesario-lunarg** [comment]
@sfricke-samsung unfortunately the `VkLayerTest.PrivateDataFeature` is crashing on our nvidia machine. I'll see if I can gather some more details later today.

**Comment by sfricke-samsung** [comment]
I think I see it
```
    const auto *private_data_features = LvlFindInChain<VkPhysicalDevicePrivateDataFeaturesEXT>(device_createinfo_pnext);
    if (!private_data_features->privateData) {
```
    should probably check `private_data_features ` isn't null before dereferencing 🤦

**Comment by ncesario-lunarg** [comment]
Running new patch through internal CI.

**Pull request merged**
