### PR TITLE
tests: Fix WSI extension logic

### PR DESCRIPTION
**Pull request by juan-lunarg**
Currently WSI testing is a bit broken on linux since AddSurfaceExtension doesn't line up with CreateSurface.

In the new approach
- WSI extensions queried properly
- If AddSurfaceExtension is called at least 1 WSI will be required when calling AreRequiredExtensionsEnabled
- VkRenderFramework::CreateSurface checks if the extension is enabled
- Specific WSI tests now have to explicitly check for their desired WSI extension

### CODE REVIEW

**Comment by juan-lunarg** [comment]
> Currently WSI testing is a bit broken on linux since AddSurfaceExtension doesn't line up with CreateSurface.

To be more clear tests will fail depending on your environment on linux.

```
Validation Error: [ UNASSIGNED-GeneralParameterError-ExtensionNotEnabled ] Object 0: handle = 0x55555761a910, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xe92b452d | Attempted to call vkCreateXlibSurfaceKHR() but its required extension VK_KHR_xlib_surface has not been enabled
```

**Comment by charles-lunarg** [comment]
When you say tests fail on linux, are you referring to the current behavior or the new behavior that this PR adds?

**Comment by juan-lunarg** [comment]
> When you say tests fail on linux, are you referring to the current behavior or the new behavior that this PR adds?

I'm referring to the current behavior this new PR fixes. Now all test pass on my machine with my PR.

**Comment by ncesario-lunarg** [comment]
On my local linux setup (only wayland, no X installed), `VkPositiveLayerTest.CmdCopySwapchainImage` fails (actually hangs) pretty early, seemingly in `vk::EnumerateInstanceExtensionProperties`, but it's hard to say as the stack is likely incorrect in my local run.

**Comment by juan-lunarg** [comment]
Wayland still needs to be added to `VkRenderFramework`

`VkRenderFramework::CreateSurface` currently only handles X11/XCB/WIN32/Android

My PR just cleans up the extension code and gets my X11 testing working again.

Another PR still needs to be done to properly add Wayland to the `VkRenderFramework`

**Comment by juan-lunarg** [comment]
> On my local linux setup (only wayland, no X installed), `VkPositiveLayerTest.CmdCopySwapchainImage` fails (actually hangs) pretty early, seemingly in `vk::EnumerateInstanceExtensionProperties`, but it's hard to say as the stack is likely incorrect in my local run.

Tried reproducing the failure. My primary wsi on my system is wayland. And I've disable x11/xcb via the cmake options.

```
juan@pop-os:~/projects/vvl$ loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'
wayland
```

I don't get a crash with either the mock driver, intel, nvidia, or lavapipe.

```
Note: Google Test filter = VkPositiveLayerTest.CmdCopySwapchainImage
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from VkPositiveLayerTest
[ RUN      ] VkPositiveLayerTest.CmdCopySwapchainImage
/home/juan/projects/vvl/tests/positive/image_buffer.cpp:1726: Skipped
Cannot create surface or swapchain
[  SKIPPED ] VkPositiveLayerTest.CmdCopySwapchainImage (16593 ms)
[----------] 1 test from VkPositiveLayerTest (16593 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (16600 ms total)
[  PASSED  ] 0 tests.
[  SKIPPED ] 1 test, listed below:
[  SKIPPED ] VkPositiveLayerTest.CmdCopySwapchainImage
```

**Review by ncesario-lunarg — APPROVED** [review]

**Pull request merged**
