### PR TITLE
layers: Switch chassis to read/write locking

### PR DESCRIPTION
**Pull request by jeffbolznv**
(Note: stacked on #1306)

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Rebased and running through CI.

**Comment by mark-lunarg** [comment]
@jeffbolznv, did you change something, or just rebase?

**Comment by jeffbolznv** [comment]
Just rebased.

**Comment by mark-lunarg** [comment]
Ah.  No need to rebase these guys, they're all going through CI now.  If you do rebase or change, please leave a comment so I know if I need to resubmit or not...

**Pull request merged**
