### PR TITLE
gn: Use check_call for CI

### PR DESCRIPTION
**Pull request by spencer-lunarg**
@y-novikov I found why CI has not been failing properly

(I assume this first run will fail, from there I will turn this PR into something that fixes things)

### CODE REVIEW

**Comment by y-novikov** [comment]
> CI Vulkan-ValidationLayers build # 16014 passed.

Hmm, doesn't look like it did.

**Comment by spencer-lunarg** [comment]
> CI Vulkan-ValidationLayers build # 16014 passed.
> Hmm, doesn't look like it did.

@y-novikov this is our internal CI, but the Github Actions are now blocked (like we thought they were)

image

**Review by jeremyg-lunarg — APPROVED** [review]

**Comment by spencer-lunarg** [comment]
Internal CI failure was from an `NegativeGpuAVRayQuery.TMaxLessThenTmin` isolated issue outside the scope of this change

**Comment by y-novikov** [comment]
Super, thank you for fixing both and the build and the future checks!

**Pull request merged**
