### PR TITLE
Dummy:  to test for linux build failures

### PR DESCRIPTION
**Pull request by souravpNV**
Common change has both test and layer change

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@souravpNV -- Hey, this is exactly what we've been looking for!  I've already combined the two commits in PR #1730, so this one shouldn't be necessary unless you've made changes to either of those commits.  Thanks!

**Comment by souravpNV** [comment]
@mark-lunarg Thanks for taking care of that, I just created this to test if Linux build is passing when both of the changes are combined.
So just to clarify for future, test and layers will be separate commit but can be in same PR.

This can be closed as it is.

**Comment by mark-lunarg** [comment]
@souravpNV, yes, just as you have here with the layers commit first and the tests on top.  Lots of stuff to learn here, and next time you'll sail right through it!  Thanks for your patience.

**Comment by souravpNV** [comment]
@mark-lunarg : Thanks, I will make a note of this for future check-ins

**Pull request closed without merging**
