### PR TITLE
core_validation: bug: CoreChecks::GpuAllocateValidationResources doesn't use "bind_point" parameter

### PR DESCRIPTION
**Pull request by Andreyogld3d**
Hi! I have bug during using Validation layers:

```
vkCmdBindPipeline(..., VK_PIPELINE_BIND_POINT_COMPUTE, ...);
vkCmdDispatch(...)
```
After calling  vkCmdDispatch, i got error "Unable to find pipeline state",. I think there is a problem of using 
VK_PIPELINE_BIND_POINT_GRAPHICS instead of "bind_point" parameter.

BR, Andrey

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Tony, does GPUAV support compute yet?

**Comment by Tony-LunarG** [comment]
Can you limit the search to BIND_POINT_GRAPHICS and BIND_POINT_COMPUTE.  I don't think the GPUAV code is ready for BIND_POINT_RAY_TRACING_NV yet.
Also there are 3 commits on this branch and there only needs to be one.

**Comment by Andreyogld3d** [comment]
Hi! You should apply last commit:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/8aa919037a53f82b60381afddab0cb5536e0c280

**Comment by Tony-LunarG** [comment]
If you could please change "pipilines" to "pipelines" in the last commit message and squash the commit and revert of  GLOBAL_CB_NODE, this should be good to go.  Thanks.

**Comment by Andreyogld3d** [comment]
Ok, you should apply commit 
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/845/commits/146f36846cf5fba8a910818fc10106005ec37dc5

**Comment by Tony-LunarG** [comment]
Merged

**Pull request closed without merging**
