### PR TITLE
build: Automate self vvl renaming

### PR DESCRIPTION
**Pull request by spencer-lunarg**
This will `-DBUILD_SELF_VVL=ON` in CI to be able to build the Self Validation so we can run on it easier

cc @arno-lunarg

### CODE REVIEW

**Review by arno-lunarg — APPROVED** [review]
nice!

**Comment by y-novikov** [comment]
ANGLE isn't able to load VK_LAYER_KHRONOS_validation after this:
https://chromium-review.googlesource.com/c/angle/angle/+/5650353

Could you please update BUILD.gn similarly to CMakeLists.txt?
@cnorthrop

**Comment by y-novikov** [comment]
@dneto0 in case you wonder why https://chromium-review.googlesource.com/c/chromium/src/+/5650456 failed.

**Comment by spencer-lunarg** [comment]
Created https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8188

I only grepped in `BUILD.gn` but seems there is some extra script (wasn't aware of) that is where these JSON files are injected with the string

**Pull request merged**
