### PR TITLE
build: Fix clang warnings

### PR DESCRIPTION
**Pull request by MarkY-LunarG**
Latest clang generated multiple build warnings.  This should resovle
the issues encountered.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
This LGTM, @Tony-LunarG should also have a look at it.

**Review by Tony-LunarG — COMMENTED** [review]
resolve is misspelled in the commit message.

**Comment by Tony-LunarG** [comment]
Could you please add to the change log in vk_mem_alloc.h?

**Comment by MarkY-LunarG** [comment]
> resolve is misspelled in the commit message.

Done

> Could you please add to the change log in vk_mem_alloc.h?

Done.

**Comment by Tony-LunarG** [comment]
Running through internal CI, then good to go

**Review by Tony-LunarG — APPROVED** [review]
LGTM

**Pull request merged**
