### PR TITLE
build: export build commands

### PR DESCRIPTION
**Pull request by jasuarez**
Generate compile_commands.json, which can be used by different external
tools for different purposes (e.g., Emacs + LSP).

Change-Id: I7386063bee373a40bf0870c119e40b955dbaa39f

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Hey @mikes-lunarg, seems benign, 'cept for Ninja.  This OK with you?

**Comment by mikes-lunarg** [comment]
@mark-lunarg Yeah it's harmless.  I don't necessarily agree that we should be hard-coding options that can be passed on the command line, but I can't imagine this causing issues for anyone.

**Comment by mark-lunarg** [comment]
@mikes-lunarg, let's do this one.  If more folks show up wanting command-line things, we can undo it and create a policy.

**Comment by mark-lunarg** [comment]
Tweaked commit msg and pushed to Master.

**Pull request closed without merging**
