### PR TITLE
layers: Relabel STAGE_NONE VUs

### PR DESCRIPTION
**Pull request by sfricke-samsung**
(Marked WIP until https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4648 lands and merged, might need to cherry pick this change when updating headers)

Fixed Sync2 VUs labels for 

> If the synchronization2 feature is not enabled, srcStageMask must not be 0

cases

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
LGTM, but @jeremyg-lunarg should probably take a quick look.

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM too

**Comment by sfricke-samsung** [comment]
VUID in 185 spec, updated with them and ready to merge now (removed WIP)

**Comment by sfricke-samsung** [comment]
Failing CI for invalid VU it seem, will just need to wait to rebase on new headers being pulled in I guess

**Comment by ncesario-lunarg** [comment]
> Failing CI for invalid VU it seem, will just need to wait to rebase on new headers being pulled in I guess

Yeah, I think we need to wait until we move to the 1.2.185 headers.

**Comment by ncesario-lunarg** [comment]
The failure looks like it is due to a bad commit that got merged to master. I think if you rebase and push, this should be GTG.

**Comment by ncesario-lunarg** [comment]
This one is my bad. #3032 also needs to get merged to disable the failing S10 tests. I can see all platforms look good except for the S10, so going ahead with merge.

**Pull request merged**
