### PR TITLE
Build system fixes

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/khronosgroup/vulkan-validationlayers/1843)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
ping

**Comment by mark-lunarg** [comment]
@marcinslusarz, can you outline your underlying reason for this change?  As you quite rightly point out, glslang and spirv-tools are two separate repos, but we specifically need/want to use the version glslang uses, and wish to avoid using or having two different versions.  That said, we're not adamantly opposed to such a change, but they can produce unforeseen issues.  Thanks!

**Comment by marcinslusarz** [comment]
I install each project to a separate prefix under $HOME, so I can wipe it out and reinstall if there's such need (I can list many reasons why this would be the case). It's also useful if I want to have multiple versions installed. 

Right now Vulkan-ValidationLayers forces me to install glslang and spirv-tools into one prefix because it uses only one variable for discovering them.

**Comment by mark-lunarg** [comment]
Running through CI.

**Pull request merged**
