### PR TITLE
tests: Don't Validation failures for Android

### PR DESCRIPTION
**Pull request by juan-lunarg**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Hey Juan, is this just an experiment or is there an issue driving this change?  Just curious!

**Comment by juan-lunarg** [comment]
> Hey Juan, is this just an experiment or is there an issue driving this change? Just curious!

I forgot to link this issue:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4673

**Comment by juan-lunarg** [comment]
This is an experiment to find how many failures Android still has given the improvements in testing. Based on CI I'll decide where to go from there.

**Comment by juan-lunarg** [comment]
See here for a list of tests that fail on Android with this change:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4673#issuecomment-1386296960

**Pull request closed without merging**
