### PR TITLE
Add validation support for VK_INDEX_TYPE_UINT8_EXT

### PR DESCRIPTION
**Pull request by pdaniell-nv**

### CODE REVIEW

**Comment by jeffbolznv** [comment]
Would you mind hooking up these two in parameter validation?

```
ifdef::VK_NV_ray_tracing[]
  * [[VUID-vkCmdBindIndexBuffer-indexType-02507]]
    pname:indexType must: not be ename:VK_INDEX_TYPE_NONE_NV.
endif::VK_NV_ray_tracing[]
ifdef::VK_EXT_index_type_uint8[]
  * [[VUID-vkCmdBindIndexBuffer-indexType-02765]]
    If pname:indexType is ename:VK_INDEX_TYPE_UINT8_EXT, the
    <<features-indexTypeUint8,indexTypeUint8>> feature must: be enabled
endif::VK_EXT_index_type_uint8[]
```

**Comment by pdaniell-nv** [comment]
I added the missing VU checks.

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by mark-lunarg** [comment]
Rebased and pushed to Master.

**Pull request closed without merging**
