### PR TITLE
Add support for Map Memory VUID

### PR DESCRIPTION
**Pull request by sfricke-samsung**
- VUID-vkMapMemory-size-00678
- VUID-vkMapMemory-size-00679
- VUID-vkMapMemory-size-00680
Where already supported, just not labeled
 ----
VUID-vkMapMemory-offset-00679 doesn't need to be wrapped in the `size == VK_WHOLE_SIZE` logic
> offset must be less than the size of memory
----
Added support for
VUID-VkMappedMemoryRange-memory-00684
> memory must be currently host mapped

### CODE REVIEW

**Comment by jeremy-lunarg** [comment]
I'm seeing the following failure in our test farm.

[ RUN      ] VkLayerTest.InvalidMemoryMapping
Unexpected: [ VUID-vkMapMemory-memory-00678 ] Object: 0x40000000004 (Type = 8) | VkMapMemory: Attempting to map memory on an already-mapped VkDeviceMemory 0x40000000004[]. The Vulkan spec states: memory must not be currently host mapped (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkMapMemory-memory-00678)
Other error messages logged for this test were:
     [ VUID-vkMapMemory-memory-00678 ] Object: 0x40000000004 (Type = 8) | VkMapMemory: Attempting to map memory on an already-mapped VkDeviceMemory 0x40000000004[]. The Vulkan spec states: memory must not be currently host mapped (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkMapMemory-memory-00678)
/home/lunarg/.jenkins/w8/64-bit/Debug/tests/vkrenderframework.cpp:162: Failure
Failed
Did not receive expected error 'UNASSIGNED-CoreValidation-MemTrack-InvalidMap'
Unexpected: [ VUID-vkMapMemory-offset-00679 ] Object: 0x40000000004 (Type = 8) | VkMapMemory: Attempting to map memory with an offset of 0x10001 which is larger than the total array size 0x10000 The Vulkan spec states: offset must be less than the size of memory (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkMapMemory-offset-00679)
Other error messages logged for this test were:
     [ VUID-vkMapMemory-offset-00679 ] Object: 0x40000000004 (Type = 8) | VkMapMemory: Attempting to map memory with an offset of 0x10001 which is larger than the total array size 0x10000 The Vulkan spec states: offset must be less than the size of memory (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkMapMemory-offset-00679)
/home/lunarg/.jenkins/w8/64-bit/Debug/tests/vkrenderframework.cpp:162: Failure
Failed
Did not receive expected error ' with size of VK_WHOLE_SIZE oversteps total array size 0x'
Unexpected: [ VUID-vkMapMemory-memory-00678 ] Object: 0x40000000004 (Type = 8) | VkMapMemory: Attempting to map memory on an already-mapped VkDeviceMemory 0x40000000004[]. The Vulkan spec states: memory must not be currently host mapped (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkMapMemory-memory-00678)
/home/lunarg/.jenkins/w8/64-bit/Debug/tests/vkrenderframework.cpp:172: Failure
Failed
Received unexpected error(s).
/home/lunarg/.jenkins/w8/64-bit/Debug/tests/vkrenderframework.cpp:162: Failure
Failed
Did not receive expected error 'Unmapping Memory without memory being mapped: '
             TEST SKIPPED: Failed to set memory type.

**Comment by jeremy-lunarg** [comment]
I need to refactor some changes from your test patch into the layer patch to prevent the failure.

**Comment by jeremy-lunarg** [comment]
Squashed locally and pushed to master. Thank you @sfricke-samsung

**Comment by sfricke-samsung** [comment]
sorry, I forgot to make sure to check the layer commit didn't need patches on the tests commit to past the tests... thanks for cleaning up @jeremy-lunarg  for me

**Pull request closed without merging**
