### PR TITLE
doc: Fix links on LunarXchange

### PR DESCRIPTION
**Pull request by christophe-lunarg**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@christophe-lunarg, can you point us to the broken links?

**Comment by KarenGhavam-lunarG** [comment]
The ./ format works while within the repository. However when the markdown is translated to html to upload to the SDK site, those links won't work. You can view them broken on the LunarXchange site (look at the version "master" in the dropdown).

**Comment by mark-lunarg** [comment]
@KarenGhavam-lunarG, I looked, but could not find them -- which doc are they in?

**Comment by mark-lunarg** [comment]
Oh, OK.  I see them now.

**Comment by Groovounet** [comment]
@mark-lunarg I find this change really hinky because we just broke the logic of Git branches to allow pulling master branch document to a totally different system. When I am on a different branch than master branch, that branch should be a full version of itself, not a made of part of others versions.

Most probably something to resolve on how we handle docs on LunarXchange.

**Comment by mark-lunarg** [comment]
This, exactly!  Thanks @christophe-lunarg.

**Pull request merged**
