### PR TITLE
Arm PerfDoc Check 24 - Pipeline Bubble Tracking

### PR DESCRIPTION
**Pull request by samwalls-arm**
Hey there,

Here are some checks pertaining to tracking pipeline bubbles based on: work pushed to pipeline stages + various types of dependencies between pipeline stages (including pipeline barriers, subpass dependencies, and `VkEvent` dependencies).

These are some of the last checks explicitly ported from the original PerfDoc. Attilio started this quite a while ago, and I've since finished everything.

Let me know what you think.

Thanks,
Sam Walls

### CODE REVIEW

**Comment by samwalls-arm** [comment]
The clang pipeline in Travis (and my local machine, testing out clang instead of gcc) is failing because of errors such as:
```
[  6%] Built target gtest
[ 11%] Built target VkLayer_utils
[ 11%] Built target VkLayer_device_profile_api-json
[ 16%] Built target VkLayer_device_profile_api
[ 20%] Built target gtest_main
Scanning dependencies of target VkLayer_khronos_validation
[ 25%] Building CXX object layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/best_practices.cpp.o
[ 25%] Building CXX object layers/CMakeFiles/VkLayer_khronos_validation.dir/best_practices_utils.cpp.o
[ 25%] Building CXX object layers/CMakeFiles/VkLayer_khronos_validation.dir/generated/chassis.cpp.o
In file included from /home/sam/w/arm/Vulkan-ValidationLayers/layers/generated/best_practices.cpp:29:
In file included from /home/sam/w/arm/Vulkan-ValidationLayers/layers/best_practices_validation.h:312:
/home/sam/w/arm/Vulkan-ValidationLayers/layers/generated/best_practices.h:28:6: warning: 'PostCallRecordCreateInstance' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
void PostCallRecordCreateInstance(
     ^
/home/sam/w/arm/Vulkan-ValidationLayers/layers/generated/chassis.h:3133:22: note: overridden virtual function is here
        virtual void PostCallRecordCreateInstance(const VkInstanceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkInstance* pInstance, VkResult result) {};
                     ^
In file included from /home/sam/w/arm/Vulkan-ValidationLayers/layers/generated/best_practices.cpp:29:
In file included from /home/sam/w/arm/Vulkan-ValidationLayers/layers/best_practices_validation.h:312:
/home/sam/w/arm/Vulkan-ValidationLayers/layers/generated/best_practices.h:35:6: warning: 'PostCallRecordEnumeratePhysicalDevices' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
void PostCallRecordEnumeratePhysicalDevices(
     ^
/home/sam/w/arm/Vulkan-ValidationLayers/layers/state_tracker.h:669:10: note: overridden virtual function is here
    void PostCallRecordEnumeratePhysicalDevices(VkInstance instance, uint32_t* pPhysicalDeviceCount,
         ^
```
I'm not sure which change could cause this, as the compiler is complaining about functions from `layers/generated/best_practices.cpp` such as `PostCallRecordCreateInstance`. Any ideas?

Additionally, the windows CI build seems to be passing on Release but not Debug? I'm finding that this passes on my local windows setup.

**Comment by mark-lunarg** [comment]
@samwalls-arm, y'all have added an `override `qualifier to the declarations added to `best_practices_validation.h`.  These need to be removed.  For the windows builds, the issue probably isn't debug/release, but 64-bit/32-bit -- the failing Appveyor log ends with this:

> C:\projects\vulkan-validationlayers\external\googletest\googletest\include\gtest/gtest.h(1579): error C2220: warning treated as error - no 'object' file generated (compiling source file C:\projects\vulkan-validationlayers\tests\vklayertests_best_practices.cpp) [C:\projects\vulkan-validationlayers\build\tests\vk_layer_validation_tests.vcxproj]
> C:\projects\vulkan-validationlayers\external\googletest\googletest\include\gtest/gtest.h(1579): warning C4018: '>=': signed/unsigned mismatch (compiling source file C:\projects\vulkan-validationlayers\tests\vklayertests_best_practices.cpp) [C:\projects\vulkan-validationlayers\build\tests\vk_layer_validation_tests.vcxproj]

I'm guessing that fixing it will take care of your problem.

**Comment by samwalls-arm** [comment]
@mark-lunarg good spot. The error output was a bit misleading there, but that makes sense. Everything seems to be working now.

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by mark-lunarg** [comment]
@samwalls-arm, hey, I'm going to defer this PR for the time being -- if we get the time to drive on this later we can reopen it or create a new PR.  Thanks!

**Pull request closed without merging**
