### PR TITLE
layers: Add ability to disable image layout validation

### PR DESCRIPTION
**Pull request by mattruschnv**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Hey @mattruschnv, is it OK with you if I change the name of the disable from `image_layout `to `image_layout_validation` or maybe `image_layout_checks`?  "image_layout" already shows up in over a hundred other spots, and this would make searches easier.  Lemme know.

**Comment by mattruschnv** [comment]
Fine by me. I originally had it as image_layout_validation but changed it to make it consistent with (most of) the other disables.

**Comment by mark-lunarg** [comment]
Rebased, changed var name, squashed, and running through the farm.

**Comment by mark-lunarg** [comment]
Ran clean on the farm.  Thanks @mattruschnv.

**Pull request closed without merging**
