### PR TITLE
[WIP] build: Use FetchContent to grab dependencies

### PR DESCRIPTION
**Pull request by ncesario-lunarg**
FYI @lunarpapillo @charles-lunarg @mikes-lunarg

This effectively removes `update_deps.py` and adds a "known_good.cmake" to track required repo versions. This is more an RFC for gathering input as to what sort of effect this would have downstream.

### CODE REVIEW

**Comment by charles-lunarg** [comment]
A couple of thoughts about the transition period. Fetch content allows the specification of where the source gets downloaded to. By default its in `build/_deps` but we could make it live in `external`. This could be coupled with using fetch content as a 'fallback', as either a DEPENDENCY_INSTALL build option or another mechanism is checked before fetch content runs.
For example, in vk-bootstrap I made it so that a specific headers directory could be provided then it tries to use `find_package()` and finally uses fetch content if neither were successful.
https://github.com/charles-lunarg/vk-bootstrap/blob/5140be1d4da479b4d15b075c8951a07ee75eb2b3/CMakeLists.txt#L8

**Comment by ncesario-lunarg** [comment]
@charles-lunarg my initial thought for the `FetchRepo` function is something along the lines of:
```cmake
if (NOT (TARGET dependency))
  find_package(dependency)
  if (NOT dependency_FOUND)
    FetchContent ...
  endif()
endif()
```

The problem with `find_package` that I can see is that all repos need to be "relatively good" about export targets, and I'm not sure that's the case. Something we should work towards, but I don't think it can be relied on at the moment (though hopefully I'm wrong about that).

I would very much _not_ want to support multiple methods for fetching content. i.e., I would advocate for either sticking with `update_deps.py` (though move calling it to inside cmake for all repos) _or_ using FetchContent, but maintaining both is something I'd like to avoid.

**Comment by charles-lunarg** [comment]
@ncesario-lunarg Had an offline disscussion with nate, found that by default/using specific methods FetchContent de-duplicates the gotten repositories for us automatically. This removes a lot of the concern over versioning since there are rules about letting the highest project deciding the version dependencies will be.

**Comment by ncesario-lunarg** [comment]
After thinking about this a bit more (and due to concerns that @lunarpapillo has brought up w.r.t. building the SDK), I think a precursor to this change should probably be making sure all ecosystem repos "properly" install cmake targets (something I'll do as time permits). That would allow the SDK to effectively "install" all dependencies (as `update_deps.py` currently does) and repos can then use `FetchContent` only if `find_package` fails, but still use "proper cmake" to link to dependencies (rather than manually specifying and searching for file paths).

**Comment by charles-lunarg** [comment]
I went to the CppCon 2021 conference, where several talks about CMake & packaging were presented such as this talk https://www.youtube.com/watch?v=IZXNsim9TWI&list=PLHTh1InhhwT6vjwMy3RG5Tnahw0G9qIx6&index=43

I think the talk has some salient points about what is and isn't important for proper 'packaging' of the repo's.

**Comment by ncesario-lunarg** [comment]
Thanks for the reference @charles-lunarg! I'll give that a watch when I get a chance.

**Comment by juan-lunarg** [comment]
While FetchContent has numerous advantages the cons are numerous.
- Performance
- Requires projects absorbed to practice modern CMake
- Won't work particularly well with Android/BUILD.gn

**Pull request closed without merging**
