### PR TITLE
layers: Remove unnecessary FDM tiling check

### PR DESCRIPTION
**Pull request by neelbedekar**
Currently, the validation layers check for VUID 02084 in 2 spots, one
for images with usage VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV and one
for VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT. However, VUID 02084
only applies to VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV, not FDM,
so this check can be removed for the FDM path.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
LGTM, running through CI.  The travis failures are spurious.

**Comment by mark-lunarg** [comment]
@neelbedekar, can you click through the CLA, please?

**Comment by neelbedekar** [comment]
@mark-lunarg I'm not sure why it's showing up as unsuccessful. When I click the CLA link, I see the following:
image
Seems like it's already signed.

**Comment by mark-lunarg** [comment]
@neelbedekar, can you hit the 'recheck' link in the help-blurb just after the CLA-Not Signed Yet paragraph?  Perhaps you need to add your commit ID email to your Github account?

**Comment by neelbedekar** [comment]
@mark-lunarg it looks like my commits did not have an email associated with them, which was the root of this issue. I think I'm best off creating another PR, now that I've properly linked the email to future commits.

**Pull request closed without merging**
