### PR TITLE
build: Fix Vulkan header/registry detection for SDK

### PR DESCRIPTION
**Pull request by maltekliemann**
When trying to find the Vulkan headers/registry from the SDK, `FindVulkanHeaders` incorrectly sets `VULKAN_HEADERS_INSTALL_DIR` to `$ENV{VULKAN_SDK}/include` instead of `$ENV{VULKAN_SDK}`, resulting in `VulkanHeaders_INCLUDE_DIR` (resp. `VulkanRegistry_DIR`) to receive the incorrect hint `$ENV{VULKAN_SDK}/include/include` (resp. `$ENV{VULKAN_SDK}/include/share/vulkan/registry`).

The problem is fixed by setting `VULKAN_HEADERS_INSTALL_DIR` to `$ENV{VULKAN_SDK}` instead.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@shannon-lunarg, this sounds sdk-ish, not sure who'd be the best person for this -- likely you or maybe @richard-lunarg?

**Comment by maltekliemann** [comment]
@richard-lunarg Thanks for responding!

> @mark-lunarg @shannon-lunarg On the surface this looks like the ValidationLayers repo will not build if the VULKAN_SDK path is set. I've never built with that environment variable set, so I just did a fresh get, set the environment variable:
> 
> D:\LunarG\Vulkan-ValidationLayers\build>echo %VULKAN_SDK%
> d:\VulkanSDK\1.2.154.1
> 
> and built the repository. I'm very new to cmake, but I can build with or without VULKAN_SDK set, so I'm not sure what the issue is here. Someone with more clarity and experience with build issues should probably take a look.

Are you sure you're not overriding the use of `VULKAN_SDK` by using a the `DVULKAN_HEADERS_INSTALL_DIR` directive?

**Comment by maltekliemann** [comment]
Looking back at the pull request, I realize that I've not provided enough information. Here's a clearer description of the problem: If I run

```
mkdir -p build
cd build
cmake ..
```

with `VULKAN_SDK` set to `$HOME/vulkansdk-macos-1.2.154.0/macOS`, I get:

```
Could NOT find VulkanHeaders (missing: VulkanHeaders_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindVulkanHeaders.cmake:79 (find_package_handle_standard_args)
  CMakeLists.txt:53 (find_package)

-- Configuring incomplete, errors occurred!
```

Here's what I think is wrong:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/b26cd01260d767a2fff124ba464006652a41fd6d/cmake/FindVulkanHeaders.cmake#L41-L73

Judging by lines 59-66, `VULKAN_HEADERS_INSTALL_DIR` must be set to the install directory of Vulkan-Headers in the SDK, where `include/` and `share/` are found (so that the variables `VulkanHeaders_INCLUDE_DIR` and `VulkanRegistry_DIR` are correctly discovered. For macOS that's `/Users/.../vulkansdk-macos-1.2.154.0/macOS`, which is equal to the environment variable `VULKAN_SDK`. 

But in line 47, `VULKAN_HEADERS_INSTALL_DIR` is set to `$ENV{VULKAN_SDK}/include`. So now the `HINT` that `find_path` from lines 59-66 gets for `VulkanHeaders_INCLUDE_DIR` is `${VULKAN_HEADERS_INSTALL_DIR}`, which is $ENV{VULKAN_SDK}/include/include`. In the macOS case, this is `/Users/.../vulkansdk-macos-1.2.154.0/macOS/include/include`, which unsuprisingly doesn't exist.

That's why I think line 47 must be fixed in the way I suggested in the pull request.

**Comment by mark-lunarg** [comment]
@maltekliemann, thanks very much for the extra information.  We'll let @jeremyk-lunarg, our MacOS guru have a look.

**Comment by maltekliemann** [comment]
@mark-lunarg, sounds good, although I don't think this is a macOS specific problem. I see a similar problem under Linux, where `VULKAN_SDK` must be `/path/to/1.2.154/x86_64`.

**Comment by jeremyk-lunarg** [comment]
Passing local CI.  LGTM

**Comment by richard-lunarg** [comment]
I did try rebuilding on macOS with VULKAN_SDK set and it worked with the above instructions too. I used:
source setup-env.sh from the SDK.

So... I did not realize fully how you were trying to build until now as well, so it looks like all is well with this.

**Comment by maltekliemann** [comment]
@richard-lunarg By "above instructions" you mean the following, right?
```
mkdir build
cd build
../scripts/update_deps.py
cmake -C helper.cmake ..
cmake --build .
```
In that case, I don't think you're using the SDK, as the Vulkan-Header path defined in `helper.cmake` take precedence over the one deduced from `VULKAN_SDK`.

When I try to build against the SDK headers, I get a wall of compiler errors.

**Pull request merged**
