### PR TITLE
layers: fix acessmask to pipeline state mapping

### PR DESCRIPTION
**Pull request by souravpNV**
fixed as per spec

### CODE REVIEW

**Comment by souravpNV** [comment]
@dgkoch @mark-lunarg for review

**Review by dgkoch — APPROVED** [review]
LGTM

**Comment by mark-lunarg** [comment]
LGTM, Running through CI.  @souravpNV, you just need to make Travis CI happy.

**Comment by souravpNV** [comment]
@mark-lunarg Looks like Travis is happy :)

**Comment by mark-lunarg** [comment]
Thank you very much @souravpNV, for Travis and for the super-quick turnaround.

**Pull request merged**
