### PR TITLE
tests: Test creation with VkAllocationCallbacks

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Hey @krOoze, this is failing on Android platforms in the test farm.  I'll try to get some more details in the next day or two.

**Comment by krOoze** [comment]
@mark-lunarg I have to offten clean VS Solution (and sometimes delete whole `build` directory). There might be some problems in build dependencies...

Anyway, rebased of master. Might help too...

**Comment by locke-lunarg** [comment]
@krOoze  The test structure changed. Please move `VkLayerTest, InvalidAllocationCallbacks` from `layer_validation_tests.cpp` into `vklayertests_command.cpp`.

**Comment by krOoze** [comment]
Done. Seems to fit more in `vklayertests_others.cpp`. Command pool in the test is just chosen arbitrarily.

**Comment by mark-lunarg** [comment]
Passed CI.  Thanks Petr!

**Pull request merged**
