### PR TITLE
layers: Add support for OpenBSD

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
LGTM! Just a few things to make CI happy:
1. Update the copyright in [vk_loader_platform.h](https://github.com/KhronosGroup/Vulkan-ValidationLayers/runs/8102804760?check_suite_focus=true#step:4:16)
2. Sign the CLA
3. Change the label in the commit subject line from `layers` to `build` (technically not needed for CI, but good for consistency with other commits like this)

**Comment by brad0** [comment]
1. Do I update the copyright in the same manner as the commit below?
2. I already did.
3. I used `layers` as I took inpiration from this commit.. https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/d360374f4cbcd890f6379041834098d32dd756c4

**Comment by ncesario-lunarg** [comment]
> 1. Do I update the copyright in the same manner as the commit below?

Yep! Just update the year for each copyright please.

> 2. I already did.

:+1:

> 3. I used `layers` as I took inpiration from this commit.. [d360374](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/d360374f4cbcd890f6379041834098d32dd756c4)

Yeah, `layers` or `build` is fine here. At first glance I thought this was only changing build scripts, but it doesn't touch any any build scripts :)

**Comment by brad0** [comment]
ping.

**Pull request merged**
