### PR TITLE
Add acceleration structure tracking and validation

### PR DESCRIPTION
**Pull request by jmacnak-nv**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@jmacnak-nv, we'll eventually need to squash some of these commits -- ideally, the repo should build and pass all tests for each individual commit.  Doesn't need to be done until the last minute and I can take care of it if necessary.  Thanks!

**Comment by jmacnak-nv** [comment]
Squashed the commits. Looking into the test failures now.

**Comment by mark-lunarg** [comment]
LGTM, running through CI.

**Comment by jmacnak-nv** [comment]
(for history, needed to disable the tests on MockICD and DeviceSimulation)

**Comment by jmacnak-nv** [comment]
(re-basing after the codegen and vst changes)

**Comment by mark-lunarg** [comment]
CI was happy, shortened commit messages and pushed to Master.  Thanks @jmacnak-nv...

**Pull request closed without merging**
