### PR TITLE
layers: Fix deadlock triggered by queries updated in secondary command buffers.

### PR DESCRIPTION
**Pull request by akeley98NV**
Fix for #7874

### CODE REVIEW

**Review by spencer-lunarg — APPROVED** [review]
@akeley98NV thanks for the fix (and tests)

1. You need to run `clang-format` as CI is mad about it https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/8775393117/job/24077674023?pr=7880

2. @artem-lunarg I would like to get your review on this as well

**Comment by akeley98NV** [comment]
Yeah it's mad because my TEST_DESCRIPTION is too long, is it acceptable to split it across 2 lines? (Some projects don't like this as it breaks grepability). Or suggestion for a shorter description?

**Comment by spencer-lunarg** [comment]
> Yeah it's mad because my TEST_DESCRIPTION is too long, is it acceptable to split it across 2 lines? (Some projects don't like this as it breaks grepability). Or suggestion for a shorter description?

It is ok, we have `clang-format` to enforce this, the description is normally used when someone fails the test or has to debug it... so a 2nd line is totally ok!

**Review by arno-lunarg — APPROVED** [review]

**Comment by artem-lunarg** [comment]
@akeley98NV Thanks for the detailed analysis that shows the problem. I updated the test a little bit. Made it positive since we do not try to reproduce some VU error, and also used the existing helpers to make it smaller. Could you please remove the existing test from `query.cpp` and put the following updated version into a different file `query_positive.cpp`. I tested it on windows, it hangs with original code (no crash with windows runtime but a deadlock) and works with your fix.

```

// https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7874
TEST_F(PositiveQuery, ReuseSecondaryWithQueryCommand) {
    TEST_DESCRIPTION("Regression test for a deadlock when secondary command buffer is reused and records a query command");

    RETURN_IF_SKIP(Init());
    if (HasZeroTimestampValidBits()) {
        GTEST_SKIP() << "Device graphic queue has timestampValidBits of 0, skipping.";
    }

    vkt::QueryPool query_pool(*m_device, VK_QUERY_TYPE_TIMESTAMP, 1);

    vkt::CommandBuffer secondary_buffer(*m_device, m_commandPool, VK_COMMAND_BUFFER_LEVEL_SECONDARY);
    secondary_buffer.begin(VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT);
    vk::CmdWriteTimestamp(secondary_buffer.handle(), VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT, query_pool, 0);
    secondary_buffer.end();

    m_commandBuffer->begin(VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT);
    vk::CmdResetQueryPool(m_commandBuffer->handle(), query_pool, 0, 1);
    vk::CmdExecuteCommands(m_commandBuffer->handle(), 1, &secondary_buffer.handle());
    m_commandBuffer->end();

    m_default_queue->submit(*m_commandBuffer);

    // Submit the command buffer again, making query pool in use and invalid to destroy
    m_default_queue->submit(*m_commandBuffer);

    m_default_queue->wait();
}
```

**Comment by artem-lunarg** [comment]
I'd like to suggest a one line fix (https://github.com/artem-lunarg/Vulkan-ValidationLayers/commit/3dcbec707095a36c567ae4a3a530106cd7bfc7ed) (cc @jeremyg-lunarg).

Current vvl has this function:
```
bool CommandBuffer::UpdatesQuery(const QueryObject &query_obj) const {
    // Clear out the perf_pass from the caller because it isn't known when the command buffer is recorded.
    auto key = query_obj;
    key.perf_pass = 0;
    for (auto *sub_cb : linkedCommandBuffers) {
        auto guard = sub_cb->ReadLock();
        if (sub_cb->updatedQueries.find(key) != sub_cb->updatedQueries.end()) {
            return true;
        }
    }
    // !! No lock for  THIS command buffer while accessing the following updatedQueries. !!
    return updatedQueries.find(key) != updatedQueries.end(); 
}
```

We do lock the secondary command buffers but we do not lock *this* command buffer. *this* command buffer is a primary command buffer from one of the subsequent submissions (not from the current one that is being retired). I can speculate that the reason we do not lock it is because we assume that command buffers can not be modified while *pending* and probably we have validation for that, this code might rely on that assumption.

The part that locks secondary command buffer was added separately here (SHA=221bb37645c72db356277aa1353af4e07a75b677), my best guess it was added with the best intention to make code safer but it's not clear if there was an actual race (@jeremyg-lunarg do you have insights?).

My suggestion is to tread secondary command buffer the same way we tread primary command buffers and remove the line with a lock. This passes new regression test. If any issues we then we still need a different fix which also fixes access to *this* command buffer since it is also not locked.

**Comment by akeley98NV** [comment]
If the maintainers think the original problematic lock can be removed, I'm certainly happy to have that change accepted instead of this one.

**Review by jeremyg-lunarg — APPROVED** [review]

**Comment by jeremyg-lunarg** [comment]
I think either the solution in this PR or removing the sub cb locks as @artem-lunarg proposes are equivalent.  Really though the query state tracking code is in sorry state and needs some rethinking.

**Comment by artem-lunarg** [comment]
I discussed this more with @jeremyg-lunarg and one of the goals is to to prevent crashes if external synchronization is violated (correctness is secondary then), in this regard removing lock might be unsafe. On the other hand we also don't have the lock for the primary command buffer (both approaches fix the issue but the external synchronization is also not handled ideally). I'll try to analyze this more during the week.

**Comment by artem-lunarg** [comment]
Going to proceed with https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7909. @akeley98NV thanks for the help with this issue.

**Comment by akeley98NV** [comment]
Sounds good, thanks!

**Pull request closed without merging**
