### PR TITLE
Move VkPerformanceConfigurationINTEL validation to be auto generated

### PR DESCRIPTION
**Pull request by djdeath**
The update of Vulkan-Headers 1.2.152 (ced848d699b567), added a fix for
a couple of VK_INTEL_performance_query entrypoints in vk.xml.

It makes sense to move more validation to automation so that we can get
those checks for free.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@djdeath, looks like at least some of the failures are because the generators and source don't match, and there are some changes to `vk_validation_error_messages.h` which shouldn't normally happen -- maybe `update_deps.py` should be re-run?

**Comment by djdeath** [comment]
Woops... indeed missing a known_good.json update.

**Comment by mark-lunarg** [comment]
@djdeath, a quick question.  I'm trying to add some additional Query validation (to address #2029) but can't seem to find any hardware that supports performance queries to the point of featuring performanceCounterQueryPools.  Can you share what platform you used for testing?  And, if I get the new PR together, would you mind having a look at it at all?  Thanks!

**Comment by mark-lunarg** [comment]
BTW, waiting for 152 (or greater) header version to land in this repo...

**Comment by djdeath** [comment]
> @djdeath, a quick question. I'm trying to add some additional Query validation (to address #2029) but can't seem to find any hardware that supports performance queries to the point of featuring performanceCounterQueryPools. Can you share what platform you used for testing? And, if I get the new PR together, would you mind having a look at it at all? Thanks!

We started shipping the KHR_performance_query extension on the Mesa 20.2 branch (still in RC at this point but you can find it packaged for Ubuntu on https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers).

In term of hardware you need a Broadwell processor or more recent (anything >= i3/5/7-5000) which is also the starting platform for CTS conformance.

And sure I can test a branch if you have one.

**Comment by mark-lunarg** [comment]
Running through CI.

**Review by mark-lunarg — APPROVED** [review]

**Comment by mark-lunarg** [comment]
Rebased, ran through CI, updated commit message and pushed to master.  Thanks!

**Pull request closed without merging**
