### PR TITLE
build: Fix duplicate xxhash object files

### PR DESCRIPTION
**Pull request by juan-lunarg**
Currently both VkLayer_utils and VVL build xxhash.c which results in duplicate identical object files. Now VkLayer_utils is responsible for the xxhash object file.

Also turn xxhash.c to xxhash.cpp to avoid mixed language usage in a single library. This helps avoid minor confusions in the CMake code.

### CODE REVIEW

**Comment by juan-lunarg** [comment]
Example ninja build output from before this change:

```sh
Building C object layers/CMakeFiles/VkLayer_utils.dir/xxhash.c.o
...
Building C object layers/CMakeFiles/VkLayer_khronos_validation.dir/xxhash.c.o
```

Now it looks like this:

```sh
Building CXX object layers/CMakeFiles/VkLayer_utils.dir/xxhash.cpp.o
```

**Review by ncesario-lunarg — APPROVED** [review]
Would creating a static library/target containing xxhash.c[pp] and linking against that work? If we have multiple targets that depend on xxhash, seems like they should each "depend" on xxhash. That's _assuming_ cmake has the smarts to not bring in the xxhash target/lib twice when linking the .so.

**Comment by juan-lunarg** [comment]
> Would creating a static library/target containing xxhash.c[pp] and linking against that work?

I tried that approach but it doesn't work cleanly due to the fact we have to install `VkLayer_utils` which `LunarG/VulkanTools` depends on.

**Comment by ncesario-lunarg** [comment]
> > Would creating a static library/target containing xxhash.c[pp] and linking against that work?
> 
> I tried that approach but it doesn't work cleanly due to the fact we have to install `VkLayer_utils` which `LunarG/VulkanTools` depends on.

Ah yes, another "TODO" :/

**Pull request merged**
