### PR TITLE
build: Update known-good files for 1.2.135 header [WIP]

### PR DESCRIPTION
**Pull request by shannon-lunarg**
Changes:
- Updated known-good files
- Generated new files using `generate_source.py`

### CODE REVIEW

**Comment by jeffbolznv** [comment]
```
jni/../third_party/Vulkan-Tools/common/vulkan_wrapper.cpp:655:1: error: unknown type name 'PFN_vkCmdProcessCommandsNVX'; did you mean 'PFN_vkCmdExecuteCommands'?

PFN_vkCmdProcessCommandsNVX vkCmdProcessCommandsNVX;

^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This NVX extension was removed in this header update. Does Vulkan-Tools need to be updated first?

**Comment by shannon-lunarg** [comment]
@jeffbolznv Yes, it does seem Vulkan-Tools known-good needs to be addressed first. I have that running through LunarG internal CI right now and have created a PR here: https://github.com/KhronosGroup/Vulkan-Tools/pull/353

**Comment by mark-lunarg** [comment]
Rebased on Master.

**Comment by mark-lunarg** [comment]
Rebased and pushed to Master.

**Pull request closed without merging**
