### PR TITLE
layers: Fix vkUpdateDescriptorSetWithTemplate crash

### PR DESCRIPTION
**Pull request by souravpNV**
add state tracker for acceleration structure when updated using
vkUpdateDescriptorSetWithTemplate

### CODE REVIEW

**Comment by souravpNV** [comment]
@mark-lunarg : Getting this "layers/descriptor_sets.h has an out-of-date copyright notice."
Do you know how to fix that?
@dgkoch  for review.

**Review by dgkoch — COMMENTED** [review]
I'm not really familiar with this area of the layers, but it looks reasonable to me.

**Comment by ncesario-lunarg** [comment]
> ... Getting this "layers/descriptor_sets.h has an out-of-date copyright notice."
@souravpNV changing all of the "2015-2020" -> "2015-2021" should fix the copyright check.

As for the linux builds, it looks like maybe the mock ICD test run is failing, but I don't know why that would be happening.

**Comment by souravpNV** [comment]
> > ... Getting this "layers/descriptor_sets.h has an out-of-date copyright notice."
> > @souravpNV changing all of the "2015-2020" -> "2015-2021" should fix the copyright check.
>  Thanks that worked
> As for the linux builds, it looks like maybe the mock ICD test run is failing, but I don't know why that would be happening.
Even I am not sure about that, I don't have a Linux build to debug it.

**Comment by souravpNV** [comment]
@ncesario-lunarg , mock icd tests were failing because I didn't update the layer_chassis_dispatch_generator.py
 and instead made changes to layer_chassis_dispatch.cpp directly, fixing that all checks are passing now.

**Comment by ncesario-lunarg** [comment]
Awesome, nice catch @souravpNV!

@mark-lunarg this change LGTM and is running through [internal CI](http://erusea:4040/8190), but just an FYI as I also don't have a lot of experience in with this.

**Review by ncesario-lunarg — APPROVED** [review]

**Review by mark-lunarg — APPROVED** [review]

**Pull request merged**
