### PR TITLE
layers: Add missing RayTracing KHR alias struct

### PR DESCRIPTION
**Pull request by sfricke-samsung**
From https://github.com/KhronosGroup/Vulkan-Docs/issues/1433

Simple fix and only spot I found with similar issue

cc @dgkoch

### CODE REVIEW

**Review by dgkoch — APPROVED** [review]
LGTM

cc @souravpNV  as well.

**Comment by souravpNV** [comment]
LGTM2

**Comment by ncesario-lunarg** [comment]
Running through [internal CI](http://erusea:4040/8234).

**Review by ncesario-lunarg — APPROVED** [review]
LGTM; just waiting for internal CI to finish.

**Pull request merged**
