### PR TITLE
layers: Add missing 'override' keyword.

### LINKED ISSUE #2419: compiler style warning: inconsistent-missing-override
Example failure:

```
../../third_party/vulkan-deps/vulkan-validation-layers/src/layers\stateless_validation.h(1512,10): error: 'PreCallValidateGetDeviceGroupSurfacePresentModes2EXT' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    bool PreCallValidateGetDeviceGroupSurfacePresentModes2EXT(VkDevice device, const VkPhysicalDeviceSurfaceInfo2KHR *pSurfaceInfo,
         ^
../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/generated\chassis.h(4412,22): note: overridden virtual function is here
        virtual bool PreCallValidateGetDeviceGroupSurfacePresentModes2EXT(VkDevice device, const VkPhysicalDeviceSurfaceInfo2KHR* pSurfaceInfo, VkDeviceGroupPresentModeFlagsKHR* pModes) const { return false; };
                     ^
1 error generated.
```

This is popping up in the Chromium integration. We turn on a lot of additional compiler warnings and use -Werror. I'll submit a CL to disable this specific warning in GN. If the VVL maintainers would like to enforce this style that would involve fixing the code generation and turning this warning on in your presubmit.

Context: https://chromium-review.googlesource.com/c/chromium/src/+/2595260

### PR DESCRIPTION
**Pull request by null77**
Fixes #2419

@mark-lunarg PTAL

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
Thanks for this @null77! If you can [remove the period](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2425/checks?check_run_id=1597041941#step:4:14) from the end of the commit message, I think this should be good. I'm running this through our internal CI now.

**Comment by null77** [comment]
> Thanks for this @null77! If you can [remove the period](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2425/checks?check_run_id=1597041941#step:4:14) from the end of the commit message, I think this should be good. I'm running this through our internal CI now.

Done

**Comment by mark-lunarg** [comment]
@null77, thanks for fixing this for us.  If you see this again, let us know and we'll look into adding another Windows build to CI.

**Comment by mark-lunarg** [comment]
Thanks @ncesario-lunarg!

**Pull request merged**
