### PR TITLE
Update LICENSE.txt

### PR DESCRIPTION
**Pull request by ben-clayton**
Include BSD license used in `layers/external/vma/vk_mem_alloc.h`

### CODE REVIEW

**Comment by ben-clayton** [comment]
Required to make Google's license checking bots happy

**Comment by juan-lunarg** [comment]
I don't know enough about licensing to be useful here.

Pinging @KarenGhavam-lunarG and @KhronosWebservices

**Review by dneto0 — COMMENTED** [review]
Right. This will be necessary, since AMD's VMA code was copied into this repo.

(I was surprised to see that, but I don't know all the reasons, and it's not up to me.)

**Comment by juan-lunarg** [comment]
> (I was surprised to see that, but I don't know all the reasons, and it's not up to me.)

TLDR: The chromium build, system package managers, and the current android build.

**Review by juan-lunarg — DISMISSED** [review]

**Comment by KarenGhavam-lunarG** [comment]
> Pinging @KarenGhavam-lunarG and @KhronosWebservices

No concerns here. This fix is correct. We need to detail the licenses in use in this repository.

**Comment by outofcontrol** [comment]
The only concern I can think of is that we don't have a CLA for the BSD, so accepting changes to the file is problematic. Is it possible for AMD to accept a license change to Apache 2.0? Might be good also to get reuse setup to ensure we are tracking the copyright and license across all files in this repository.

**Comment by KarenGhavam-lunarG** [comment]
>  Is it possible for AMD to accept a license change to Apache 2.0?

This would be problematic. And most likely this is not the only file/license beyond Apache 2.0 in the repository

> Might be good also to get reuse setup to ensure we are tracking the copyright and license across all files in this repository.

I am unfamiliar with reuse and what the implications of this would be.

**Comment by KarenGhavam-lunarG** [comment]
IMHO, the questions about the CLA and reuse should not hold up merging of this PR. Rather a separate issue can be logged regarding these questions. This is due to the fact that there are other 3rd party files in this repository with licenses that are not Apache 2.0 (as noted in the license.txt file) and the questions around the CLA and reuse are not new or introduced by this PR.

**Comment by outofcontrol** [comment]
> IMHO, the questions about the CLA and reuse should not hold up merging of this PR.

Agree.

**Review by juan-lunarg — APPROVED** [review]

**Comment by ben-clayton** [comment]
Many thanks

**Pull request merged**
