### PR TITLE
Add renderpass compatibility checks and tests for FDM and Multiview use

### PR DESCRIPTION
**Pull request by jorgep31415**
Fixes issue #1568, and contains tests for these fixes.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
This looks great!  Running through the test farm...

**Comment by jorgep31415** [comment]
Had to make a minor wording correction to the 2 test descriptions.

**Comment by mark-lunarg** [comment]
@jorgep31415, just ignore the Appveyor failure, it's just an aberration.

**Comment by mark-lunarg** [comment]
Shortened the commit subject lines a bit, rebased, and pushed to Master.  Excellent!

**Pull request closed without merging**
