### PR TITLE
layers: Add fragment density map imageless size checks

### PR DESCRIPTION
**Pull request by r-potter**
New checks for:

* VUID-VkFramebufferCreateInfo-flags-03196
* VUID-VkFramebufferCreateInfo-flags-03197

### CODE REVIEW

**Review by artem-lunarg — APPROVED** [review]
LGTM

**Comment by artem-lunarg** [comment]
@r-potter thanks for the density map checks. Could you rebase and resolve potential conflicts, then I will get this in.

**Comment by artem-lunarg** [comment]
It's also preferable to follow the convention to have separate commits for validation and test code.

**Comment by r-potter** [comment]
Thanks @artem-lunarg. Should now all be rebased and the commit split in two

**Pull request merged**
