### PR TITLE
Adjust Apache reference to be more standard

### PR DESCRIPTION
**Pull request by Hixie**
layers: Looks like when the generator was written, the Valve copyright was
accidentally put in a weird place. This adjusts these files to match the rest of the repo.

### CODE REVIEW

**Review by ncesario-lunarg — COMMENTED** [review]
@Hixie since these files have now been updated this year, the copyright also needs to get updated from 2017 to 2022. Otherwise this LGTM!

**Comment by juan-lunarg** [comment]
```
ERROR: Repo files do not match generator output for enum_flag_bits.h
```

@Hixie you'll need to run the code generation locally and then re-base and force push to fix the CI errors.

Here are the instructions for running the code generation:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/generated_code.md

**Comment by juan-lunarg** [comment]
Hope you don't mind @Hixie but I went ahead and fixed the remaining issue with `enum_flag_bits.h` :+1:

**Review by juan-lunarg — APPROVED** [review]

**Comment by Hixie** [comment]
@juan-lunarg oh awesome, thanks! I was planning on getting to it but was busy with other stuff.

**Pull request merged**
