### PR TITLE
build: Update to header 1.3.214

### PR DESCRIPTION
**Pull request by mikes-lunarg**
- Update known-good
- Generate source
- Add descriptor_validation.cpp to stats script

### CODE REVIEW

**Comment by mikes-lunarg** [comment]
I opened a separate issue necessary VUID changes: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4124

**Review by ncesario-lunarg — APPROVED** [review]
LGTM, though I'm not sure why `VkLayerTest.DynamicRenderingDepthFormatAndResolveMode` is crashing on nvidia (that's the only HW + driver we currently have that supports that test).

**Comment by mikes-lunarg** [comment]
> I'm not sure why `VkLayerTest.DynamicRenderingDepthFormatAndResolveMode` is crashing on nvidia (that's the only HW + driver we currently have that supports that test).

I see a similar crash on my linux nvidia system too, I'll do a little digging

**Comment by mikes-lunarg** [comment]
Mystery solved, I pushed a new commit:

> VK_KHR_depth_stencil_resolve is now a required dependency for VK_KHR_dynamic_rendering, making VUID-VkRenderingAttachmentInfo-imageView-06131 impossible to hit without also violating the extension dependency rules.

I'll also follow up with the WG to get that VUID removed

**Comment by ncesario-lunarg** [comment]
Awesome, thanks!

**Pull request merged**
