### PR TITLE
Add validation for VK_AMD_device_coherent_memory

### PR DESCRIPTION
**Pull request by Tobski**
Also adds the other two VUIDs for vkAllocateMemory, given that one of them was a necessary intermediate step and the other was easy.

### CODE REVIEW

**Comment by Tobski** [comment]
@mark-lunarg Everything is building and running locally, but it seems like the test is running against devsim and finding a set of conditions that are unexpected by the specification; specifically that the extension is exposed, but no coherent memory types are exposed. I've just pushed a condition to test this hypothesis when running the test (which I expect to back out); it could possibly be a DevSim bug?

I'm not completely ruling out that I've fluffed something in the test, but I can't see it, so a second set of eyes would be appreciated 😅

**Comment by Tobski** [comment]
> I've just pushed a condition to test this hypothesis when running the test (which I expect to back out); it could possibly be a DevSim bug?

Ok yea, so that passes. If you check the logs for the test runs of the Linux builds you'll see:

> TEST SKIPPED: Invalid implementation, VK_AMD_device_coherent_memory exposed but fails to support required memory types

**Comment by Tobski** [comment]
(To be clear, please don't accept this MR, there's an underlying issue here that needs resolving AFAICT...)

**Comment by Tobski** [comment]
@mark-lunarg So looking at the test logs, it seems that the DevSim layer isn't hiding the AMD extensions of the underlying platform? This seems like a pretty weird omission? Other tests requiring AMD-specific extensions are running quite happily no matter which test is profile is active...

**Comment by mark-lunarg** [comment]
Lemme run it through the test farm to get a better idea of what's really going on.

**Comment by mark-lunarg** [comment]
@tobski, it's fine on the farm. I'm taking a look at the MockICD failures and will suggest a workaround.

**Comment by mark-lunarg** [comment]
Hey @Tobski, it looks like this particular test is failing due to a quirk of the Mock ICD.  It has to advertise support for all extensions but doesn't also implement the underlying assumptions such as the associated memory type.  In these cases, likely the best solution is to exclude this test from running on the test ICD by adding something similar to this near the start of the test:

```
if (DeviceIsMockICD() || DeviceSimulation()) {
    printf("%s MockICD does not support the necessary memory type, skipping test\n", kSkipPrefix);
    return;
}
```

**Comment by mark-lunarg** [comment]
I'll go ahead and fix it.

**Comment by mark-lunarg** [comment]
Squashed fixes into the test commit and pushed to Master.

**Pull request closed without merging**
