### PR TITLE
tests: Fix minor video test framework issues

### PR DESCRIPTION
**Pull request by aqnuep**
This PR fixes some minor issues with the test framework for Vulkan Video tests found by valgrind and further review.

### CODE REVIEW

**Review by juan-lunarg — COMMENTED** [review]
While I have you here a have a question about the video code.

```
class VkVideoLayerTest : public VkLayerTest {
  protected:
    struct {
        PFN_vkGetPhysicalDeviceVideoCapabilitiesKHR GetPhysicalDeviceVideoCapabilitiesKHR;
        PFN_vkGetPhysicalDeviceVideoFormatPropertiesKHR GetPhysicalDeviceVideoFormatPropertiesKHR;
    } vk{};

    void Init(bool enable_protected_memory = false) {
        SetTargetApiVersion(VK_API_VERSION_1_1);
```

enable_protected_memory is never used in the init function and it doesn't seem intentional.

**Comment by juan-lunarg** [comment]
> This PR fixes some minor issues with the test framework for Vulkan Video tests found by valgrind and further review.

Have you tried using address sanitizer as well? I know it's a bit more robust than valgrind in certain areas.

`-D VVL_ENABLE_ASAN`

**Comment by aqnuep** [comment]
> enable_protected_memory is never used in the init function and it doesn't seem intentional.

Indeed, you're right. That's just a left-over of an (in the end) unnecessary parameter.

> Have you tried using address sanitizer as well? I know it's a bit more robust than valgrind in certain areas.

No, but I'll give it a try.

**Review by ncesario-lunarg — APPROVED** [review]

**Review by juan-lunarg — CHANGES_REQUESTED** [review]
Will approve once the `enable_protected_memory` issue is fixed.

**Comment by aqnuep** [comment]
> Will approve once the enable_protected_memory issue is fixed.

In the end I went back to using the flag to explicitly not enable protected memory, as it was originally designed to be handled.

It's actually good that you noted this one as I found a bug in one of the protected memory related test cases, which I also fixed.

Unfortunately, currently no Vulkan Video implementation supports protected content, so these test cases don't have the necessary coverage due to the tests being skipped.

**Review by juan-lunarg — APPROVED** [review]

**Review by juan-lunarg — APPROVED** [review]

**Pull request merged**
