### PR TITLE
build: Fix test build to use loader as imported target

### PR DESCRIPTION
**Pull request by nsubtil**
Updates the test build to consume the Vulkan loader as an imported
target in a nested project build. If the imported target is not found,
the existing logic and search path is used instead.

### CODE REVIEW

**Comment by nsubtil** [comment]
Tagging @mark-lunarg for a review

**Comment by mikew-lunarg** [comment]
Pushed to master at 81a839a10e41b851556a0cc0726bccdd21975c57

**Comment by shannon-lunarg** [comment]
The changes in this PR broke the build for anyone using the `-D` option to build ValidationLayers. This commit has been reverted on master until modifications have been made to accommodate this use case.

**Comment by mikew-lunarg** [comment]
@nsubtil Please revisit this change.

**Comment by nsubtil** [comment]
@shannon-lunarg can I get some more details on the use case that broke? A sample CMake command line would help.

**Comment by shannon-lunarg** [comment]
@nsubtil This is what I use:
```
cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Debug -DGLSLANG_INSTALL_DIR=/home/shannon/development/glslang/build/install -DVULKAN_HEADERS_INSTALL_DIR=/home/shannon/vulkan/Vulkan-Headers/build/install -DVULKAN_LOADER_INSTALL_DIR=/home/shannon/vulkan/Vulkan-Loader/build/install ..
```

**Comment by nsubtil** [comment]
Ok, I'll try to replicate that.

In the meantime, do you happen to have a build log that shows the failure? I think I know what it might be, but would be good to confirm.

**Comment by shannon-lunarg** [comment]
This is the extent of the output when I use that cmake command:
```
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.7", minimum required is "3") 
-- Using glslang install located at /home/shannon/development/glslang/build/install
-- Vulkan-ValidationLayers/external: googletest found - configuring it for tests
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.7") 
-- VULKAN_LOADER_INSTALL_DIR specified, using find_package to locate Vulkan
CMake Error at tests/CMakeLists.txt:106 (target_include_directories):
  Cannot specify include directories for imported target "vulkan".


-- Configuring incomplete, errors occurred!
See also "/home/shannon/vulkan/Vulkan-ValidationLayers/build/CMakeFiles/CMakeOutput.log".
See also "/home/shannon/vulkan/Vulkan-ValidationLayers/build/CMakeFiles/CMakeError.log".
Makefile:736: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
```

**Comment by nsubtil** [comment]
Yeah, that's what I suspected. This is version-dependent behavior in CMake, which I didn't catch early enough. We need to tweak this for CMake <= 3.10. I think this particular problem is easy to fix, but there may be others lurking.

Can you confirm which version of CMake you're on?

I think we never settled the discussion on standardizing the minimum CMake version requirement --- tagging @mikew-lunarg for visibility, as he had previously suggested standardizing on something a bit newer.

**Comment by mikew-lunarg** [comment]
@nsubtil   The CMake version recommendations have been bumped to v3.12.4 on Linux, v3.12.2 for Windows, leveraging the configuration of containers used for CI.  Those versions are described in the Getting_Started and Vulkan_Samples documents in the SDK.

**Comment by shannon-lunarg** [comment]
I am at cmake version 3.10.2. @mark-lunarg was experiencing similar build errors and I'm not sure which version of cmake he is using.

**Comment by mark-lunarg** [comment]
Was using 3.8.0-rc1.

**Comment by nsubtil** [comment]
Do we intend to continue supporting CMake versions earlier than 3.12?

**Comment by mikew-lunarg** [comment]
I'm thinking this may be the juncture at which we begin enforcing the 3.12
minimum.
@Shannon McPherson <shannon@lunarg.com> Can I ask you to upgrade your CMake
to the recommended version and retest?
I personally use v3.12.4 across all platforms.

**Comment by mark-lunarg** [comment]
The current minimum versions are pegged to the last two LTS versions of Ubuntu that we have to support (was that 3.5-something?) and those folks don't have an easy way to get to newer cmake versions.  Is there a way to avoid using the new-to-cmake-3.11 feature?

**Comment by lenny-lunarg** [comment]
I don't think it's at all reasonable to require CMake 3.12. That version appears to have released around the end of November 2018. As @mark-lunarg just said, we officially support the last two Ubuntu LTS releases, and 16.04 released with CMake 3.5. Given the pushback we've had in the past with regards to upgrading to tools that are 3-4 years old, I don't see how requiring a CMake version that's not even 6 months old is a good idea.

And I second @mark-lunarg's questions. Isn't there a way to make this work with CMake 3.5?

**Comment by nsubtil** [comment]
Not sure what tools you're referring to as far as earlier push back, but in the case of CMake, it's fairly trivial to run an arbitrary CMake version --- it's entirely self-contained (no system-wide installation required) and binaries are readily available. It's not like, say, compiler toolchain support, where using a different version may be an insurmountable problem due to interactions with third-party components.

The main problem I see here is that we need CI to ensure whatever versions of CMake we do support won't break. That doesn't seem to exist today, so it gets pretty tricky to make changes like these. It's not the first time that build changes are reverted after the fact due to similar situations, which isn't productive.

**Comment by mikew-lunarg** [comment]
All, let's please hold on CMake version discussions until it's better understood the exact factors contributing to inconsistent behavior of this PR.  I will leave this PR reverted until we have that understanding and a plan to move forward.

**Comment by nsubtil** [comment]
I'd rather not let a separate project get held up by the CMake version discussion. I'm continuing to look at what it takes to make CMake <= 3.10 work, assuming that's still an option.

**Comment by mikew-lunarg** [comment]
@nsubtil I look fwd to the results of your investigation.

**Comment by nsubtil** [comment]
Added a commit that does explicit CMake version checks around `target_include_directories()` on imported targets. This hopefully documents the behavior in the build script itself as explicitly as possible, and I'm hopeful we can simply remove the <= 3.11 path in the future.

@mikew-lunarg @shannon-lunarg can you give this a look?

**Comment by mark-lunarg** [comment]
Pinging @shannon-lunarg , @mikew-lunarg.  Now that the cmake hoops have been jumped through, is this PR now good-to-go?

**Comment by KarenGhavam-lunarG** [comment]
We have standardized on version 3.10.2 for Cmake. We still have not pushed that version of Cmake into the CI for this repository (there is an open pull request). I also believe this original pull request will not work with 3.10.2

**Comment by nsubtil** [comment]
This PR will work as-is, but is a bit uglier than necessary since it has effectively two paths in it. Should be reworked to include just the "old" path, as that is what will work with 3.10.2.

I don't think I'll have enough bandwidth to rebase / update this for at least the next two weeks, but I can follow up on this after that.

**Comment by mikew-lunarg** [comment]
Once PR #958 has been merged, then this pull request can be reworked to work with CMake version 3.10.2.
Since this PR needs rework, we're opting to close it and @nsubtil can submit a new one in the future.

**Pull request closed without merging**
