### PR TITLE
Fix some more compiler and static analysis warnings

### PR DESCRIPTION
**Pull request by krOoze**
Fix some more issues discovered by warnings in #1106

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Wow, third PR to fix the pNext init! Running through CI now.

**Comment by krOoze** [comment]
@mark-lunarg Sorry I have to append it to all my PRs, so tests won't crash. Please push **some** fix, and I will rebase on top of it.

**Comment by mark-lunarg** [comment]
@krOoze -- no worries, everybody's had to deal with it.  I'll run them all through CI when the boards are again green.  Thanks!

**Comment by krOoze** [comment]
@mark-lunarg FYI all my PRs should be rebased not, and my personal `pNext` fix dropped.

**Comment by mark-lunarg** [comment]
Passed CI -- thanks Petr!

**Pull request merged**
