### PR TITLE
Cross-queue memory barriers not validated properly

### PR DESCRIPTION
**Pull request by BingoBongoVrn**
Vertex buffer is filled by data on transfer queue then it is transferred to graphics queue. Transferring barrier has srcQueueFamilyIndex == 2 (transfer queue), dstQueueFamilyIndex == 0 (graphics queue), srcPipelineStage = VK_PIPELINE_STAGE_TRANSFER_BIT, dstPipelineStage = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT. After calling vkCmdPipelineBarrier() I get this validation error:

`Vulkan: Validation Error: [ VUID-vkCmdPipelineBarrier-dstStageMask-04098 ] Object 0: handle = 0x1c348826380, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x95bc4c5b | vkCmdPipelineBarrier(): .dstStageMask flag VK_PIPELINE_STAGE_VERTEX_INPUT_BIT is not compatible with the queue family properties (VK_QUEUE_TRANSFER_BIT|VK_QUEUE_SPARSE_BINDING_BIT) of this command buffer. The Vulkan spec states: Any pipeline stage included in pname:dstStageMask must be supported by the capabilities of the queue family specified by the queueFamilyIndex member of the VkCommandPoolCreateInfo structure that was used to create the VkCommandPool that commandBuffer was allocated from, as specified in the table of supported pipeline stages (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensio… ageMask-04098)`

Before update to 2.189 my code worked fine. It feels like old problem that existed 4 years ago https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1550 .

### CODE REVIEW

**Review by jeremyg-lunarg — CHANGES_REQUESTED** [review]
The doc changes in this PR don't appear to be related to the description.

WRT queue family ownership transfers, please see https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2888 and https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#synchronization-queue-transfers  The spec only mentions special conditions about access masks during queue family ownership transfers.

**Comment by jeremyg-lunarg** [comment]
Also, the CTS cases mentioned in #1550 have been since been updated see https://github.com/KhronosGroup/VK-GL-CTS/blob/5d72b170aad664e4fcf770863d37bd041d45ff9b/external/vulkancts/modules/vulkan/synchronization/vktSynchronizationOperationMultiQueueTests.cpp#L338

**Comment by BingoBongoVrn** [comment]
Oh, I see, when there is transfer between queues, "from top to bottom" pipeline stages could be used and srcAccess and dstAccess masks should equal to 0. But it feels like validation layer provides some misinformation in such case (not only my opinion). Also specification says that during release/acquire resource transfer values of srcAccess and dstAccess masks don't affect validity of barrier but validation layer anyway checks them. So I suppose request should be closed ?

p,s. Probably I missed how pulling of request works because I have no idea why there is this doc attached.

**Comment by jeremyg-lunarg** [comment]
> Oh, I see, when there is transfer between queues, "from top to bottom" pipeline stages could be used and srcAccess and dstAccess masks should equal to 0. But it feels like validation layer provides some misinformation in such case (not only my opinion). So I suppose request should be closed ?

I can close it, but if you think the error message is providing misinformation, is there something we could do to make what is happening here clearer?

> p,s. Probably I missed how pulling of request works because I have no idea why there is this doc attached.

You probably should have created an Issue instead, but not big problem.

**Comment by BingoBongoVrn** [comment]
> if you think the error message is providing misinformation, is there something we could do to make what is happening here clearer?

I still don't understand why checking of pipeline stages during transfer was started after this discussion https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2888 if specification says nothing about pipeline stages. Problem is that error I and everybody got contradicts existing of queues because it says that I can't fill vertex buffer in transfer queue and then transfer this buffer to graphics queue through one pair of release/acquire barriers. Also good question is how dstAccessMask can be checked in release barrier and srcAccessMask can be check in acquire barrier if specification strictly says that these masks are ignored and they don't affect validity of barrier. Original solution to check srcPipelineStage and srcAccessMask in release barrier and dstPipelineStage and dstAccessMask in acquire barrier feels like it is optimal. So in this situation it is hard to think about valid message if something is wrong.

>  I can close it
ok, thanks, then I'm leaving decision of closing to you.

**Comment by jeremyg-lunarg** [comment]
The dstAccessMask in the release barrier and the srcAccessMask in the acquire barrier are ignored because 'something' has to happen in the hardware to make the buffer or image memory be accessible to the other queue family. After the release barrier, memory access is no longer possible in the src queue family and before the acquire barrier, memory access is not possible in the dst queue family.

However, in both the acquire and release barriers, you could still use the dst or src stage masks to form an execution dependency chain for synchronization with other commands in the src or dst command buffers.   This would be similar to having a barrier that has both the src and dst access masks set to 0.  I'm not sure how often this is useful in practice, but I think it is valid, and it looks like it was considered as part of[ Vulkan-Docs issue 347](https://github.com/KhronosGroup/Vulkan-Docs/issues/347), which I think is what lead to the last set of changes to this part of the spec. 

I'm going to close this PR. If this is still a problem the best way to proceed will be to open a [Vulkan-Docs issue](https://github.com/KhronosGroup/Vulkan-Docs/issues) or a [validation layer issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues)

**Pull request closed without merging**
