### PR TITLE
Add VUID 02711

### PR DESCRIPTION
**Pull request by sfricke-samsung**
In process created a common function for [indirect commands](https://github.com/KhronosGroup/Vulkan-Docs/blob/master/chapters/commonvalidity/draw_dispatch_indirect_common.txt) which moved the 02708 and 02709 VUIDs to the DrawDispatchVuid look up table.

Also used `unprotected` for state tracking instead of `protected` due to it being a c++ keyword

Adds:
VUID-vkCmdDrawIndirect-commandBuffer-02711
VUID-vkCmdDispatchIndirect-commandBuffer-02711
VUID-vkCmdDrawIndexedIndirect-commandBuffer-02711
VUID-vkCmdDrawIndirectCount-commandBuffer-02711
VUID-vkCmdDrawIndexedIndirectCount-commandBuffer-02711
VUID-vkCmdTraceRaysIndirectKHR-commandBuffer-02711
VUID-vkCmdDrawMeshTasksIndirectCountNV-commandBuffer-02711
VUID-vkCmdDrawMeshTasksIndirectNV-commandBuffer-02711

### CODE REVIEW

**Comment by jeremyk-lunarg** [comment]
I'm working on adding some vkCmdDraw* VUIDs as well. These don't look like they overlap with my work currently, but is there a way we can coordinate so that we don't overlap in the future?

**Comment by sfricke-samsung** [comment]
@jeremyk-lunarg Well the best way is to have issues prior to making the PR (which 100% guilty of not doing)

Is there an issue or set of vkCmdDraw* VUID's you are working on, my goal currently is to get all the protected memory VUID covered

**Comment by jeremyk-lunarg** [comment]
@sfricke-samsung I was doing a little work on `02707`, but I'm not very far along, so I'll leave that one to you.
Working on issue #135 and just going through the VUIDs in there.
Currently I'm testing changes I made for validating `02696`.

**Comment by sfricke-samsung** [comment]
@jeremyk-lunarg I created an issue to track what I plan to cover next for more transparency and to not have people do the same work twice

**Comment by jeremyk-lunarg** [comment]
@sfricke-samsung Thank you!

**Pull request merged**
