### PR TITLE
Fix GPU-AV destroy renderpass to call state tracker

### PR DESCRIPTION
**Pull request by Tony-LunarG**

### CODE REVIEW

**Comment by Tony-LunarG** [comment]
> Are there any other places needs to call up to ValidationStateTracker?

Yes there are.  Consider this WIP for a while.

**Review by ncesario-lunarg — APPROVED** [review]
LGTM so far!

**Comment by Tony-LunarG** [comment]
More complete now

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM

**Pull request merged**
