### PR TITLE
layers: Use CommandTypeString everywhere

### PR DESCRIPTION
**Pull request by sfricke-samsung**
So this was going to be a simple "use `CommandTypeString` instead of hard coding strings arguments everywhere" and slowly got larger then I was expecting.

- Had to generate the `CMD_TYPE` alias names
- Had to duplicate `DrawDispatchVuid`/`GpuVuid`, think this was the right choice
- For sync validation, removed the concept of `override_name` in `SyncOpBase`
- In `CoreValidation`/`GpuValidation` there are no entry pointgs for `vkCmdDrawIndirectCountAMD`/`vkCmdDrawIndexedIndirectCountAMD` currently, so didn't add those here

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
This LGTM, but adding other folks due to the scope of this change, specifically @jeremyg-lunarg for the changes related to synchronization.

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM. This is a really nice cleanup.

**Comment by sfricke-samsung** [comment]
rebased to resolve conflict

**Review by Tony-LunarG — APPROVED** [review]
Very nice!

**Pull request merged**
