### PR TITLE
layers: Remove some unassigned labels

### PR DESCRIPTION
**Pull request by sfricke-samsung**
VUID-VkGraphicsPipelineCreateInfo-stage-00726
VUID-vkQueueSubmit-pSubmits-04626
VUID-vkCmdDrawIndirectByteCountEXT-counterBufferOffset-04568
VUID-VkPipelineShaderStageCreateInfo-pName-00707
VUID-VkPipelineRasterizationStateCreateInfo-polygonMode-01413

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
[Internal CI running](http://erusea:4040/8158).

**Review by ncesario-lunarg — APPROVED** [review]
LGTM! Just waiting for CI.

**Comment by ncesario-lunarg** [comment]
Internal CI looks good and github actions (on [separate branch](https://github.com/ncesario-lunarg/Vulkan-ValidationLayers/actions/runs/494724675) with GH actions fix).

**Comment by sfricke-samsung** [comment]
rebased to see if GitHub actions are working now

**Comment by sfricke-samsung** [comment]
@ncesario-lunarg seems the rebase worked, will do with the other PRs

**Comment by ncesario-lunarg** [comment]
That would be awesome, thanks @sfricke-samsung!

**Pull request merged**
