### PR TITLE
Migrate swapchain acquire check to stateless +tests

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@krOoze, this PR fails `VkPositiveLayerTest.SwapChainImageLayout` on the Android platforms (including my Pixel2XL), and on one platform (Pixel3) it also fails `VkLayerTest.WarningSwapchainCreateInfoPreTransform`.

**Comment by krOoze** [comment]
The check is very trivial; it seems unlikely. What is the exact fail log?

**Comment by krOoze** [comment]
`WarningSwapchainCreateInfoPreTransform` does not even call acquire...

**Comment by mark-lunarg** [comment]
Sorry, the two failures for this test are `VkLayerTest.SwapchainAcquireImageNoSyncKHR` and `VkLayerTest.WarningSwapchainCreateInfoPreTransform`.  Pertinent adb log snippets:


```
2780 11-14 15:00:14.029 31722 31738 I VulkanLayerValidationTests: [ RUN      ] VkLayerTest.SwapchainAcquireImageNoSync
2781 11-14 15:00:14.038 31722 31738 I vulkan  : Loaded layer VK_LAYER_KHRONOS_validation
2782 11-14 15:00:14.041 31722 31738 I Adreno  : QUALCOMM build          : 6fb5a5b, Ife855c4895
2783 11-14 15:00:14.041 31722 31738 I Adreno  : Build Date              : 08/21/18
2784 11-14 15:00:14.041 31722 31738 I Adreno  : Shader Compiler Version : EV031.25.00.00
2785 11-14 15:00:14.041 31722 31738 I Adreno  : Local Branch            : Googledrop_0815
2786 11-14 15:00:14.041 31722 31738 I Adreno  : Remote Branch           :
2787 11-14 15:00:14.041 31722 31738 I Adreno  : Remote Branch           :
2788 11-14 15:00:14.041 31722 31738 I Adreno  : Reconstruct Branch      :
2789 11-14 15:00:14.041 31722 31738 I Adreno  : Build Config                     : S L 4.0.10 AArch64
2790 11-14 15:00:14.041 31722 31738 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2791 11-14 15:00:14.042 31722 31738 I chatty  : uid=10309(com.example.VulkanLayerValidationTests) identical 4 lines
2792 11-14 15:00:14.042 31722 31738 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2793 11-14 15:00:14.050   613 14801 I SDM     : HWCDisplay::GetColorModeCount: Supported color mode count = 3
2794 11-14 15:00:14.051   613 14801 I SDM     : HWCDisplay::GetColorModes: Supports color mode[0] = 0
2795 11-14 15:00:14.051   613 14801 I SDM     : HWCDisplay::GetColorModes: Supports color mode[1] = 7
2796 11-14 15:00:14.051   613 14801 I SDM     : HWCDisplay::GetColorModes: Supports color mode[2] = 9
2797 11-14 15:00:14.051 31722 31738 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
2798 11-14 15:00:14.051   613 14801 I SDM     : HWCDisplay::GetColorModeCount: Supported color mode count = 3
2799 11-14 15:00:14.051   613 14801 I SDM     : HWCDisplay::GetColorModes: Supports color mode[0] = 0
2800 11-14 15:00:14.051   613 14801 I SDM     : HWCDisplay::GetColorModes: Supports color mode[1] = 7
2801 11-14 15:00:14.051   613 14801 I SDM     : HWCDisplay::GetColorModes: Supports color mode[2] = 9
2802 11-14 15:00:14.052 31722 31738 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
2803 11-14 15:00:14.061 31722 31738 I VulkanLayerValidationTests: [       OK ]VkLayerTest.SwapchainAcquireImageNoSync (32 ms)
2804 11-14 15:00:14.061 31722 31738 I VulkanLayerValidationTests: [ RUN      ] VkLayerTest.SwapchainAcquireImageNoSync2KHR
2805 11-14 15:00:14.074 31722 31738 I vulkan  : Loaded layer VK_LAYER_KHRONOS_validation
2806 11-14 15:00:14.076 31722 31738 I Adreno  : QUALCOMM build          : 6fb5a5b, Ife855c4895
2807 11-14 15:00:14.076 31722 31738 I Adreno  : Build Date              : 08/21/18
2808 11-14 15:00:14.076 31722 31738 I Adreno  : Shader Compiler Version : EV031.25.00.00
2809 11-14 15:00:14.076 31722 31738 I Adreno  : Local Branch            : Googledrop_0815
2810 11-14 15:00:14.076 31722 31738 I Adreno  : Remote Branch           :
2811 11-14 15:00:14.076 31722 31738 I Adreno  : Remote Branch           :
2812 11-14 15:00:14.076 31722 31738 I Adreno  : Reconstruct Branch      :
2813 11-14 15:00:14.076 31722 31738 I Adreno  : Build Config                     : S L 4.0.10 AArch64
2814 11-14 15:00:14.077 31722 31738 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2815 11-14 15:00:14.077 31722 31738 I chatty  : uid=10309(com.example.VulkanLayerValidationTests) identical 8 lines
2816 11-14 15:00:14.077 31722 31738 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2817 11-14 15:00:14.084   611  1284 E BufferQueueProducer: [com.example.VulkanLayerValidationTests/android.app.NativeActivity#0] connect: already connected (cur=1 req=1)
2818 11-14 15:00:14.084 31722 31738 E vulkan  : native_window_api_connect() failed: Invalid argument (-22)
2819 11-14 15:00:14.084 31722 31738 I VulkanLayerValidationTests: *** Failure in jni/../../tests/vklayertests_others.cpp:1236 Value of: InitSwapchain()
2820 11-14 15:00:14.084 31722 31738 I VulkanLayerValidationTests:   Actual: false
2821 11-14 15:00:14.084 31722 31738 I VulkanLayerValidationTests: Expected: true
2822 11-14 15:00:14.090 31722 31738 I VulkanLayerValidationTests: [  FAILED  ]VkLayerTest.SwapchainAcquireImageNoSync2KHR (29 ms)
```


```
3358 11-14 15:00:15.593 31722 31738 I VulkanLayerValidationTests: [ RUN      ] VkLayerTest.WarningSwapchainCreateInfoPreTransform
3359 11-14 15:00:15.604 31722 31738 I vulkan  : Loaded layer VK_LAYER_KHRONOS_validation
3360 11-14 15:00:15.606 31722 31738 I Adreno  : QUALCOMM build          : 6fb5a5b, Ife855c4895
3361 11-14 15:00:15.606 31722 31738 I Adreno  : Build Date              : 08/21/18
3362 11-14 15:00:15.606 31722 31738 I Adreno  : Shader Compiler Version : EV031.25.00.00
3363 11-14 15:00:15.606 31722 31738 I Adreno  : Local Branch            : Googledrop_0815
3364 11-14 15:00:15.606 31722 31738 I Adreno  : Remote Branch           :
3365 11-14 15:00:15.606 31722 31738 I Adreno  : Remote Branch           :
3366 11-14 15:00:15.606 31722 31738 I Adreno  : Reconstruct Branch      :
3367 11-14 15:00:15.606 31722 31738 I Adreno  : Build Config                     : S L 4.0.10 AArch64
3368 11-14 15:00:15.607 31722 31738 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
3369 11-14 15:00:15.607 31722 31738 I chatty  : uid=10309(com.example.VulkanLayerValidationTests) identical 4 lines
3370 11-14 15:00:15.607 31722 31738 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
3371 11-14 15:00:15.620   611  1284 E BufferQueueProducer: [com.example.VulkanLayerValidationTests/android.app.NativeActivity#0] connect: already connected (cur=1 req=1)
3372 11-14 15:00:15.621 31722 31738 E vulkan  : native_window_api_connect() failed: Invalid argument (-22)
3373 11-14 15:00:15.621 31722 31738 I VulkanLayerValidationTests: *** Failure in jni/../../tests/vkrenderframework.cpp:145 Failed
3374 11-14 15:00:15.621 31722 31738 I VulkanLayerValidationTests: Did not receive expected error 'UNASSIGNED-CoreValidation-SwapchainPreTransform'
3375 11-14 15:00:15.628 31722 31738 I VulkanLayerValidationTests: [  FAILED  ]VkLayerTest.WarningSwapchainCreateInfoPreTransform (35 ms)
```

**Comment by mark-lunarg** [comment]
Double-checking on Master now.

**Comment by mark-lunarg** [comment]
No failures on Master, fails similarly with the patch on top of Master.

**Comment by krOoze** [comment]
Oh ok, `SwapchainAcquireImageNoSync` is buggy. Gonna see about the other one

**Comment by krOoze** [comment]
@mark-lunarg Yea, I do not see anything wrong with this. `VkLayerTest.WarningSwapchainCreateInfoPreTransform` does not even call `vkAcquireNextImageKHR`, so hard to see how it could be anything with this code...

**Comment by mark-lunarg** [comment]
@krOoze, `WarningSwapchainCreateInfoPreTransform `is probably OK.  What I'm seeing is that there are dependencies:

1 = SwapchainAcquireImageNoSync
2 = SwapchainAcquireImageNoSyncKHR
3 = WarningSwapchainCreateInfoPreTransform

Execute 1, 2, 3:     2 and 3 fail
Execute 2, 3:         3 fails
Execute 1:             no failure
Execute 2:             no failure
Execute 3:             no failure
Execute 1,2:          2 fails
Execute 1,3:          3 fails

There should be a complete Vulkan teardown/setup between each test, but it could be a bug in the framework or the driver is ending up in some weird state.  BTW, it doesn't seem to matter if other tests occur in between the three, the results remain the same in the cases I've tested.

**Comment by mark-lunarg** [comment]
@krOoze, this might be related to #1340. Doing some testing now.

**Comment by krOoze** [comment]
@mark-lunarg I see Android window set to null, but never changed anywhere. Maybe not implemented for Android yet?

**Comment by krOoze** [comment]
@mark-lunarg Hm, seems I am supposed to explicitly call `DestroySwapchain()`. Android probably reuses the window and the framework cleanup is bad.

**Comment by krOoze** [comment]
@mark-lunarg I pushed the change. If you would kindly re-test.

**Pull request merged**
