### PR TITLE
layers: Add semaphore tracking to LatencySleepNV

### PR DESCRIPTION
**Pull request by chansen-nv**
vkLatencySleepNV will trigger a semaphore signaling which is waited on by an application with vkWaitSemaphores. Currently when applications with Low Latency 2 support are run with VVL, due to the lack of semaphore tracking in vkLatencySleepNV, vkWaitSemaphores will timeout. This Pull Request adds tracking to vkLatencySleepNV which resolves the issue.

### CODE REVIEW

**Review by spencer-lunarg — APPROVED** [review]
This LGTM

1. To make CI happy, adjust your commit message to `layers: Add semaphore tracking to LatencySleepNV'
2. Optional, but if you want to add a simple test using the API correctly (like hello_world style simple) to `sync_object_positive.cpp` it will run on CI with our null driver and can help catch future regressions

**Comment by chansen-nv** [comment]
Thanks Spencer! I've amended the commit name and have added writing a test to my todo list (it should not block this fix)

**Comment by spencer-lunarg** [comment]
>  have added writing a test to my todo list (it should not block this fix)

yep, will happy to get this in now, tests are always welcomed after for vendor extensions! (it is best way for us to accidentally not break these in any future refactoring that touch the semaphore state tracking)

**Comment by spencer-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/8887329471/job/24402429349?pr=7922

Sorry, the merge commit is triggering CI now

**Comment by chansen-nv** [comment]
I created a new pull request to fix the merge commits messages, closing out this one in favor of https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7930

**Pull request closed without merging**
