### PR TITLE
layers: Split shader_validation to shader_module

### PR DESCRIPTION
**Pull request by sfricke-samsung**
So now having spent a lot more time in both `shader_validation.cpp` and `spirv-val` in SPIRV-Tools as well as wanting to add more stuff like [atomics validation](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2629), proper CFG logic for [per entry-point checking](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2450), etc, I find myself feeling I am just adding more and more bloat onto what is a quite large single file for shader validation.

I am purposing splitting the logic into 2 parts

- `shader_module.cpp/h` - in charge of `SHADER_MODULE_STATE` and all utility around jumping around and getting what is needed out of a SPIR-V module
- `shader_validation.cpp/h` - does all the actual "validation checking", cares about the pipeline and/or command buffer being used, etc

With this, I never understood why we always pass `const SHADER_MODULE_STATE *module` around everywhere and not just make it a member function of the state object.

I started splitting it, but before I spend more time into, want some feedback on overall direction

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@sfricke-samsung, this approach LGTM as long as shader validation guru @ncesario-lunarg is happy with it.   A long overdue refactor -- forge ahead!  Thanks.

**Review by ncesario-lunarg — APPROVED** [review]
I have been wanting to refactor the shader validation in "some way" for a while and this looks like a great first step!

As for making SHADER_MODULE_STATE a "member function of the state object," do you have an example of what that would look like? My current understanding is this is just another "handle -> state" map in the state tracker.

And don't let Mark fool you. AFAIK, him and Tony are the "de facto VVL gurus" ;)

**Comment by sfricke-samsung** [comment]
> do you have an example of what that would look like

```patch
-    auto entrypoint = FindEntrypoint(module, createInfo.stage.pName, createInfo.stage.stage);
+    auto entrypoint = module->FindEntrypoint(createInfo.stage.pName, createInfo.stage.stage);

struct SHADER_MODULE_STATE : public BASE_NODE {
// ...
+ spirv_inst_iter FindEntrypoint(char const *name, VkShaderStageFlagBits stageBits) const;
}

- spirv_inst_iter FindEntrypoint(SHADER_MODULE_STATE const *src, char const *name, VkShaderStageFlagBits stageBits);
```

**Comment by ncesario-lunarg** [comment]
Running through [internal CI](http://erusea:4040/8913).

**Comment by ncesario-lunarg** [comment]
:+1: thanks, and I think making that change on a larger scale makes sense if it does to everyone else.

**Comment by ncesario-lunarg** [comment]
Looks like this is missing at least [this](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/cd2972d) change, specifically https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/7699b91798eb0cc43d8be031e457bcc21a7f91d5/layers/shader_validation.cpp#L3270.

**Comment by sfricke-samsung** [comment]
I might be on a few day old trees, will rebase and make sure to fix that and do another scan of what I moved

This was really more of a "is this worth putting more time into" / "anyone else actively trying to solve this" PR

**Comment by ncesario-lunarg** [comment]
Worth putting more time int? I think so.

Anyone _actively_ trying to solve this? Not so much :)

**Comment by sfricke-samsung** [comment]
@ncesario-lunarg the commit was old and rebasing and just checking the [history](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commits/master/layers/shader_validation.cpp) confirmed that was it.

So I think I got a good first pass at a refactoring, I think more polishing could be done post this PR (as I found even just doing this), but I would leave this scope as purely just moving half (actually pretty close) of the shader logic out of the current file and in its own file where it can be cleaned up easier by itself there

Also with the scale of this change, and no hard urgency, happy to rebase post next SDK code freeze as hate for this to introduce a series of bugs by accident... luckily this only touches the shader_validation.cpp/h files so rebasing is just as easy and looking at what only changed in those 2 files... will leave that up to shader validation guru @ncesario-lunarg and crew

**Comment by mark-lunarg** [comment]
@sfricke-samsung, this all sounds great to me.  I also think shader validation guru @ncesario-lunarg will happily concur with your implementation plan.

**Comment by ncesario-lunarg** [comment]
🤦 alright, any messages I get concerning "shader validation gurus" I'm forwarding to both of you ;)

But yes, from a non-guru perspective this sounds good. From what I could tell this change does not introduce any functional changes, only refactoring? If that's true, I think this can go in now as we still have a little over a week before locking things down for the next SDK release.

**Comment by sfricke-samsung** [comment]
There are no intended functional changes, I kept the scope of this as only to move things over, so it should be safe to go IMHO

**Comment by ncesario-lunarg** [comment]
Re-running this through internal CI. Will merge once that clears.

**Pull request merged**
