### PR TITLE
Add SyncVal QueueSubmit as ALPHA

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Add the enable for QueueSubmit time synchronization validation, set as
alpha.

@christophe-lunarg  -- not sure how to test this.

### CODE REVIEW

**Comment by christophe-lunarg** [comment]
Sadly, this is again an issue of the validation layer settings enable and disable falgs not being about to express their relationships so the validation layer settings for enables and disables have a built-in UI in vkconfig. I am still hoping to work someday at a refactoring of the validation layer settings to resolve this issue.

So I'll need to hard code the changes in vkconfig. I supose that this setting can only be enable when VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT is enabled?

If that's the case, would it be an issue for you to not use a flag but create an boolean setting?

The manifest file would look like:
```
                            "key": "VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT",
                            "label": "Synchronization",
                            "description": "This feature reports resource access conflicts due to missing or incorrect synchronization operations between actions (Draw, Copy, Dispatch, Blit) reading or writing the same regions of memory.",
                            "url": "${LUNARG_SDK}/synchronization_usage.html",
                            "status": "STABLE",
                            "platforms": [ "WINDOWS", "LINUX", "MACOS", "ANDROID" ]
                            "settings": [
                                {
                                    "key": "check_synchronization_queue_submit",
                                    "label": "QueueSubmit Synchronization Validation",
                                    "description": "Enable synchronization validation between submitted command buffers when Synchronization Validation is enabled.",
                                    "type": "BOOL",
                                    "default": false,
                                    "status": "ALPHA"
                                    "dependence": {
                                        "mode": "ANY",
                                        "settings": [
                                            {
                                                "key": "enables",
                                                "value": [ "VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT" ]
                                            }
                                        ]
                                    }
                                },
```

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM

**Comment by christophe-lunarg** [comment]
@jzulauf-lunarg my proposed changed required validation implementation changes, did you make them somewhere else?

Do you read somewhere check_synchronization_queue_submit in you code?

**Review by christophe-lunarg — APPROVED** [review]

**Comment by jzulauf-lunarg** [comment]
@jeremyg-lunarg -- updated docs, give a quick look?
@KarenGhavam-lunarG -- documentation change added to PR, who to add to review?

**Pull request merged**
