### PR TITLE
Extend the device profile layer

### PR DESCRIPTION
**Pull request by Whenning42**
Extended the device profile layer so that every validation layer test
can be run without skipping on just the device profile layer and the
mock ICD. This provides a quicker and more reliable way to run all the
tests than using devsim with the 9 current device profiles. This form of
running tests however is possibly less thorough as each test will only
encounter one config instead of the 9.

### CODE REVIEW

**Comment by Whenning42** [comment]
Overall, I can't tell how the benefits of this change match-up against the added complexity. Having a reliable and fast way to hit all the tests would be fantastic, however if we're not convinced it's thorough enough to stop using dev sim, I'm not sure what the benefits are. Regardless, this PR at least provides and example of how dev profile can be expanded and more heavily used in the validation tests.

**Comment by tobine** [comment]
@mark-lunarg Yes, I'll do something with this

**Comment by locke-lunarg** [comment]
@Whenning42  The test structure changed.  In `layer_validation_tests.cpp`, please declare in  `layer_validation_tests.h` and define in `layer_validation_tests.cpp`.  Those `VkLayerTest` have moved into `vklayertests_XXXXX.cpp`. You can use those tests name to search them.  Please let me know if more assistance is needed. Thank you.

**Comment by mark-lunarg** [comment]
Added reference to this work to the [internal Projects issue](https://github.com/LunarG/Projects/issues/179) for the device profile layer.  Closing this as it's grown stale (sorry!).

**Pull request closed without merging**
