### PR TITLE
[WIP] Implement VK_NV_device_generated_commands

### PR DESCRIPTION
**Pull request by pixeljetstream**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@pixeljetstream, hopefully we aren't blocking here -- is there an update on this effort?

**Comment by pixeljetstream** [comment]
No, just other priorities at the moment, hence unexpected break. Thanks for asking.

**Comment by mark-lunarg** [comment]
@pixeljetstream, closing this for now due to inactivity -- when there's time later, we can reopen this PR or just create a new one -- thanks!

**Comment by pixeljetstream** [comment]
please re-open again. I would like you to comment on the changes made so far. The biggest pain points in merging is that I split up graphics pipeline state validation into a few functions. This change could be done independent of DGC to make the change sort of two step merging. Or I can keep it as is, as one big commit. Please advice.

The only thing missing are the unit tests

**Comment by mark-lunarg** [comment]
@pixeljetstream, github says the branch has been updated/recreated since the PR closed and so the PR cannot be reopened -- create a new one and I'll link it back to this one.   We'll put the comments on the current state in that PR.   In general, overly monolithic commits are less preferable, but we don't want to make extra work for you.

**Pull request closed without merging**
