### PR TITLE
[WIP] Arm Perfdoc Check 23 - Depth Pre-pass Warning

### PR DESCRIPTION
**Pull request by samwalls-arm**
Here's another check from Arm perfdoc. This check estimates and warns against the usage of depth pre-passes for Arm best practices.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Hey @samwalls-arm, I can't remember why we made this WIP, but I just rebased/deconflicted and have it passing all CI here.  Should I push these changes?

**Comment by samwalls-arm** [comment]
Hey @mark-lunarg thank you for that! I pushed this, then left it alone at the last minute, as I wanted to check what it would do on real content which uses depth pre-passes. I haven't worked on that yet. Additionally I have a feature branch from Attilio with an implementation of pipeline bubble tracking, which I also want to test on real content.

The behaviour here is a nearly direct port from what's in PerfDoc. So, I'm quite confident that it works for some cases, but wondering if there's any common or simple cases which wouldn't be captured by the checks.

I'll try to find some time in the next few weeks to test them - unless you think these tests are sufficient to do an initial implementation? Thanks again!

**Comment by mark-lunarg** [comment]
OK, I will try to push my changes back onto your branch, if that's OK with you...

**Comment by samwalls-arm** [comment]
@mark-lunarg Sorry, didn't see that this was a question. Yes, that should be fine!

**Comment by mark-lunarg** [comment]
@samwalls-arm, I wasn't able to push to the existing branch, so I pushed this one to origin:

`markl-pr-arm-check-23`

As I mentioned, it is passing all CI.  I will leave it up to y'all as to whether it's OK to go in as-is.  Thanks!

**Comment by samwalls-arm** [comment]
Hey @mark-lunarg, I think we're fine with adding these for now. We know what's implemented works due to the tests, it also copies what was in PerfDoc closely, so we're confident in it. If we need to expand the class of cases where a warning is thrown, in the future, that should be fine.

Is the branch you rebased still non-conflicting?

**Comment by mark-lunarg** [comment]
OK, I'll rebase it again and run it through CI, with an eye towards pushing.  Thanks!

**Comment by mark-lunarg** [comment]
Rebased and pushed to Master.  Thanks!

**Comment by samwalls-arm** [comment]
Thanks for that @mark-lunarg! Apologies for keeping this waiting around, if that makes a difference to you.

**Comment by mark-lunarg** [comment]
Hey @samwalls-arm, our team has noticed that this commit causes crashes when running CTS.  The dEQP-VK.api.smoke.triangle test (and a few more) crash with these BP checks enabled and pass without them.  They noticed that at least on Windows, `PostCallRecordCmdBindPipeline()` `blend_state ` is garbage and gets dereferenced.  Would you have the time to take a look?

**Comment by mark-lunarg** [comment]
@samwalls-arm, nevermind -- this looks to be the same failure as those reported in #2018, and @Tony-LunarG is handling that one.  Sorry for the churn!

**Comment by samwalls-arm** [comment]
@mark-lunarg, looking at the code, quickly, I'm not sure why that would be happening. I hope Tony can pinpoint the problem.

**Pull request closed without merging**
