### PR TITLE
Correctly check buffers' bound memory overlap

### PR DESCRIPTION
**Pull request by aitor-lunarg**

### CODE REVIEW

**Comment by aitor-lunarg** [comment]
Should solve the issue about not correctly checking memory overlap for buffer copy operations. Affected VUIDs: VUID-vkCmdCopyBuffer-pRegions-00117, VUID-VkCopyBufferInfo2-pRegions-001171 from #3993 

The approach could be improved when it comes to performance, but there would be a need to implement a container that inserts while merging ranges. The sparse_container::range_map<Key, T> kind of does the job, but we would be wasting memory since we don't need to store anything. With this container, we can compute all ranges from the source buffer, and later just try to intersect the ranges from destination buffer (It should be faster).

It would be good to have some sparse resource copy testing, but there's work to be done about sparse resources (I'll have a look to start working on that).

**Comment by jeremyg-lunarg** [comment]
running perf tests on this PR

**Comment by Tony-LunarG** [comment]
Any tests covering the cases that this code fixes?

**Comment by aitor-lunarg** [comment]
We don't have such test. It may be a good idea to add it. I will prepare a test that highlights the issue we are fixing with this PR

**Review by ziga-lunarg — APPROVED** [review]

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM. No perf changes from this PR.

**Pull request merged**
