### PR TITLE
Add missing implicit arrayLength VUs

### PR DESCRIPTION
**Pull request by sfricke-samsung**
I randomly came across this a while ago and finally got time to just dig into the XML/Python code.

Added generated logic to expose missing implicit VUs for array length

Added a test to cover the various edge cases missing as well

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Rebased, fixed conflicts, running through CI.

**Comment by mark-lunarg** [comment]
@sfricke-samsung, one failure on NV Windows, below.  Also, would you mind rebasing while you're in there?  Thanks!

```
[ RUN      ] VkLayerTest.ShadingRateImageNV
Unexpected: Validation Error: [ VUID-VkPipelineViewportShadingRateImageStateCreateInfoNV-viewportCount-arraylength ] Object 0: handle = 0x1d16382b108, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x140a7702 | VkPipelineViewportShadingRateImageStateCreateInfoNV: parameter viewportCount must be greater than 0. The Vulkan spec states: viewportCount must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkPipelineViewportShadingRateImageStateCreateInfoNV-viewportCount-arraylength)
C:\j\w8\64-bit\Debug\tests\vkrenderframework.cpp(195): error: Failed
Received unexpected error(s).
[  FAILED  ] VkLayerTest.ShadingRateImageNV (1705 ms)
```

**Comment by sfricke-samsung** [comment]
@mark-lunarg ... sorry for keep missing all these NV extensions I can't run locally atm 😆 ... but will rebase and fix the trivial CI failure, figured with `VK_KHR_fragment_shading_rate` in I would need to rebase a lot of things

**Comment by mark-lunarg** [comment]
No problem Spencer, we all have the same problem.  If I could get you access to the test farm I would! We have some plans to automate some of this stuff, perhaps someday you can iterate on these issues just like we do.

**Comment by mark-lunarg** [comment]
Running through CI.

**Review by mark-lunarg — APPROVED** [review]

**Comment by mark-lunarg** [comment]
Passed CI.  Thanks Spencer, this is a really nice pickup!

**Pull request merged**
