### PR TITLE
layers: Find all shader variable ids, fix false positive wrong descriptor type

### LINKED ISSUE #3971: Possible false positive with aliased descriptor arrays
**Describe the Issue**
I believe I am getting this error incorrectly:

`Validation Error: [ VUID-vkCmdDrawIndexed-None-02699 ] Object 0: handle = 0xedcc4d0000000f9b, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xa44449d4 | Descriptor set VkDescriptorSet 0xedcc4d0000000f9b[] encountered the following validation error at vkCmdDrawIndexed time: Descriptor in binding #30 index 4117 requires an image view of type VK_IMAGE_VIEW_TYPE_2D, VK_IMAGE_VIEW_TYPE_3D but got VK_IMAGE_VIEW_TYPE_CUBE_ARRAY. The Vulkan spec states: Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid if they are statically used by the VkPipeline bound to the pipeline bind point used by this command (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-None-02699)
`

We have an HLSL shader that has several arrays of textures aliased to the same descriptor binding:

```
Texture2D g_bindless_Texture2D[] : layout( set = 4, binding = 0);
Texture3D g_bindless_Texture3D[] : layout( set = 4, binding = 0);
TextureCube g_bindless_TextureCube[] : layout( set = 4, binding = 0);
Texture2DArray g_bindless_Texture2DArray[] : layout( set = 4, binding = 0);
TextureCubeArray g_bindless_TextureCubeArray[] : layout( set = 4, binding = 0);
```

We create a descriptor set that VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT and when we allocate the descriptor set we provide a VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO_EXT with the size of these arrays (I am providing this for context, but the same bug would exist if the arrays were sized in the shader instead of by variable count).

We load the descriptor set with textures of all of the types above: 2D, 3D, Cube, 2DArray, CubeArray.

In CoreChecks::ValidateDescriptorSetBindingData() validation iterates over all of the descriptors in the array.  For each descriptor it calls CoreChecks::ValidateImageDescriptor.  So far so good, but then for the descriptor the value of binding_info.second.reqs is 0x0686.  Specifically it has determined that the descriptor reqs has DESCRIPTOR_REQ_VIEW_TYPE_2D | DESCRIPTOR_REQ_VIEW_TYPE_3D.

The reason it has decided that 2D | 3D is required is because it analyzes the shader module in SHADER_MODULE_STATE::DescriptorTypeToReqs.  This looks at the OpTypeImage SPIR-V instructions and it sees only type 2D and 3D.  The reason for this is because while the shader has declared all of these arrays at the high level code, there are no actual fetches from the g_bindless_TextureCubeArray so there is no way for SHADER_MODULE_STATE::DescriptorTypeToReqs to determine that there is an aliased CubeArray at the same binding.

While the checks being performed here are generally right, in the case of aliased descriptors with dead-code eliminated fetches it doesn't know that the original shader had aliased descriptors at that binding.

The fix for us (and the reason probably this is not commonly hit) is that we will be using VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT on this descriptor set.  In that case, validation will skip the descriptor checks.  It turns out we want to set that for other reasons, but I still thought this was worth reporting because my belief is that technically validation is giving a false positive.

**Valid Usage ID**
VUID-vkCmdDrawIndexed-None-02699

**Environment:**
 - OS:  Windows 10
 - GPU: NVIDIA
 - SDK or header version if building from repo: 208
 - Options enabled (synchronization, best practices, etc.): VK_LAYER_KHRONOS_validation

**Additional context**

### PR DESCRIPTION
**Pull request by ziga-lunarg**
Closes #3971 

Before descriptor types were only checked against used variables, but we need to allow binding descriptor types from unused variables as well, to prevent false positives.

### CODE REVIEW

**Review by ncesario-lunarg — COMMENTED** [review]
I _think_ this is correct, though it might not be depending on the failures in CI.

**Comment by ziga-lunarg** [comment]
It's a bit more complicated, sometimes we want to find unused variables, sometimes we don't, working on it.

**Review by ncesario-lunarg — APPROVED** [review]
LGTM if CI is ok!

**Comment by danginsburg** [comment]
If you run aggressive dead-code spirv-opt elimination does it still work?  If it's still relying on SPIR-V I don't actually see how it's possible.

**Comment by ziga-lunarg** [comment]
If the unused descriptors are removed before it gets to the validation layers I don't think there is anything we can do.

**Comment by danginsburg** [comment]
> If the unused descriptors are removed before it gets to the validation layers I don't think there is anything we can do.

That's really what I meant by the original bug - the descriptors will be eliminated, any time we compile HLSL we run a legalization pass with spirv-opt and part of that will do dead code elimination.  I think it's not possible to know the descriptor image types in the SPIR-V for aliased descriptors.  I don't think there is a simple fix here for validation, there is no way for you to know that it is valid to put a different texture type in an array.  Even avoiding the check if there are aliased descriptors won't work because you can't know there is descriptor aliasing for sure (since the other descriptors might have been eliminated).

**Comment by ziga-lunarg** [comment]
If you believe something else should be done you can reopen the issue. I will think about it in any case.

**Comment by ncesario-lunarg** [comment]
> any time we compile HLSL we run a legalization pass with spirv-opt and part of that will do dead code elimination

I don't think there's anything we can do then. Sounds like we would need some sort of "debug information" to be left behind by spirv-opt, but that seems unlikely to happen (at least not in the short term)?

**Pull request merged**
