### PR TITLE
kill warnings with structs/methods

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Restructure string storage s.t. compiler warnings are eliminated.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Something a bit less invasive?  Maybe?

**Comment by jzulauf-lunarg** [comment]
@mark-lunarg  -- there's this https://github.com/KhronosGroup/Vulkan-ValidationLayers/compare/zulauf_warn_down 

But I'm far less fond of it.

**Comment by jzulauf-lunarg** [comment]
@daveh-lunarg  -- +1 your approach, with an undefine directly following use (or guarded with an ifdef) so the so uses don't conflict.

**Comment by jzulauf-lunarg** [comment]
Abandon for simpler near term solution.

**Pull request closed without merging**
