### PR TITLE
core_validation: Implement some missing vkCmdBindPipeline VUIDs

### PR DESCRIPTION
**Pull request by JasperNV**
This implements the correct VUIDs for vkCmdBindPipeline to ensure that the correct pipeline is used with the correct binding points.

### CODE REVIEW

**Comment by tobine** [comment]
Changes LGTM. Would like a test that hits the 3 VUs. Should be able to copy and re-purpose an existing test, skipping the NV RT case when that feature is not present.

**Comment by JasperNV** [comment]
Is there any documentation on how to run the tests? Running `ctest` inside the VL directory tells me that none were found.

**Comment by tobine** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/CONTRIBUTING.md#testing-your-changes

**Comment by JasperNV** [comment]
Thank you. I will work on adding new tests for this functionality. Are existing tests supposed to pass? I see some errors like:

```
[ RUN      ] VkLayerTest.FramebufferCreateErrors
Unexpected:  [ VUID-VkFramebufferCreateInfo-pAttachments-02633 ] Object: VK_NULL_HANDLE (Type = 0) | vkCreateFramebuffer:  Framebuffer Attachment (0) conflicts with the image's IMAGE_USAGE flags (VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT). The Vulkan spec states: Each element of pAttachments that is used as a depth/stencil attachment by renderPass must have been created with a usage value including VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkFramebufferCreateInfo-pAttachments-02633)
Other error messages logged for this test were:
      [ VUID-VkFramebufferCreateInfo-pAttachments-02633 ] Object: VK_NULL_HANDLE (Type = 0) | vkCreateFramebuffer:  Framebuffer Attachment (0) conflicts with the image's IMAGE_USAGE flags (VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT). The Vulkan spec states: Each element of pAttachments that is used as a depth/stencil attachment by renderPass must
have been created with a usage value including VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkFramebufferCreateInfo-pAttachments-02633)
..\Vulkan-ValidationLayers\tests\layer_validation_tests.cpp(389): error: Failed
Did not receive expected error 'VUID-VkFramebufferCreateInfo-pAttachments-02603'
[  FAILED  ] VkLayerTest.FramebufferCreateErrors (1489 ms)
```

**Comment by tobine** [comment]
Yes, all tests should pass. Note that the test you flagged as failing on your local system is passing on the farm w/ your change: https://travis-ci.org/KhronosGroup/Vulkan-ValidationLayers/jobs/515930972

I'd say ignore any local fails your seeing (unless you *want* to dig into them) and just focus on getting your new test to pass.

**Comment by JasperNV** [comment]
Updated with tests in place. I tried to follow existing conventions as best I could.

**Comment by JasperNV** [comment]
Quick ping on this?

**Pull request merged**
