### PR TITLE
Add Validation for VU 04059

### PR DESCRIPTION
**Pull request by janharaldfredriksen-arm**
Restrict VkBufferViewCreateInfo with VK_WHOLE_SIZE maxTexelBufferElements.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by mark-lunarg** [comment]
@janharaldfredriksen-arm, internal CI failed on linux, android and NV Windows, passed on AMD Windows -- relevant info below:

Nvidia Windows:
> [ RUN      ] VkLayerTest.InvalidBufferViewCreateInfoEntries
> Unexpected: Validation Error: [ VUID-VkBufferViewCreateInfo-buffer-parameter ] Object 0: handle = 0x291c0b6c010, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xe5a3c587 | Invalid VkBuffer Object 0x4c5b620000000007. The Vulkan spec states: buffer must be a valid VkBuffer handle (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkBufferViewCreateInfo-buffer-parameter)
> unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
> [  FAILED  ] VkLayerTest.InvalidBufferViewCreateInfoEntries (1077 ms)

Linux:  
> [ RUN      ] VkLayerTest.InvalidBufferViewCreateInfoEntries
> ERROR: -------------------------------------------------------------
> ERROR: FAIL during test after 1.04 minutes (62.38 seconds) with execute(/home/lunarg/.jenkins/w8/64-bit/Debug/dbuild/tests/vk_layer_validation_tests) failed after 1.04 minutes (62.37 seconds) with returncode=-11 (-0xb)



Android, passed on Pixel3, but crashes on GalaxyS10 and NexusPlayer -- Galaxy S10 logcat info:
> 07-08 10:39:20.897  3066  3121 I VulkanLayerValidationTests: [ RUN      ] VkLayerTest.InvalidBufferViewCreateInfoEntries
> 07-08 10:39:20.910  5505  7807 I CameraService: onUidStateChanged: uid=10068, procState=11
> 07-08 10:39:20.912  4520  4520 I Finsky:download_service: [2] psx.onDestroy(8): IPC-SERVER: Stopping gRPC host service...
> 07-08 10:39:20.918  3066  3121 I vulkan  : Loaded layer VK_LAYER_KHRONOS_validation
> 07-08 10:39:20.928  5505  7807 I CameraService: onUidStateChanged: uid=10068, procState=20
> 07-08 10:39:20.960  3066  3121 W ValidationTest: 0xebadde09 skipped times: 0
> --------- beginning of crash
> 07-08 10:39:20.960  3066  3121 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 3121 (Thread-6), pid 3066 (ValidationTests)
> 07-08 10:39:20.996  6419  6419 E crash_dump64: unknown process state: t
> 07-08 10:39:21.019  6419  6419 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
> 07-08 10:39:21.024  5588  5588 I /system/bin/tombstoned: received crash request for pid 3121
> 07-08 10:39:21.026  6419  6419 I crash_dump64: performing dump of process 3066 (target tid = 3121)
> 07-08 10:39:21.036  6419  6419 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 07-08 10:39:21.037  6419  6419 F DEBUG   : Build fingerprint: 'samsung/beyond1ltexx/beyond1:10/QP1A.190711.020/G973FXXU3BSKO:user/release-keys'
> 07-08 10:39:21.037  6419  6419 F DEBUG   : Revision: '26'
> 07-08 10:39:21.037  6419  6419 F DEBUG   : ABI: 'arm64'
> 07-08 10:39:21.037  6419  6419 F DEBUG   : Timestamp: 2020-07-08 10:39:21-0600
> 07-08 10:39:21.038  6419  6419 F DEBUG   : pid: 3066, tid: 3121, name: Thread-6  >>> com.example.VulkanLayerValidationTests <<<
> 07-08 10:39:21.038  6419  6419 F DEBUG   : uid: 11995
> 07-08 10:39:21.038  6419  6419 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20
> 07-08 10:39:21.038  6419  6419 F DEBUG   : Cause: null pointer dereference
> 07-08 10:39:21.038  6419  6419 F DEBUG   :     x0  0000006fb55d4de0  x1  0000006fb55e4f90  x2  0000006fb55e5000  x3  0000000000000008
> 07-08 10:39:21.038  6419  6419 F DEBUG   :     x4  000000702b1e0490  x5  0000007031a6f2c1  x6  2d44495556236c6d  x7  7265666675426b56
> 07-08 10:39:21.038  6419  6419 F DEBUG   :     x8  0000000000000000  x9  01ad4e45b690b59a  x10 0000000000000001  x11 0000000000000000
> 07-08 10:39:21.038  6419  6419 F DEBUG   :     x12 0000000000000000  x13 0000000000000018  x14 0000000000000000  x15 0000006fb53ddf40
> 07-08 10:39:21.038  6419  6419 F DEBUG   :     x16 000000701de75be0  x17 00000070c2e2cae0  x18 00000000dac0c8b4  x19 0000006fb55d4dd0
> 07-08 10:39:21.038  6419  6419 F DEBUG   :     x20 000000702b1e06d8  x21 000000702b1e0558  x22 0000006fb53ddf40  x23 0000006fb55d4de0
> 07-08 10:39:21.038  6419  6419 F DEBUG   :     x24 000000702b1e0558  x25 0000006fb53ddf80  x26 000000702b1e1020  x27 000000702b1e1020
> 07-08 10:39:21.038  6419  6419 F DEBUG   :     x28 0000006fd06e5dd8  x29 000000702b1e05e0
> 07-08 10:39:21.038  6419  6419 F DEBUG   :     sp  000000702b1e04d0  lr  000000701c17349c  pc  000000701c1734a8
> 07-08 10:39:21.051  6419  6419 F DEBUG   : 
> 07-08 10:39:21.051  6419  6419 F DEBUG   : backtrace:
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #00 pc 0000000000aa34a8  /vendor/lib64/egl/libGLES_mali.so (vkCreateBufferView+136) (BuildId: 2074cca0c239c545a7bd2396c71003a9)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #01 pc 00000000008e8548  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVkLayer_khronos_validation.so (BuildId: e36858687225552a9b56153e0634bed80d0a9de9)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #02 pc 000000000092ca74  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVkLayer_khronos_validation.so (BuildId: e36858687225552a9b56153e0634bed80d0a9de9)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #03 pc 000000000001e19c  /system/lib64/libvulkan.so (vulkan::api::(anonymous namespace)::CreateBufferView(VkDevice_T*, VkBufferViewCreateInfo const*, VkAllocationCallbacks const*, VkBufferView_T**)+180) (BuildId: d569637329ba16330d390540dee0e601)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #04 pc 00000000001d447c  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVulkanLayerValidationTests.so (BuildId: f2c8c6466ab5bcc1d071a56a0d8eec4e9af25de7)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #05 pc 00000000002416d8  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVulkanLayerValidationTests.so (BuildId: f2c8c6466ab5bcc1d071a56a0d8eec4e9af25de7)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #06 pc 00000000003b6014  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVulkanLayerValidationTests.so (testing::Test::Run()+384) (BuildId: f2c8c6466ab5bcc1d071a56a0d8eec4e9af25de7)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #07 pc 00000000003b72cc  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVulkanLayerValidationTests.so (testing::TestInfo::Run()+396) (BuildId: f2c8c6466ab5bcc1d071a56a0d8eec4e9af25de7)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #08 pc 00000000003b786c  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVulkanLayerValidationTests.so (testing::TestCase::Run()+248) (BuildId: f2c8c6466ab5bcc1d071a56a0d8eec4e9af25de7)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #09 pc 00000000003c05c4  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVulkanLayerValidationTests.so (testing::internal::UnitTestImpl::RunAllTests()+1080) (BuildId: f2c8c6466ab5bcc1d071a56a0d8eec4e9af25de7)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #10 pc 00000000003c0158  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVulkanLayerValidationTests.so (testing::UnitTest::Run()+164) (BuildId: f2c8c6466ab5bcc1d071a56a0d8eec4e9af25de7)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #11 pc 00000000001e07e0  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVulkanLayerValidationTests.so (BuildId: f2c8c6466ab5bcc1d071a56a0d8eec4e9af25de7)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #12 pc 00000000003a4030  /data/app/com.example.VulkanLayerValidationTests-urdkJLiIetthzYzbCVJoCg==/lib/arm64/libVulkanLayerValidationTests.so (BuildId: f2c8c6466ab5bcc1d071a56a0d8eec4e9af25de7)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #13 pc 00000000000e3b14  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 220051b49364b1c2da3adf10c30832cc)
> 07-08 10:39:21.051  6419  6419 F DEBUG   :       #14 pc 0000000000085330  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 220051b49364b1c2da3adf10c30832cc)
> 07-08 10:39:21.169  5811  8029 E BartenderActivityManager: BarTender: pid : 3789 cached=true abnormal=false kill=false stay=false release=false

**Comment by janharaldfredriksen-arm** [comment]
@mark-lunarg - Thanks. Found & fix a bad bug. Should be better now, I hope.

**Comment by mark-lunarg** [comment]
Running through the test farm again...

**Comment by mark-lunarg** [comment]
Thanks @janharaldfredriksen-arm!

**Pull request merged**
