### PR TITLE
Revert "Add Validation for VK_KHR_create_renderpass2"

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
Reverts KhronosGroup/Vulkan-ValidationLayers#357

Issues with Android 8.x CI testing.

### CODE REVIEW

**Comment by jzulauf-lunarg** [comment]
@Tobski crashes on tests

VkLayerTest.RenderPassEndBeforeFinalSubpass
VkLayerTest.RenderPassDestroyWhileInUse

**Comment by cnorthrop** [comment]
I think these were known failures that skipped our filters due to renaming tests.

**Comment by jzulauf-lunarg** [comment]
Filters to be updated to eliminate failures in renamed tests.

**Comment by Tobski** [comment]
Oh - so is this OK then? How come I didn't see this in the CI for the PR btw - is there some extra CI that you only run on master?

**Comment by jzulauf-lunarg** [comment]
@tobski -- Yes, there are some non-public CI environments, this one with a known-failures list that filters by testname.  The changed test names happened to be on that list.

The moral is "don't change test names without checking with all CI environments and maybe not even then."

**Pull request closed without merging**
