### PR TITLE
[WIP] Allow dependencies to be in the external/ folder.

### PR DESCRIPTION
**Pull request by dj2**
This CL allows placing SPIRV-Tools, SPIRV-Headers, GLSLang and
Vulkan-Headers into the external/ folder instead of installing.

### CODE REVIEW

**Comment by sl1pkn07** [comment]
https://github.com/KhronosGroup/Vulkan-Loader/pull/363

need inplement also this in VVL if merge this PR

**Comment by dj2** [comment]
The validation files don't appear to reference the VulkanHeaders VERSION values so that change shouldn't be needed.

**Comment by dj2** [comment]
This seems to break the CI on linux but I'm not sure why? Is there something I'm missing here?

**Comment by sl1pkn07** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/6c33edd0e38499ad0a54f73140cd266f5d417bd9/tests/CMakeLists.txt#L109

maybe is ` ${VulkanHeaders_INCLUDE_DIRS}`

?

https://github.com/KhronosGroup/Vulkan-Loader/search?q=VulkanHeaders_INCLUDE_DIR&unscoped_q=VulkanHeaders_INCLUDE_DIR
https://github.com/KhronosGroup/Vulkan-Loader/search?q=VulkanHeaders_INCLUDE_DIRS&unscoped_q=VulkanHeaders_INCLUDE_DIRS

example taked from vulkan-loader

**Comment by dj2** [comment]
The bots don't use the externals/ version of any of these. This should have no change on how the bots operate as they still install and use the installed version.

**Comment by sl1pkn07** [comment]
the bots show 

~~~
-- Found Threads: TRUE  
-- Using Vulkan headers from Vulkan::Headers target
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
~~~

the normal outpus is somethinkg like

~~~
-- Found VulkanHeaders: brawbraw/Vulkan-Headers/build/install/include  
-- Found VulkanRegistry: brawbraw/Vulkan-Loader/Vulkan-Headers/build/install/share/vulkan/registry  
~~~


because

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/66a8c391bc062219194bad9037ce70fa2ea7d98a/cmake/FindVulkanHeaders.cmake#L78-L84

?

**Comment by dj2** [comment]
Looking at this CL vs a previous one, you're right, this is getting Vulkan::Headers defined, I just don't know where it would be coming from? There should be nothing checking out the headers into `externals/` so why does moving the externals folder `add_subdirectory` up change how the build works? And, if Vulkan::Headers is defined .... why aren't the rest of the bits setup as usual?

Ah, ok, now I see, this repo runs the update_deps script from the `VulkanLoader` which places the Headers into the externals/ folder. Although, I'm still confused as to why the build doesn't work as it works correctly here with the headers in external

**Comment by sl1pkn07** [comment]
maybe for this?

https://github.com/KhronosGroup/Vulkan-Loader/search?q=VulkanHeaders_INCLUDE_DIR&unscoped_q=VulkanHeaders_INCLUDE_DIR
https://github.com/KhronosGroup/Vulkan-Loader/search?q=VulkanHeaders_INCLUDE_DIRS&unscoped_q=VulkanHeaders_INCLUDE_DIRS

seems, if the VH is taked from VL, the test of VVL the VulkanHeaders_INCLUDE_DIR is not set because is VulkanHeaders_INCLUDE_DIRS

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/tests/CMakeLists.txt#L109

**Comment by dj2** [comment]
You're probably right, I wonder why it works locally. I'll see if I can sort it out later. Thanks a lot for the help.

**Comment by mark-lunarg** [comment]
Changed to Work-In-Progress until things are passing.  Thanks!

**Comment by dj2** [comment]
Hm, there is a conflict here I don't know if I can work out. The validation layer bots run the update_deps script from the loader which checks out code into the `external` folder.

That code is then all built and the layers are setup to use the 'installed' version of the headers. But, this could would then also pickup that folder existing and do an `add_subdirectory` and now we have installed stuff in there and some of the paths are pulling from there.

So, either the loader `update_deps` script would need to use a folder outside of external or this would need to checkout the headers to something other then `vulkan-header` folder.  The first is probably a non-starter as that would cause everyones checkout to need to update deps again and rebuild the headers. The second could work but would be weird to have a `vk-headers` folder.

**Comment by mark-lunarg** [comment]
Hey guys, is this still in progress? There've been some efforts recently in this area...

**Comment by dj2** [comment]
Sorry, I got stalled out with the issue I mentioned in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1652#issuecomment-618468862. I don't know how to get around that as the current system will break anyone who has compiled the libraries into the `external` folder.

**Comment by dj2** [comment]
I'm closing this to move out of the queue for now. I don't know how best to resolve the issue I mentioned above.

**Pull request closed without merging**
