### PR TITLE
WIP  Prototype of thread_local persistent state template/approach

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
See caveats in TlsGuard declaration.

Please review the following protoype approach for inter-phase (i.e. Validation -> Record persistent state.  Uses thread_local static members, and uses optional to avoid dynamic allocations. 

Includes one simple example usage (which works). See caveats in TlsGuard declaration.

### CODE REVIEW

**Review by mark-lunarg — APPROVED** [review]
This looks awesome.  It will really simplify things and open the door for new optimizations!  🥇

**Comment by jeremyg-lunarg** [comment]
Yep this is neat! Would we want to use this to clean up the existing stuff in chassis.cpp where various CreateInfos get changed before being sent down to the ICD?

**Comment by mark-lunarg** [comment]
@jeremyg-lunarg, yes!  There used to be even more places where we saved data from the validate step for the record step, but since the current mechanism was so ugly we just ate the perf cost.  There's still the issue that it means the validate step is required in these cases, maybe that's not a big issue or maybe there needs to be another step before validate to grab the state.  Either way, it's a big improvement.

**Comment by ncesario-lunarg** [comment]
Yep, very cool!

**Comment by jzulauf-lunarg** [comment]
latest change to ensure the approach builds clean everywhere.

**Comment by jzulauf-lunarg** [comment]
committed as part of syncval submit time validation work

**Pull request closed without merging**
