### PR TITLE
layers: Set workgroup scalar block layout in SPIR-V validator

### PR DESCRIPTION
**Pull request by cmarcelo**
Used by VK_KHR_workgroup_memory_explicit_layout.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@sfricke-samsung?

**Comment by sfricke-samsung** [comment]
Seems correct, as long as the current `spirv-val` supports the `--workgroup-scalar-block-layout` setting https://github.com/KhronosGroup/SPIRV-Tools/pull/4128 this seems correct to me.

**Comment by ncesario-lunarg** [comment]
Running through [internal CI](http://erusea:4040/8304).

**Review by ncesario-lunarg — APPROVED** [review]
LGTM!

**Pull request merged**
