### PR TITLE
layers: Add support for video core and decode extensions

### PR DESCRIPTION
**Pull request by aqnuep**
Extensions covered:

- VK_KHR_video_queue
- VK_KHR_video_decode_queue
- VK_KHR_video_decode_h264
- VK_KHR_video_decode_h265

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
@aqnuep CI looks good except for the following on our nvidia HW:
```
[ RUN      ] VkVideoLayerTest.CreateSessionUnsupportedProfile
C:\j\vz0\Debug64\Vulkan-ValidationLayers\tests\vkerrormonitor.cpp(162): error: Failed
Did not receive expected error 'VUID-VkVideoSessionCreateInfoKHR-pVideoProfile-04845'
C:\j\vz0\Debug64\Vulkan-ValidationLayers\tests\vkerrormonitor.cpp(106): error: Failed
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x1a6b7445b30, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0x43ee850000001d0d, type = VK_OBJECT_TYPE_VIDEO_SESSION_KHR; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x1a6b7445b30[], VkVideoSessionKHR 0x43ee850000001d0d[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
```

**Comment by aqnuep** [comment]
> @aqnuep CI looks good except for the following on our nvidia HW:

That's due to using an outdated driver. Please ask for @pdaniell-nv for their latest driver which has this fix.

**Comment by KarenGhavam-lunarG** [comment]
> That's due to using an outdated driver. Please ask @pdaniell-nv for their latest driver which has this fix.

We just got an updated driver from Piers last Thursday that he said had all the latest video fixes.

**Comment by aqnuep** [comment]
> > That's due to using an outdated driver. Please ask @pdaniell-nv for their latest driver which has this fix.
> 
> We just got an updated driver from Piers last Thursday that he said had all the latest video fixes.

This was a regression that got fixed 2 days ago.

**Comment by pdaniell-nv** [comment]
The latest public beta driver https://developer.nvidia.com/vulkan-driver has the fix.

**Comment by ncesario-lunarg** [comment]
Thanks @pdaniell-nv.

@aqnuep We're on hold for now as we're unable to get our CI drivers updated, but as soon as that's done we should be able to proceed. Trying out the latest public beta, all of the video extension tests that run (there are a few that are skipped on my platform) look good.

**Comment by aqnuep** [comment]
> @aqnuep We're on hold for now as we're unable to get our CI drivers updated, but as soon as that's done we should be able to proceed. Trying out the latest public beta, all of the video extension tests that run (there are a few that are skipped on my platform) look good.

That's expected. AFAIK no implementation supports protected content decoding yet, hence those are skipped, as well as some other tests which are not applicable to the NVIDIA implementation (like the DISTINCT output mode which is only supported on the AMD implementation). In general, there are differences between the set of test cases skipped on various driver implementations due to capability differences.

**Comment by jeremyg-lunarg** [comment]
Internal CI testing passed. Our NV test machine was upgraded to use this driver version:
```
Driver Name = NVIDIA
Driver Info = 527.97
```

**Comment by aqnuep** [comment]
> Internal CI testing passed. Our NV test machine was upgraded to use this driver version:
> 
> ```
> Driver Name = NVIDIA
> Driver Info = 527.97
> ```

I've rebased the PR so it no longer has any conflicts.

I guess this is ready to be merged. Right?

**Comment by jeremyg-lunarg** [comment]
> I've rebased the PR so it no longer has any conflicts.
> 
> I guess this is ready to be merged. Right?

Yes! Here it goes...

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM.

**Comment by jeremyg-lunarg** [comment]
There's another, very minor, merge conflict that snuck in to cmd_buffer_state.h. I'd fix it for you and merges but maintainer pushes are disabled on your repo.

Also, the year change will trigger an error from our copyright check which I consider a false positive since you wrote the code in 2022. I will override that failure. I'm working a fix to the script to handle year changes more correctly. Happy new year!

**Comment by aqnuep** [comment]
> There's another, very minor, merge conflict that snuck in to cmd_buffer_state.h. I'd fix it for you and merges but maintainer pushes are disabled on your repo.

No worries, I rebased it and pushed an update.

> Also, the year change will trigger an error from our copyright check which I consider a false positive since you wrote the code in 2022. I will override that failure. I'm working a fix to the script to handle year changes more correctly. Happy new year!

Thanks for the review and everything, and Happy New Year to you too!

**Pull request merged**
