### PR TITLE
Added support for vkCmdCopyImage VUID

### PR DESCRIPTION
**Pull request by sfricke-samsung**
VUID-VkImageCopy-srcImage-01789

> If the calling command’s srcImage or dstImage is of type VK_IMAGE_TYPE_2D, then extent.depth must be 1.

VUID-VkImageCopy-srcImage-01790

> If both srcImage and dstImage are of type VK_IMAGE_TYPE_2D then extent.depth must be 1.

VUID-VkImageCopy-srcImage-01791

> If the calling command’s srcImage is of type VK_IMAGE_TYPE_2D, and the dstImage is of type VK_IMAGE_TYPE_3D, then extent.depth must equal to the layerCount member of srcSubresource.

VUID-VkImageCopy-dstImage-01792

> If the calling command’s dstImage is of type VK_IMAGE_TYPE_2D, and the srcImage is of type VK_IMAGE_TYPE_3D, then extent.depth must equal to the layerCount member of dstSubresource.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by mark-lunarg** [comment]
I'm a little unsure about the APIVersion checking with the maintenance1 enables, @Tony-LunarG is gonna check that over for us.

**Comment by sfricke-samsung** [comment]
ok, to my knowledge when making this PR the `VK_KHR_maintenance1` became core in 1.1 so only the devices running 1.0 without it enabled fall into the pre-maintenance conditions. Definitely a nasty legacy VU conditional check for the VVL

**Comment by Tony-LunarG** [comment]
This extension promotion should already be handled in device_extensions.InitFromDeviceCreateInfo, but I still see this check pattern elsewhere in existing code.  Was there a case where you found the check for api_version >= VK_API_VERSION_1_1 to be necessary?  I don't think it should and the other similar checks should someday be reduced to only checking the extension.

**Comment by mark-lunarg** [comment]
Just a note, whoever does the final rebase on this one will need to change the `log_msg()` calls to `LogError()` calls.  See the surrounding validation source for examples.

**Comment by sfricke-samsung** [comment]
@Tony-LunarG So to my knowledge if the device API version (which is what I assumed `api_version` is.. hope that's correct lol) is 1.1 greater then maintenance is core and all aspect of it are now required

**Comment by mark-lunarg** [comment]
@sfricke-samsung, while it may need to be revisited at some point, currently we do some under-the-covers stuff so that for a given API version, the promoted extensions for that version are marked as 'enabled' automatically.  In cases where we the extra context of _how_ it was enabled (through promotion or explicitlyby the app), there's another mechanism for that since it is much less prevalent. If I've misspoken, @Tony-LunarG can clarify.

**Comment by mark-lunarg** [comment]
BTW, @Tony-LunarG has volunteered to seeing that all these types of redundant checks in the repo are scrubbed.  Heh.

**Comment by sfricke-samsung** [comment]
ok, so here is the question that will settle this for me

I run the VVL on a driver that is version 1.1, but does not expose `VK_KHR_maintenance_1` in its list of extensions. According to the spec, how I read it, the VUID follows as if the extension is supported.

If I on this said driver and I remove the `api_version >= VK_API_VERSION_1_1` so it's now again

```
if (device_extensions.vk_khr_maintenance1) {
   // VUID-x
}
```

will the VVL still get to VUID-x?

**Comment by Tony-LunarG** [comment]
Yes, in vk_extension_helper.h, the code sets all of the 1.1 (and 1.2) promoted extensions to kEnabledByApiLevel, regardless of what was exposed by the driver or requested by the application
`           for (auto promoted_ext : V_1_1_promoted_device_apis) {
                info = get_info(promoted_ext);
                assert(info.state);
                if (info.state) this->*(info.state) = kEnabledByApiLevel;
            }
`

**Comment by sfricke-samsung** [comment]
Ok, so
1. That's awesome, and actually much easier than having to know the subtle details of when and what is promoted
2. My idea would to remove these then in my PR (I can do it later today, unless you are eager sooner) and then probably have a PR that goes and scrubs the rest of the code for this type of redundant check (probably make an issue for it)

**Comment by sfricke-samsung** [comment]
rebased and removed redundant 1.1 check

**Comment by Tony-LunarG** [comment]
I fixed up the log_msg calls and pushed to master

**Comment by sfricke-samsung** [comment]
> Just a note, whoever does the final rebase on this one will need to change the log_msg() calls to LogError() calls.

🤦‍♂ Thanks for the help getting this in!

**Pull request closed without merging**
