### PR TITLE
test: Added VK_NV_geometry_shader_passthrough

### PR DESCRIPTION
**Pull request by cmayer1**
Added positive layer test to make sure that the usage of
VK_NV_geometry_shader_passthrough does not cause any
errors.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@cmayer1, any chance you can rebase this please?

**Comment by cmayer1** [comment]
@mark-lunarg , I am OOO but will rebase on Monday when I am back.

**Comment by mark-lunarg** [comment]
Thanks! Running through CI.

**Comment by cmayer1** [comment]
rebased

**Comment by mark-lunarg** [comment]
Rebased again and running through CI.

**Comment by cmayer1** [comment]
@mark-lunarg thanks for reviewing.

**Pull request merged**
