### PR TITLE
layers: Add VK_KHR_uniform_buffer_standard_layout

### PR DESCRIPTION
**Pull request by gnl21**

### CODE REVIEW

**Comment by gnl21** [comment]
It looks like this isn't pulling a recent enough version of the headers in CI, but I don't know what I need to do about that. Could someone let me know? Thanks.

**Comment by KarenGhavam-lunarG** [comment]
The extension VK_KHR_uniform_buffer_standard_layout is in the 1.1.108 header but the 1.1.108 header has not yet been propagated to this repository. This takes several days at a minimum once the header is posted in Vulkan-Headers.

**Comment by mikew-lunarg** [comment]
When a header update is integrated into a dependent repo, there will be a
tag in that repo that matches the header tag.

For example: Vulkan-Headers has a "v1.1.108" tag, but the latest tag in
Vulkan-ValidationLayers is "v1.1.107".
After V-VL is updated, it will have a "v1.1.108" tag as well.

**Comment by mark-lunarg** [comment]
@gnl21, the 1.1.108 header updates have been pushed.  Can you rebase, separate the tests into a separate commit, and avoid the merge commits?  After your push I'll run the two new commits through CI. Thanks!

**Comment by gnl21** [comment]
Done, @mark-lunarg.

**Comment by mark-lunarg** [comment]
Sweet!  In the farm now.

**Comment by gnl21** [comment]
It looks like this is failing in CI because the version of SPIRV-Tools that it's using isn't new enough, but I can't find where that dependency is expressed. Strangely, everything builds fine on my test machine.

**Comment by jeffbolznv** [comment]
IIRC validation gets spirv-tools via glslang. So you'd need to update the glslang commit hash.

**Comment by gnl21** [comment]
Thanks, Jeff. I wondered about that, but it seemed a bit odd.

I've updated the known goods to revisions that I think will work, but I don't have any method for picking those revisions or testing on Android.

**Comment by mark-lunarg** [comment]
@gnl21, I have this passing on desktop platforms, but need to check with @cnorthrop about getting the Android glslang known-good updated.

**Comment by gnl21** [comment]
OK, thanks. Let me know if you need me to update anything.

**Comment by gnl21** [comment]
Any update on this, @mark-lunarg, @cnorthrop?

**Comment by mark-lunarg** [comment]
We need to get good glslang/spirv-tools versions for Android -- will talk to the responsible folks early next week.

**Comment by mark-lunarg** [comment]
Opened #1034 to get the right sprivtools/headers for Android to support this PR.

**Comment by mark-lunarg** [comment]
OK then.  Had to do an out-of-band Android K-G update, but after that landed was able to rebase, run through CI, and then push to Master.  Sorry it took so long -- thanks!

**Pull request closed without merging**
