### PR TITLE
Fix wsi format props

### LINKED ISSUE #1764: Format Features of Swapchain Image?
Hi, I just cloned the latest validation layers.
I have noticed a new validation error:
`
Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-blendEnable-02023 ] Object 0: handle = 0xb3deb0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x1991022a | vkCreateGraphicsPipelines(): pipeline.pColorBlendState.pAttachments[0].blendEnable is VK_TRUE but format VkImage 0x40000000004[] associated with this attached image (VK_FORMAT_B8G8R8A8_SRGB) does not support VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT. The Vulkan spec states: If rasterization is not disabled and the subpass uses color attachments, then for each color attachment in the subpass the blendEnable member of the corresponding element of the pAttachment member of pColorBlendState must be VK_FALSE if the attached image's format features does not contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-blendEnable-02023)
`
The image it is complaining about is a Swapchain Image. I checked the spec and it doesn't seem to say anything about format features of a Swapchain Image. Are you taking format features of Swapchain Images in consideration here? Is this a spec bug, a validation bug or a driver bug?
If I disable `blendEnable` for that image, I lose blending. It works perfectly without the validation layer.
NVIDIA drivers 4.40 on Ubuntu 20.04. I also had the same problem on 19.04, 4.35 driver.

### PR DESCRIPTION
**Pull request by krOoze**
fix #1764

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Running through CI.

**Comment by mark-lunarg** [comment]
@krOoze, failed similarly on all internal CI HW platforms:

```
[ RUN      ] VkPositiveLayerTest.SwapchainImageFormatProps
/home/lunarg/.jenkins/w8/64-bit/Debug/tests/vkpositivelayertests.cpp:9440: Failure
Expected equality of these values:
  VK_SUCCESS
    Which is: 0
  resolved_err
    Which is: 5
VK_INCOMPLETE
[  FAILED  ] VkPositiveLayerTest.SwapchainImageFormatProps (312 ms)
```

**Comment by krOoze** [comment]
Right, once again I forgot about `VK_INCOMPLETE`. Fixt.

**Comment by mark-lunarg** [comment]
Sending on another trip through CI!

**Pull request merged**
