### PR TITLE
Validate VK_EXT_fragment_density_map2

### PR DESCRIPTION
**Pull request by janharaldfredriksen-arm**

### CODE REVIEW

**Comment by janharaldfredriksen-arm** [comment]
Note: This depends on #2001. I'll update this when that has landed.

**Comment by janharaldfredriksen-arm** [comment]
Tests passing finally. (Lots of fun tracking down uninitialized state in the Mock ICD :))

I think this is ready for review now, so de-WIP.

CC: @mark-lunarg since you looked at earlier drafts of this.

**Comment by mark-lunarg** [comment]
Running through the test farm.

**Comment by mark-lunarg** [comment]
Thanks a bunch!

**Pull request merged**
