### PR TITLE
layers: Some cleanup and comments for GPU-Val

### PR DESCRIPTION
**Pull request by sjfricke**
In my effort to learn more about the GPU-Validation code to add more runtime SPIR-V validation I had some house cleaning fixes decided to push here

### CODE REVIEW

**Review by ncesario-lunarg — APPROVED** [review]
This LGTM, but really depends on @Tony-LunarG (and the new GPUAV expert: @jeremyg-lunarg!)

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM.

**Comment by jeremyg-lunarg** [comment]
@sjfricke we'll need to coordinate to avoid conflicts. I sent you some details about what I'm planning in Khronos slack

**Review by Tony-LunarG — APPROVED** [review]
LGTM - thanks for the clean up!

**Pull request merged**
