### PR TITLE
layers: Update ValidationStateTracker for synchronization2

### PR DESCRIPTION
**Pull request by jeremyg-lunarg**
layers: Update ValidationStateTracker for synchronization2
    
    Add all entry points in the extension. Refactor state tracking
    for vkQueueSubmit() and vkQueueBindSparse() so that they can
    share code with vkQueueSubmit2KHR().
    
    Change-Id: Ifb81891a6b9bea2d1c68550f5567b841b056ec3a

### CODE REVIEW

**Comment by jeremyg-lunarg** [comment]
Now that the header update is merged, can I please get some review on this change? Thanks!

**Review by ncesario-lunarg — APPROVED** [review]
LGTM, though it would probably good if someone like @jzulauf-lunarg took a look. If you're confident with this change @jeremyg-lunarg, :ship:

**Comment by ncesario-lunarg** [comment]
Looks like we should try to move our appveyor builds to Actions as well...

**Comment by jeremyg-lunarg** [comment]
> Looks like we should try to move our appveyor builds to Actions as well...

This failure looks not-real.

**Comment by ncesario-lunarg** [comment]
Yeah, looks like a network issue.

**Comment by jeremyg-lunarg** [comment]
Internal CI finally finished. Job 4075 passed all but Android. Reran that platform manually in Job 561 and that passed.

**Pull request merged**
