### PR TITLE
layers: Refactor shader location validation

### PR DESCRIPTION
**Pull request by krOoze**
#1106

### CODE REVIEW

**Comment by krOoze** [comment]
@mark-lunarg Will probably fail one test case. I fail to reproduce localy, so I welcome any info though.

**Comment by jeremy-lunarg** [comment]
I see an assert in shader_validation.cpp:568 when I run VkLayerTest.PipelineWrongBindPointCompute. Do you see that @krOoze ?

**Comment by krOoze** [comment]
Yes; that what I spoke about above. Can't reproduce locally, which is bit vexing. Probably I need to setup some specific device profile for the mock or something. I will give it further look tomorrow.

**Comment by jeremy-lunarg** [comment]
Sounds good. I can reproduce. I will take a look as well. Thanks.

**Comment by krOoze** [comment]
@jeremy-lunarg Right. Thanks!

**Pull request merged**
