### PR TITLE
corechecks: Validation for VK_EXT_border_color_swizzle

### PR DESCRIPTION
**Pull request by pdaniell-nv**

### CODE REVIEW

**Comment by pdaniell-nv** [comment]
I didn't add a test for this one since it was so trivial, but happy to add one if you think it's needed. Also a large part of the diff is because it put the existing custom border color validation under `if (pCreateInfo != nullptr) {` which I believe is where it was meant to be.

**Review by jeremyg-lunarg — COMMENTED** [review]
The validation changes look good to me, but if it is easy to add a test case that would be nice. Thanks!

**Comment by pdaniell-nv** [comment]
> The validation changes look good to me, but if it is easy to add a test case that would be nice. Thanks!

I've added a test.

**Review by jeremyg-lunarg — APPROVED** [review]
LGTM

**Pull request merged**
