### PR TITLE
layers: Fix reading android settings bug

### LINKED ISSUE #2733: VK_LAYER_SETTINGS_PATH in android doesn't work due to the newline character fgets() introduces
**Describe the Issue**
The way "setprop VK_LAYER_SETTINGS_PATH " is being read in the GetEnvironment() function, it adds a newLine character at the end. fgets() is notorious for that.
Because of this, the settings file reading doesn't work.

**Valid Usage ID**
NA

**Environment:**
 - Android

**Additional context**
Remove the unwanted trailing newLine char that fgets() introduces.

--- a/layers/vk_layer_config.cpp
+++ b/layers/vk_layer_config.cpp
@@ -88,6 +88,8 @@ string GetEnvironment(const char *variable) {
     if (pPipe != nullptr) {
         char value[256];
         fgets(value, 256, pPipe);
+        // Removing trailing newline character from fgets() input
+        value[strcspn(value, "\n")] = 0;
         pclose(pPipe);

         // Make sure its not an empty line

### PR DESCRIPTION
**Pull request by ncesario-lunarg**
Fixes reading setprop values on Android.

Closes #2733

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
@sfricke-samsung @lunarpapillo @johnzupin Adding you guys as I think you use this feature, but I have yet to make use of it myself. Think this is ok, but just double checking.

**Review by lunarpapillo — COMMENTED** [review]
What's the original bug?  Looking at the original code, it's unclear how this ever worked, as there would always be a terminal newline.

The code change looks fine; but the change in behavior is concerning, if there is a caller that expects the terminal newline and won't ever see it now.

Offhand, why are we using a `getprop` process instead of calling the native `property_get()` function from `cutils/properties.h`?

**Comment by ncesario-lunarg** [comment]
Good questions @lunarpapillo! I believe @sfricke-samsung was the original author, so I'm guessing the original code worked for him which is why I'm hesitant to change it.

Where/what is `cutils/properties.h`?

**Comment by shakti-hub** [comment]
> The original bug was that the Android settings were _never_ working, right?
> 
> The code change looks fine; but the change in behavior is concerning, if there is a caller that expects the terminal newline and won't ever see it now. (Of course, if it never worked, that's not a concern.)
> 
> Do we have a test case that passes with this change and fails without it?
> 
> Offhand, why are we using a `getprop` process instead of calling the native `property_get()` function from `cutils/properties.h`?

The settings file is getting read and parsed after the fix.
Verified with khronos_validation.message_id_filter on one filter. 
For example, if I set the below line in the vk_layer_settings.txt, I don't see any Validation messages pertaining to this VUID.
Otherwise, I see a bunch of these, which I am not interested in eliminating.

khronos_validation.message_id_filter       = "VUID-VkImageCreateInfo-pNext-02397"

**Comment by sfricke-samsung** [comment]
So I have many thoughts on this now

-----
1. So yes, this PR is a proper fix, there are only 3 spots android uses this, but the other two are to query [debug.vvl.forcelayerlog](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2651) and the [ro.build.version.sdk](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2294) (where I introduced this function/bug)... both cases are only checked for a `int` and why it works for them... I see the issue is when the layer code goes

```
env_path.append("/vk_layer_settings.txt");
```

the newline is kicking in and causing the issue... so for that, yes this fix seems good

-----

2. the `getprop` vs `property_get` is probably slightly out of scope for this fix, but if it is changed, I would rather have it consistent across the tools ecosystem somewhat

-----

3. <Slight rant>  Not sure why the validation layers is asking the app to use `setprop VK_LAYER_SETTINGS_PATH` and not something like `setprop debug.vvl.setting_path` to be more "android-like"... also it could then offer doing individual settings like [api_dump_layer](https://vulkan.lunarg.com/doc/view/latest/windows/api_dump_layer.html) does, as an example, it has the users go

```
adb shell "setprop debug.apidump_log_filename '/sdcard/Android/vk_apidump.txt'"
```

and we could offer the same in the validation layers... again, out of scope

-----

4. @shakti-hub Curious why you want to filter `VUID-VkImageCreateInfo-pNext-02397`... if you are dealing with external AHB formats then it is important you follow the spec

> Vulkan can import Android hardware buffers that have external formats, but since the image contents are in an undiscoverable and possibly proprietary representation, images with external formats **must** only be used as sampled images, **must** only be sampled with a sampler that has Y′CBCR conversion enabled, and **must** have optimal tiling.

So not sure why you need any other `VkImageUsageFlags` as there is nothing else valid/legal an Android Vulkan driver out there  will be able to do with that private format

**Comment by ncesario-lunarg** [comment]
Ok, if there are no objections then, I'll go ahead and merge this, then create an issue to discuss/track some of the other changes @sfricke-samsung brought up.

**Comment by ncesario-lunarg** [comment]
Created #2742 to track the Android issues.

**Pull request merged**
