### PR TITLE
layers: ValidateCooperativeMatrix only if support

### PR DESCRIPTION
**Pull request by sfricke-samsung**
cc: @jeffbolznv to make sure I am not missing anything obvious here.

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
Running through [internal CI](http://erusea:4040/8430).

**Review by ncesario-lunarg — APPROVED** [review]
LGTM; will wait for @jeffbolznv's input before merging.

**Comment by jeffbolznv** [comment]
Seems fine, I guess. Is this just an optimization or was there a functional issue?

**Comment by sfricke-samsung** [comment]
Its an optimization. I have tried reducing the number of passes we were making looping the Module instructions and realized it was doing it in this function, regardless of there being no chance to have anything to validate

**Pull request merged**
