### PR TITLE
[WIP] Validate VK_KHR_pipeline_executable_properties

### PR DESCRIPTION
**Pull request by sfricke-samsung**
Add some missing VUIDs not added from original PR for VK_KHR_pipeline_executable_properties

VUID-vkGetPipelineExecutableInternalRepresentationsKHR-pipelineExecutableInfo-03276
VUID-vkGetPipelineExecutableInternalRepresentationsKHR-pipeline-03277
VUID-vkGetPipelineExecutableStatisticsKHR-pipeline-03273
VUID-vkGetPipelineExecutablePropertiesKHR-pipeline-03271

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Any reason not to add tests?

**Comment by sfricke-samsung** [comment]
The original didn't #1131 

nothing stopping me other then laziness, if we want can always add some

**Comment by mark-lunarg** [comment]
@sfricke-samsung, if it's not overly involved, at least for each type of the added ones please?  It was my mistake to not ask for the other tests.

**Comment by sfricke-samsung** [comment]
@mark-lunarg 

So I added 2 test, but the `ValidatePipelineExecutablePropertiesMultiDevice` is crashing (really the layer isn't working correctly)

Debugging it I found the issue is the 

```
const PIPELINE_STATE *pipeline_state = GetPipelineState(pExecutableInfo->pipeline);
```

is returning `nullptr`

So the test creates a `VkPipeline` with `VkDevice a` which I can see it add to the `ValidationStateTracker::PostCallRecordCreateComputePipelines` call, but when `GetPipelineState` is called later (from `VkDevice b`) I notice the instance of `ValidationStateTracker` when the `GetPipelineState` is called is different from when it was recorded... I haven't looked to hard into the chassis, but I thought it was a shared instance level class so not sure why there are 2 instances of the class

**Comment by mark-lunarg** [comment]
@sfricke-samsung -- each device gets its own statetracker (if needed) and nothing gets shared between devices, at least directly.  To get to the data of a device outside your current context, see `CoreChecks::PostCallRecordCreateDevice` as an example.  You can use GetLayerDataPtr to get the device validation object, use that to pick the particular validation object you need, and access it that way.  The `object_tracker_utils.cpp` unit also has several examples.

**Comment by sfricke-samsung** [comment]
ok, so I realize now I was misled from the fact `CMD_BUFFER_STATE` has a `VkDevice` which after tracking it around, seems like it never actually gets used (an issue for another PR I guess lol).

I will look into the object_tracker_utils examples and rework the PR to properly save the VkDevice state

**Comment by mark-lunarg** [comment]
@sfricke-samsung, closing this for now due to inactivity -- when there's time later we can reopen this PR or create a new one -- thanks!

**Pull request closed without merging**
