### PR TITLE
Simplify render pass stage validation

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by mark-lunarg** [comment]
Rebased and running through CI.

**Comment by omnigoat** [comment]
Hi! So this validation rejects subpass dependencies that look like the explicit versions of the implicit external subpasses as defined in the spec: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap7.html#renderpass-creation:

You'll note `VK_PIPELINE_STAGE_ALL_COMMANDS_BIT` - either the spec is worded badly or the validation layer should accept VK_PIPELINE_STAGE_ALL_COMMANDS_BIT as valid.

```
VkSubpassDependency implicitDependency = {
    .srcSubpass = VK_SUBPASS_EXTERNAL;
    .dstSubpass = firstSubpass; // First subpass attachment is used in
    .srcStageMask = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
    .dstStageMask = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;
    .srcAccessMask = 0;
    .dstAccessMask = VK_ACCESS_INPUT_ATTACHMENT_READ_BIT |
                     VK_ACCESS_COLOR_ATTACHMENT_READ_BIT |
                     VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |
                     VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT |
                     VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
    .dependencyFlags = 0;
};
```

**Comment by krOoze** [comment]
@omnigoat It must be some kind of a bug then. This patch should only affect non-`VK_SUBPASS_EXTERNAL` stuff. Can you give me the specific arguments, and the error msg?
Any flags should be allowed with `VK_SUBPASS_EXTERNAL`.

**Comment by krOoze** [comment]
@omnigoat Ups, I read it wrong; disregard previous msg. Yea, I cannot be sure either. You need to petition [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs/issues). IIRC some were even against `ALL_GRAPHICS`. On the other hand `ALL_COMMANDS` says:

> `VK_PIPELINE_STAGE_ALL_COMMANDS_BIT` is equivalent to the logical OR of every other pipeline stage flag that is supported on the queue it is used with.

Which, if I took it literally, would make it possibly valid at Render Pass creation time (queue is not known). But then would make it invalid at submission if the queue is not Graphics-only.

**Comment by krOoze** [comment]
@omnigoat I piggy-backed this to my Issue https://github.com/KhronosGroup/Vulkan-Docs/issues/1020.

Meanwhile I am pretty sure I am missing some pipeline stages in here, but nobody complained yet... hmm.

**Pull request merged**
