### PR TITLE
layers: Add missing skip handling to commands

### LINKED ISSUE #1713: Can't run ToT tests on devsim (CI failing as well)
Noticed when rebasing some PR that they are not failing CI. I tried pulling down ToT, grabbed 137 headers and clean build and what not and get

```
./tests/vk_layer_validation_tests --devsim
[==========] Running 656 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 499 tests from VkLayerTest
[ RUN      ] VkLayerTest.InstanceExtensionDependencies
[       OK ] VkLayerTest.InstanceExtensionDependencies (14 ms)
[ RUN      ] VkLayerTest.InstanceBadStype
[       OK ] VkLayerTest.InstanceBadStype (5 ms)
[ RUN      ] VkLayerTest.InstanceDuplicatePnextStype
[       OK ] VkLayerTest.InstanceDuplicatePnextStype (7 ms)
[ RUN      ] VkLayerTest.InstanceFlags
[       OK ] VkLayerTest.InstanceFlags (5 ms)
[ RUN      ] VkLayerTest.InstanceAppInfoBadStype
[       OK ] VkLayerTest.InstanceAppInfoBadStype (5 ms)
[ RUN      ] VkLayerTest.InstanceValidationFeaturesBadFlags
[       OK ] VkLayerTest.InstanceValidationFeaturesBadFlags (10 ms)
[ RUN      ] VkLayerTest.InstanceBadValidationFlags
[       OK ] VkLayerTest.InstanceBadValidationFlags (9 ms)
[ RUN      ] VkLayerTest.DestroyInstanceAllocationCallbacksCompatibility
[       OK ] VkLayerTest.DestroyInstanceAllocationCallbacksCompatibility (6 ms)
[ RUN      ] VkLayerTest.DestroyInstanceHandleLeak
[       OK ] VkLayerTest.DestroyInstanceHandleLeak (7 ms)
[ RUN      ] VkLayerTest.PSOPolygonModeInvalid
Segmentation fault (core dumped)
```

Found `b41b9d0c3689232da2ff9ca63d59ad3da0569446` is last commit that works

Seems [Remove MockICD workarounds in instanceless](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/8f07f8b0cf2847f06c5a91ae9b6d564b943cc5f5)

Didn't fully grasp why we removed 

> // WORKAROUND: Subsequent tests crash when this is not called. MockICD or Loader bug

in the commit. Can't figure out what/where the fix is for this workaround instead. (or is there a new minimum version of the loader/MockICD needed now?)

cc @krOoze

### PR DESCRIPTION
**Pull request by krOoze**
Add missing skip handling of debug callback for `vkCreateInstance`.

Should fix #1713 and remove necessity for the workarounds in #810.

### CODE REVIEW

**Comment by sfricke-samsung** [comment]
confirms this fixes issues I had in #1713, but still fails things such as

```
./tests/vk_layer_validation_tests --devsim --gtest_filter=VkBestPracticesLayerTest.UseDeprecatedExtensions
Note: Google Test filter = VkBestPracticesLayerTest.UseDeprecatedExtensions
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from VkBestPracticesLayerTest
[ RUN      ] VkBestPracticesLayerTest.UseDeprecatedExtensions
Vulkan-ValidationLayers/tests/vkrenderframework.cpp:454: Failure
Expected equality of these values:
  VK_SUCCESS
    Which is: 0
  resolved_err
    Which is: -1000011001
VK_ERROR_VALIDATION_FAILED_EXT
Vulkan-ValidationLayers/tests/vkrenderframework.cpp:293: Failure
Expected: ((VkInstance)0) != (instance_), actual: NULL vs NULL
```

Curious to see if CI hits same issue

**Comment by krOoze** [comment]
@sfricke-samsung Hm 1:0 for the CI. I can't seem to be able to reproduce locally. No matter which profile I use, the test seems to be skipped because of Vulkan version.

**Comment by krOoze** [comment]
@sfricke-samsung It is a problem of the test, which tests `vkCreateInstance` but calls `InitFramework`, which does not tolerate failure. Fix pushed.

**Comment by mark-lunarg** [comment]
Looks like you've already addressed it, but the windows platforms were failing in VkLayerTest.seObjectWithWrongDevice.

**Comment by krOoze** [comment]
Not really, I just keep piling up workarounds...

**Comment by krOoze** [comment]
OK, skipping `vkDestroyInstance` requires some changes to devsim, mock, and probably loader too, so I suppose I am done here for the time being.

**Pull request merged**
