### PR TITLE
layers:fix for VUID-vkCmdTraceRaysNV-None-02700

### PR DESCRIPTION
**Pull request by souravpNV**
Missed updating this check when KHR versions were updated

### CODE REVIEW

**Comment by souravpNV** [comment]
@dgkoch please review

**Review by dgkoch — APPROVED** [review]
Seems reasonable.

**Comment by mark-lunarg** [comment]
Fixed commit message for you, running through CI.

**Review by mark-lunarg — APPROVED** [review]

**Comment by mark-lunarg** [comment]
Passed CI, rebased and pushed to Master.

**Comment by souravpNV** [comment]
Thanks @mark-lunarg

**Pull request closed without merging**
