### PR TITLE
Add better OpExecutionMode logic

### PR DESCRIPTION
**Pull request by sfricke-samsung**
On first step to fix the 2 open Entry Point issues, first fixed up how we check `OpExecutionMode` because execution modes are not tied to a single entry point

Also added a `VK_KHR_float_controls` to verify myself on this change

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
Running through [internal CI](http://erusea:4040/8440).

**Review by ncesario-lunarg — APPROVED** [review]
LGTM! I don't entirely understand why the use of `VK_KHR_shader_float_controls` is needed to test these changes, but I'm also not as familiar with this :)

**Comment by sfricke-samsung** [comment]
So inside `ValidateExecutionModes` we use the execution mode and make sure if a driver doesn't support `shaderSignedZeroInfNanPreserveFloat32` and the app uses `OpExecutionMode %main SignedZeroInfNanPreserve 32` it catches it

We didn't have tests for those VUs anyway and I wanted them before I modified the code checking them

**Comment by ncesario-lunarg** [comment]
👍 thanks for the explanation!

**Pull request merged**
