### PR TITLE
Add validation for VK_EXT_ycbcr_image_arrays

### PR DESCRIPTION
**Pull request by pdaniell-nv**
There is only one new VUID, which is to verify that the vkCreateImage arrayLayers is not larger than 1 if the format requires sampler ycbcr conversion and VK_EXT_ycbcr_image_arrays isn't enabled.

### CODE REVIEW

**Comment by tobine** [comment]
Looks like it may require a header update based on CI failure

**Comment by tobine** [comment]
Also format checker will probably complain about your commit message which needs a <51 char intro line w/ "layers:" prefix.

**Comment by mark-lunarg** [comment]
`vk_validation_error_messages.h` is a generated file -- if this extension is new for V1.1.102, it might need to wait until VVL known-good is updated for the 1.1.102 header update (at which time the error_messages header file will get automatically updated).  Adding @shannon-lunarg to the reviewers.

**Comment by pdaniell-nv** [comment]
> `vk_validation_error_messages.h` is a generated file -- if this extension is new for V1.1.102, it might need to wait until VVL known-good is updated for the 1.1.102 header update (at which time the error_messages header file will get automatically updated). Adding @shannon-lunarg to the reviewers.

Yes, this is new in 102. What's the ETA for updating the known-good is updated to 102+?

**Comment by shannon-lunarg** [comment]
The 102 header VVL changes are running through internal CI currently.

**Comment by shannon-lunarg** [comment]
An update:
The addition of the new `VK_EXT_metal_surface` extension has created a ripple effect throughout the related repos, so a modification to LunarG-VulkanTools is required before the Vulkan-ValidationLayers known-good update can be merged. (Note: The 102 known-good update did pass internal CI so at least we don't have to repeat that step!) Work is being done to address this and since this PR has already been approved, once everything is passing internal/external CI and the known-good has been updated I will go ahead and make sure your changes are tested and merged to master.

In the meantime, let me know if you have any questions!

**Comment by pdaniell-nv** [comment]
Thanks for the update. This PR isn't urgent so no need to rush on my behalf.

**Comment by shannon-lunarg** [comment]
@pdaniell-nv The ValidationLayers known-good has been updated for the 102 Vulkan specification. After rebasing, I tried to run your branch through our internal CI but this failed almost immediately due to recent changes in the repo. Instead of risking getting a wire crossed somewhere I will leave the rebasing and conflict resolutions up to you.

**Comment by mark-lunarg** [comment]
@pdaniell-nv -- the repo is going through a bit of churn right now, so I'll plan on rebasing this PR, probably Monday or Tuesday if it's alright with y'all.

**Comment by mark-lunarg** [comment]
Passed CI, pushed to Master.  Thanks @pdaniell-nv.

**Pull request closed without merging**
