### PR TITLE
[RFC] layers: Split parts of core_validation out

### PR DESCRIPTION
**Pull request by JasperNV**
This is a bikeshed proposal. Currently, core_validation.cpp is a single
file that is over 12,000 lines long. It takes a long time to compile,
can be exhausting to navigate, and some tools like IntelliSense can have
issues with its large size. Splitting it into multiple files isn't a
panacea for the above issues, but a small step towards a larger goal.

Here, I do drawdispatch as a simple example to show the idea itself and
build approval. It was small and self-contained and relatively
conflict-free. If this is well-received, I will do the work myself to
help split core_validation.cpp into multiple more files.

### CODE REVIEW

**Comment by JasperNV** [comment]
I don't have any specific goals for granularity -- I figured splitting up the current core_validation.cpp into around 7-8 files seemed about right given its current size. I was imagining one file per important API concept, grouped as needed -- `core_validation_buffer.cpp`, `core_validation_imagesampler.cpp`, `core_validation_descriptorset.cpp`, `core_validation_pipeline.cpp`.

I'll dig into the Android build issue.

**Comment by JasperNV** [comment]
Android build issues have been fixed

**Comment by JasperNV** [comment]
Quick ping on this?

**Comment by mark-lunarg** [comment]
This is fine by me, but I'd like the filename changed from core_validation_drawdispatch to just drawdispatch.  Is there more stuff planned to go into this file?

**Comment by JasperNV** [comment]
Nope. The motivation behind the name was to make it clear this was part of the core validation layer, not the other layers, since there's also the thread-safety, object-tracker, stateless-validation layers, etc.

**Comment by JasperNV** [comment]
Renamed to drawdispatch.cpp

**Comment by mark-lunarg** [comment]
For a little extra context, in a month or two there will no longer a core_validation layer.  There is a CoreChecks validation object, so that might be better, or maybe just cc_ or something instead.  I really like the idea, and it's cool if we come up with a scheme that we can use for all of them, but at that time we should rename the other files as well to get the same advantage.

**Comment by JasperNV** [comment]
Ah, that makes sense then. Any public documentation I can see about the proposed new structure for the layers?

**Comment by mark-lunarg** [comment]
The white-paper is in final review now and should be available in next week's SDK.  Most of it you can already see in the source -- the old layers have all been converted to `ValidationObjects` and get combined into the `khronos_validation` layer.  Going forward, there'll be one validation layer, and you can flip parts of it on and off at CreateInstance-time.  So this is really bending the idea of what a 'validation layers' means in this repo, and it seems like more terminology will be changing in the short-term as well.  And I love the idea of making it obvious what the source relates to just from the filename

**Comment by mark-lunarg** [comment]
Passed internal CI, good to go!

**Pull request merged**
