### PR TITLE
Add VkMemoryDedicatedAllocateInfo Support

### PR DESCRIPTION
**Pull request by sfricke-samsung**
Adds support for

- VUID-VkMemoryDedicatedAllocateInfo-image-01432
- VUID-VkMemoryDedicatedAllocateInfo-image-01433
- VUID-VkMemoryDedicatedAllocateInfo-image-01434
- VUID-VkMemoryDedicatedAllocateInfo-buffer-01435
- VUID-VkMemoryDedicatedAllocateInfo-buffer-01436
- VUID-VkMemoryDedicatedAllocateInfo-image-01797

### CODE REVIEW

**Comment by jeremy-lunarg** [comment]
Running through CI...

**Comment by sfricke-samsung** [comment]
@mark-lunarg Hey,

So I realized now that there is a Vulkan Spec bug (which I will be fixing) where for `01433` and `01435` it checks `VkMemoryRequirements::size` but imported Android Hardware Buffers don't use the [Get*MemoryRequirements calls](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1365) and this PR actually added false positives to android apps using this.

I will clean up all of this so don't worry, but my question is now that I have looked much closer how the Android scripts/logging are working, it seems this was falsely marked as "pass" because you see in the logcat and the out.txt file
```
VulkanLayerValidationTests: [ UNEXPECTED_ERR ] 'Validation Error: [ VUID-VkMemoryDedicatedAllocateInfo-image-01433 ] Object 0: handle = 0x79fb896bd0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd47f82b6 | Allocation Size (16384) needs to be equal to VkImage VkImage 0x30000000003[] VkMemoryRequirements::size (0)
```

and this is because the `VerifyFound`/`VerifyNotFound` calls don't actually error out. I am curious if this was conscience as I would rather have work arounds in the tests (working on with devices I have) instead of just letting them pass

**Comment by mark-lunarg** [comment]
@sfricke-samsung, this conscious decision was made because we have only a limited number of  Android devices in our test farm (half-a-dozen?), and though we could get tests running cleanly on those platforms we often missed platforms that would break for others, for instance, Google's test farm.  They'd get failures and their CI would be hosed until we fixed the unexpecteds.  So we allow unexpecteds on Android, and do periodic sweeps to fix the ones that crop up.

**Comment by sfricke-samsung** [comment]
@mark-lunarg that makes total sense! Sounds good, I am about to get a PR up that does a good amount of clean up as well. Just was curious as I am now about to start going on a good set of PR's related to the External AHB related items not covered...you know, everyone's favorite area of the spec :)

**Comment by mark-lunarg** [comment]
@sfricke-samsung, that's awesome.  Nearly all of the existing AHB coverage was created before there was any hardware, so it can use some attention -- thanks!

**Pull request merged**
