### PR TITLE
layers: Fix vk_layer_logging.h warning with GCC 9

### PR DESCRIPTION
**Pull request by rg3igalia**
This fixes issue #907.

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@jzulauf-lunarg, this LGTM, but you should take a quick look.

**Comment by rg3igalia** [comment]
Sure. I force-pushed with default constructors and operators and included the perfect forwarding constructor.

**Comment by jzulauf-lunarg** [comment]
@rg3igalia -- I appreciate the update.  Clang-format has some complaints, perhaps trailing whitespace or tabs vs. spaces?

**Comment by rg3igalia** [comment]
> @rg3igalia -- I appreciate the update. Clang-format has some complaints, perhaps trailing whitespace or tabs vs. spaces?

My fault. Forgot to re-check it before pushing. It should be fixed now.

**Comment by jzulauf-lunarg** [comment]
@mark-lunarg -- revised approach look okay to you?

**Comment by mark-lunarg** [comment]
Yes, of course -- fabulous!

**Comment by jzulauf-lunarg** [comment]
@rg3igalia -- thanks

**Comment by rg3igalia** [comment]
> @rg3igalia -- thanks

Thanks to you for providing the final code! :smile:

**Pull request merged**
