### PR TITLE
Fix crash in vkAcquirePerformanceConfigurationINTEL

### PR DESCRIPTION
**Pull request by djdeath**
The issue is that this entry point isn't considered as a create
function so it would try to dereference one of the argument which
hasn't been filled by the implementation.

### CODE REVIEW

**Comment by djdeath** [comment]
> @djdeath, this looks great. Would you mind adding a positive test so we'll know if we break it in the future?
> I'll run it through CI in the meantime.

Hey @mark-lunarg, this is a bit tricky because it depends on an external library to setup things to have the acquire entrypoint succeed.

**Comment by mark-lunarg** [comment]
OK, were you able to verify that the changes work on your side?

**Comment by djdeath** [comment]
> OK, were you able to verify that the changes work on your side?

Yes our test suite is passing on master with this change., although my colleagues are runnign

**Comment by mark-lunarg** [comment]
OK, then skipping the test in this case is alright I guess.  Lemme run the new changes through CI...

**Comment by mark-lunarg** [comment]
Rebased and pushed to Master.  Thanks Lionel!

**Pull request closed without merging**
